/* ===== DIALOGS ===== 32 dialogs. Registry: GU.DIALOGS[id] = { title, comp, sample, dismissable } */
(function () {
  const { html, cx, Icon, app, useState, useEffect, useBusy, useCountdown, Button, Input, Checkbox, OptionRow, DialogFrame, Avatar } = GU;
  const t = (k, p) => app.t(k, p); const sel = () => app.sel; const D = (GU.DIALOGS = {});
  const B = (label, action, onClick, variant = 'primary', extra = {}) => html`<${Button} label=${label} action=${action} onClick=${onClick} variant=${variant} ...${extra} />`;
  const simple = (id, { danger, icon, body, actions, dismissable = true, titleParams }) => ({ title: `dlg.${id}.title`, sample: () => ({}), dismissable, comp: ({ props, close }) => html`<${DialogFrame} id=${'DLG-' + id} title=${t(`dlg.${id}.title`, titleParams ? titleParams(props) : undefined)} body=${body ? body(props) : t(`dlg.${id}.body`)} onClose=${close} dismissable=${dismissable} danger=${danger} icon=${icon} actions=${actions(props, close)} />` });

  /* OS-style permission simulation used by DLG-03/04/05 */
  function PermissionSim({ title, onAllow, onDeny, id }) { return html`<${DialogFrame} id=${id + '.system'} title=${title} body=${t('dlg.system.permissionBody')} onClose=${onDeny} dismissable=${false} icon="smartphone" actions=${html`<div class="dialog-actions is-row" style="margin:0"><${Button} variant="tonal" label=${t('dlg.system.allow')} action=${id + '.system.allow'} onClick=${onAllow} /><${Button} variant="outline" label=${t('dlg.system.deny')} action=${id + '.system.deny'} onClick=${onDeny} /></div>`} />`; }
  function permissionDialog(id, key, { icon, onGranted, onDenied, notNow }) {
    D['DLG-' + id] = { title: `dlg.${id}.title`, sample: () => ({}), comp: ({ props, close }) => { const [sys, setSys] = useState(false);
      if (sys) return html`<${PermissionSim} id=${'DLG-' + id} title=${t(`dlg.${id}.title`)} onAllow=${() => { app.dispatch('session.set', { [key]: 'granted', ...(id === '03' ? { notifAskedAt: Date.now() } : {}) }); close(); onGranted && onGranted(props); }} onDeny=${() => { app.dispatch('session.set', { [key]: 'denied', ...(id === '03' ? { notifAskedAt: Date.now() } : {}) }); close(); onDenied && onDenied(props); }} />`;
      return html`<${DialogFrame} id=${'DLG-' + id} title=${t(`dlg.${id}.title`)} body=${t(`dlg.${id}.body`)} onClose=${() => { notNow && notNow(); close(); }} icon=${icon} actions=${html`${B(t('dlg.permission.allow'), `DLG-${id}.allow`, () => setSys(true))}${B(t('dlg.permission.notNow'), `DLG-${id}.notNow`, () => { notNow && notNow(); close(); }, 'text')}`} />`; } };
  }
  permissionDialog('03', 'notifPermission', { icon: 'bell-ring', onGranted: () => app.toast('TST-19'), notNow: () => app.dispatch('session.set', { notifAskedAt: Date.now() }) });
  permissionDialog('04', 'cameraPermission', { icon: 'camera', onGranted: (p) => p.onGranted && p.onGranted(), onDenied: () => app.toast('TST-32') });
  permissionDialog('05', 'galleryPermission', { icon: 'images', onGranted: (p) => p.onGranted && p.onGranted() });

  D['DLG-01'] = simple('01', { danger: true, icon: 'ban', actions: (p, close) => html`${B(t('dlg.01.support'), 'DLG-01.support', () => { close(); app.openDialog('DLG-32', { url: 'mailto:destek@gumushane.edu.tr' }); })}${B(t('common.ok'), 'DLG-01.ok', close, 'text')}` });
  D['DLG-02'] = { title: 'dlg.02.title', sample: () => ({}), comp: ({ close }) => { const until = app.state.session.lockedUntil || Date.now() + 30000; const left = useCountdown(until); useEffect(() => { if (left === 0) app.dispatch('session.set', { failedAttempts: 0, lockedUntil: null }); }, [left === 0]); return html`<${DialogFrame} id="DLG-02" title=${t('dlg.02.title')} body=${left > 0 ? t('dlg.02.body', { s: left }) : t('dlg.02.unlocked')} onClose=${close} icon="lock" actions=${html`${B(t('common.ok'), 'DLG-02.ok', close)}${B(t('auth.forgot'), 'DLG-02.forgot', () => { close(); app.nav.push('AUT-04'); }, 'text')}`} />`; } };
  D['DLG-06'] = simple('06', { icon: 'log-out', actions: (p, close) => html`${B(t('auth.logout'), 'DLG-06.logout', () => { close(); GU.auth.logout(); })}${B(t('common.giveUp'), 'DLG-06.cancel', close, 'text')}` });
  D['DLG-07'] = simple('07', { danger: true, icon: 'x', body: (p) => t('dlg.07.body', { club: (sel().club(p.clubId) || {}).name }), actions: (p, close) => html`${B(t('application.cancel'), 'DLG-07.confirm', () => { if (!app.requireOnline()) return; app.dispatch('membership.cancel', { clubId: p.clubId, userId: app.uid() }); close(); app.toast('TST-40'); if (app.nav.current().screen === 'CLB-05') app.nav.back(); }, 'danger')}${B(t('common.giveUp'), 'DLG-07.cancel', close, 'text')}`, sample: () => ({ clubId: 'c06' }) });
  D['DLG-07'].sample = () => ({ clubId: 'c06' });
  D['DLG-08'] = simple('08', { danger: true, icon: 'log-out', body: (p) => t('dlg.08.body', { club: (sel().club(p.clubId) || {}).name }), actions: (p, close) => html`${B(t('club.leave'), 'DLG-08.confirm', () => { if (!app.requireOnline()) return; app.dispatch('membership.leave', { clubId: p.clubId, userId: app.uid() }); close(); app.ui.closeAllSheets(); app.toast('TST-39'); }, 'danger')}${B(t('common.giveUp'), 'DLG-08.cancel', close, 'text')}` }); D['DLG-08'].sample = () => ({ clubId: 'c01' });
  D['DLG-09'] = simple('09', { icon: 'crown', actions: (p, close) => html`${B(t('mgtMembers.transfer'), 'DLG-09.transfer', () => { close(); app.openSheet('SHT-25', { mode: 'transfer', clubId: p.clubId, onSelect: (uid) => { app.closeSheet(); app.openDialog('DLG-21', { clubId: p.clubId, userId: uid }); } }); })}${B(t('common.ok'), 'DLG-09.ok', close, 'text')}` }); D['DLG-09'].sample = () => ({ clubId: 'c03' });
  D['DLG-10'] = simple('10', { danger: true, icon: 'trash-2', actions: (p, close) => html`${B(t('common.delete'), 'DLG-10.confirm', () => { const snap = app.store.get(); app.dispatch('post.delete', { postId: p.postId }); close(); if (app.nav.current().screen === 'FED-02') app.nav.back(); app.toast('TST-45', { what: t('feed.type.post'), undo: () => app.store.restore(snap) }); }, 'danger')}${B(t('common.giveUp'), 'DLG-10.cancel', close, 'text')}` }); D['DLG-10'].sample = () => ({ postId: 'p07' });
  D['DLG-11'] = simple('11', { danger: true, icon: 'trash-2', actions: (p, close) => html`${B(t('common.delete'), 'DLG-11.confirm', () => { const snap = app.store.get(); app.dispatch('comment.delete', { commentId: p.commentId }); close(); app.toast('TST-45', { what: t('feed.comment'), undo: () => app.store.restore(snap) }); }, 'danger')}${B(t('common.giveUp'), 'DLG-11.cancel', close, 'text')}` }); D['DLG-11'].sample = () => ({ commentId: 'cm01' });
  D['DLG-12'] = simple('12', { icon: 'shield-check', actions: (p, close) => html`${B(t('common.ok'), 'DLG-12.ok', close)}${p.userId ? B(t('dlg.12.block', { name: (sel().user(p.userId) || {}).name }), 'DLG-12.block', () => { close(); app.openDialog('DLG-13', { userId: p.userId }); }, 'text') : null}` }); D['DLG-12'].sample = () => ({ userId: 'u001' });
  D['DLG-13'] = simple('13', { danger: true, icon: 'ban', titleParams: (p) => ({ name: (sel().user(p.userId) || {}).name }), actions: (p, close) => html`${B(t('sht.27.block'), 'DLG-13.confirm', () => { const snap = app.store.get(); const usr = sel().user(p.userId); app.dispatch('user.block', { userId: app.uid(), targetId: p.userId }); close(); app.toast('TST-09', { name: usr.name, undo: () => app.store.restore(snap) }); }, 'danger')}${B(t('common.giveUp'), 'DLG-13.cancel', close, 'text')}` }); D['DLG-13'].sample = () => ({ userId: 'u001' });
  D['DLG-14'] = simple('14', { danger: true, icon: 'calendar-x', body: (p) => (p.waitlist ? t('dlg.14.bodyWaitlist') : t('dlg.14.body')), actions: (p, close) => html`${B(t('common.giveUp'), 'DLG-14.confirm', () => { if (!app.requireOnline()) return; app.dispatch('rsvp.leave', { eventId: p.eventId, userId: app.uid() }); close(); app.toast('TST-42'); p.onDone && p.onDone(); }, 'danger')}${B(t('dlg.14.stay'), 'DLG-14.cancel', close, 'text')}` }); D['DLG-14'].sample = () => ({ eventId: 'e01' });
  D['DLG-15'] = simple('15', { icon: 'hourglass', body: (p) => t('dlg.15.body', { n: sel().waitlist(p.eventId).length }), actions: (p, close) => html`${B(t('event.cta.waitlist'), 'DLG-15.confirm', () => { if (!app.requireOnline()) return; const res = app.dispatch('rsvp.join', { eventId: p.eventId, userId: app.uid(), reminder: '1h' }); close(); app.toast('TST-43', { n: res.position || sel().waitlist(p.eventId).length }); })}${B(t('common.giveUp'), 'DLG-15.cancel', close, 'text')}` }); D['DLG-15'].sample = () => ({ eventId: 'e03' });
  D['DLG-16'] = simple('16', { danger: true, icon: 'calendar-x', body: (p) => { const ev = sel().event(p.eventId) || {}; return t('dlg.16.body', { event: ev.title, reason: ev.cancelReason ? t('cancelReason.' + ev.cancelReason) : '' }); }, actions: (p, close) => html`${B(t('common.ok'), 'DLG-16.ok', close)}${B(t('dlg.16.similar'), 'DLG-16.similar', () => { close(); app.nav.resetTo('EVT-01'); }, 'text')}` }); D['DLG-16'].sample = () => ({ eventId: 'e21' });
  D['DLG-17'] = simple('17', { icon: 'list-checks', body: (p) => t('dlg.17.' + (p.kind || 'approve'), { count: p.count || 0 }), actions: (p, close) => html`${B(p.kind === 'reject' ? t('applications.reject') : t('common.confirm'), 'DLG-17.confirm', () => (p.onConfirm ? p.onConfirm() : close()), p.kind === 'reject' ? 'danger' : 'primary')}${B(t('common.giveUp'), 'DLG-17.cancel', close, 'text')}` }); D['DLG-17'].sample = () => ({ kind: 'approve', count: 3 });
  D['DLG-18'] = simple('18', { icon: 'refresh-cw', body: (p) => t('dlg.18.body', { result: p.result || t('status.rejected') }), actions: (p, close) => html`${B(t('common.ok'), 'DLG-18.ok', () => { close(); p.onOk && p.onOk(); })}` }); D['DLG-18'].sample = () => ({ result: 'reddedildi' });
  D['DLG-19'] = { title: 'dlg.19.title', sample: () => ({ clubId: 'c03', userId: 'u001' }), comp: ({ props, close }) => { const usr = sel().user(props.userId) || {}; const [reason, setReason] = useState(''); return html`<${DialogFrame} id="DLG-19" title=${t('dlg.19.title', { name: usr.name })} body=${t('dlg.19.body')} onClose=${close} danger icon="user-x" actions=${html`${B(t('dlg.19.confirm'), 'DLG-19.confirm', () => { if (!app.guard(props.clubId)) return; const snap = app.store.get(); app.dispatch('membership.remove', { clubId: props.clubId, userId: props.userId, actorId: app.uid(), reason }); close(); app.ui.closeAllSheets(); if (app.nav.current().screen === 'CLB-07') app.nav.back(); app.toast('TST-47', { name: usr.name, undo: () => app.store.restore(snap) }); }, 'danger')}${B(t('common.giveUp'), 'DLG-19.cancel', close, 'text')}`}><${Input} label=${t('dlg.19.reason')} value=${reason} onInput=${setReason} multiline rows=${2} maxLength=${200} action="DLG-19.reason" /></${DialogFrame}>`; } };
  D['DLG-20'] = simple('20', { icon: 'user-cog', body: (p) => { const m = sel().membership(p.clubId, p.userId) || {}; return t('dlg.20.body', { name: (sel().user(p.userId) || {}).name, oldRole: t('role.' + (m.role || 'member')), newRole: t('role.' + p.role) }); }, actions: (p, close) => html`${B(t('common.confirm'), 'DLG-20.confirm', () => { if (!app.guard(p.clubId)) return; app.dispatch('membership.setRole', { clubId: p.clubId, userId: p.userId, role: p.role, actorId: app.uid() }); close(); app.ui.closeAllSheets(); app.toast('TST-46', { name: (sel().user(p.userId) || {}).name, role: t('role.' + p.role) }); })}${B(t('common.giveUp'), 'DLG-20.cancel', close, 'text')}` }); D['DLG-20'].sample = () => ({ clubId: 'c03', userId: 'u001', role: 'board' });
  D['DLG-21'] = { title: 'dlg.21.title', sample: () => ({ clubId: 'c03', userId: 'u001' }), comp: ({ props, close }) => { const [step, setStep] = useState(1); const [word, setWord] = useState(''); const usr = sel().user(props.userId) || {}; const ok = word.trim().toLocaleUpperCase('tr') === 'DEVRET';
    return html`<${DialogFrame} id="DLG-21" title=${t('dlg.21.title')} body=${step === 1 ? t('dlg.21.body1', { name: usr.name }) : t('dlg.21.body2')} onClose=${close} danger icon="crown" actions=${html`${step === 1 ? B(t('common.continue'), 'DLG-21.next', () => setStep(2), 'danger') : B(t('dlg.21.confirm'), 'DLG-21.confirm', () => { if (!app.guard(props.clubId)) return; const club = sel().club(props.clubId); app.dispatch('membership.transfer', { clubId: props.clubId, fromId: club.presidentId, toId: props.userId }); close(); app.ui.closeAllSheets(); app.toast('TST-49', { name: usr.name }); }, 'danger', { disabled: !ok, onDisabledClick: () => app.toast('TST-X20') })}${B(t('common.giveUp'), 'DLG-21.cancel', close, 'text')}`}>${step === 2 ? html`<${Input} value=${word} onInput=${setWord} placeholder="DEVRET" action="DLG-21.word" ariaLabel=${t('dlg.21.body2')} autofocus />` : null}</${DialogFrame}>`; } };
  D['DLG-22'] = { title: 'dlg.22.title', sample: () => ({ count: 24, onConfirm: () => {} }), comp: ({ props, close }) => { const [notify, setNotify] = useState(true); return html`<${DialogFrame} id="DLG-22" title=${t('dlg.22.title')} body=${t('dlg.22.body')} onClose=${close} icon="calendar-check" actions=${html`${B(t('eventForm.publish'), 'DLG-22.confirm', () => (props.onConfirm ? props.onConfirm(notify) : close()))}${B(t('dlg.22.back'), 'DLG-22.cancel', close, 'text')}`}><label class="row gap10" style="cursor:pointer"><${Checkbox} checked=${notify} onChange=${setNotify} action="DLG-22.notify" label=${t('dlg.22.notify', { count: props.count || 0 })} /><span class="t-body-s">${t('dlg.22.notify', { count: props.count || 0 })}</span></label></${DialogFrame}>`; } };
  D['DLG-23'] = { title: 'dlg.23.title', sample: () => ({ eventId: 'e03' }), comp: ({ props, close }) => { const [reason, setReason] = useState(null); const [err, setErr] = useState(''); const ev = sel().event(props.eventId); const n = ev ? sel().registered(ev.id).length : 0;
    return html`<${DialogFrame} id="DLG-23" title=${t('dlg.23.title')} body=${t('dlg.23.body', { count: n })} onClose=${close} danger icon="calendar-x" actions=${html`${B(t('dlg.23.confirm'), 'DLG-23.confirm', () => { if (!reason) { setErr(t('auth.err.required')); return; } if (!app.guard(ev.clubId)) return; app.dispatch('event.cancel', { eventId: ev.id, reason, actorId: app.uid() }); close(); app.ui.closeAllSheets(); app.toast('TST-48'); }, 'danger')}${B(t('common.giveUp'), 'DLG-23.cancel', close, 'text')}`}><div class="col" style="margin:0 -12px">${['weather', 'speaker', 'venue', 'other'].map((r) => html`<${OptionRow} key=${r} label=${t('cancelReason.' + r)} checked=${reason === r} action=${'DLG-23.reason.' + r} onClick=${() => { setReason(r); setErr(''); }} />`)}</div>${err ? html`<div class="field-help is-error" role="alert"><${Icon} name="triangle-alert" size=${14} /><span>${err}</span></div>` : null}</${DialogFrame}>`; } };
  D['DLG-24'] = simple('24', { icon: 'megaphone', actions: (p, close) => html`${B(t('dlg.24.silent'), 'DLG-24.silent', () => (p.onPublishSilent ? p.onPublishSilent() : close()))}${B(t('common.giveUp'), 'DLG-24.cancel', close, 'text')}` });
  D['DLG-25'] = simple('25', { icon: 'triangle-alert', actions: (p, close) => html`${p.onSave ? B(t('common.save'), 'DLG-25.save', p.onSave) : null}${B(t('dlg.25.discard'), 'DLG-25.discard', () => (p.onDiscard ? p.onDiscard() : close()), 'danger-outline')}${B(t('dlg.25.keep'), 'DLG-25.keep', () => (p.onKeep ? p.onKeep() : close()), 'text')}` }); D['DLG-25'].sample = () => ({ onSave: () => app.closeDialog(), onDiscard: () => app.closeDialog(), onKeep: () => app.closeDialog() });
  D['DLG-26'] = simple('26', { icon: 'download', dismissable: false, actions: (p, close) => html`${B(t('dlg.26.update'), 'DLG-26.update', () => { app.toast('TST-58', { what: t('dlg.26.store') }); close(); })}` });
  D['DLG-27'] = simple('27', { icon: 'lock', dismissable: false, actions: (p, close) => html`${B(t('auth.login.cta'), 'DLG-27.login', () => { close(); GU.auth.logout(); })}` });
  D['DLG-28'] = { title: 'dlg.28.title', sample: () => ({ clubId: 'c10' }), comp: ({ props, close }) => { const club = sel().club(props.clubId) || {}; const suspending = club.status === 'active'; const [reason, setReason] = useState(''); const [err, setErr] = useState('');
    return html`<${DialogFrame} id="DLG-28" title=${suspending ? t('dlg.28.title', { club: club.name }) : t('dlg.28.titleActivate', { club: club.name })} body=${suspending ? t('dlg.28.body') : t('dlg.28.bodyActivate')} onClose=${close} danger=${suspending} icon=${suspending ? 'ban' : 'circle-check'} actions=${html`${B(suspending ? t('adminClubs.suspend') : t('adminClubs.activate'), 'DLG-28.confirm', () => { if (suspending && !reason.trim()) { setErr(t('auth.err.required')); return; } app.dispatch('club.setStatus', { clubId: club.id, status: suspending ? 'suspended' : 'active', reason: reason.trim() }); if (props.reportId) app.dispatch('report.resolve', { reportId: props.reportId, action: 'suspended', actorId: app.uid() }); close(); app.ui.closeAllSheets(); app.toast('TST-50', { suspended: suspending }); }, suspending ? 'danger' : 'primary')}${B(t('common.giveUp'), 'DLG-28.cancel', close, 'text')}`}>${suspending ? html`<${Input} label=${t('dlg.28.reason')} value=${reason} onInput=${(v) => { setReason(v); setErr(''); }} multiline rows=${2} maxLength=${200} error=${err} action="DLG-28.reason" autofocus />` : null}</${DialogFrame}>`; } };
  D['DLG-29'] = simple('29', { danger: true, icon: 'trash-2', actions: (p, close) => html`${B(t('dlg.29.confirm'), 'DLG-29.confirm', () => { app.dispatch('report.resolve', { reportId: p.reportId, action: 'removed', actorId: app.uid() }); close(); app.ui.closeAllSheets(); app.toast('TST-51'); }, 'danger')}${B(t('common.giveUp'), 'DLG-29.cancel', close, 'text')}` }); D['DLG-29'].sample = () => ({ reportId: 'r01' });
  D['DLG-30'] = { title: 'dlg.30.title', sample: () => ({ userId: 'u077' }), comp: ({ props, close }) => { const usr = sel().user(props.userId) || {}; const suspending = usr.status !== 'suspended'; const [reason, setReason] = useState(''); const [err, setErr] = useState('');
    return html`<${DialogFrame} id="DLG-30" title=${suspending ? t('dlg.30.title', { name: usr.name }) : t('dlg.30.titleUnsuspend', { name: usr.name })} body=${suspending ? t('dlg.30.body') : t('dlg.30.bodyUnsuspend')} onClose=${close} danger=${suspending} icon=${suspending ? 'ban' : 'circle-check'} actions=${html`${B(suspending ? t('adminUsers.suspend') : t('adminUsers.unsuspend'), 'DLG-30.confirm', () => { if (suspending && !reason.trim()) { setErr(t('auth.err.required')); return; } app.dispatch('user.setStatus', { userId: usr.id, status: suspending ? 'suspended' : 'active', reason: reason.trim() }); if (props.reportId && suspending) app.dispatch('report.resolve', { reportId: props.reportId, action: 'suspended', actorId: app.uid() }); close(); app.ui.closeAllSheets(); app.toast('TST-52', { suspended: suspending }); }, suspending ? 'danger' : 'primary')}${B(t('common.giveUp'), 'DLG-30.cancel', close, 'text')}`}>${suspending ? html`<${Input} label=${t('dlg.28.reason')} value=${reason} onInput=${(v) => { setReason(v); setErr(''); }} multiline rows=${2} maxLength=${200} error=${err} action="DLG-30.reason" autofocus />` : null}</${DialogFrame}>`; } };
  D['DLG-31'] = simple('31', { danger: true, icon: 'trash-2', actions: (p, close) => html`${B(t('common.delete'), 'DLG-31.confirm', () => { const snap = app.store.get(); app.dispatch('event.delete', { eventId: p.eventId }); close(); app.ui.closeAllSheets(); if (app.nav.current().screen === 'EVT-02') app.nav.back(); app.toast('TST-45', { what: t('status.draft'), undo: () => app.store.restore(snap) }); }, 'danger')}${B(t('common.giveUp'), 'DLG-31.cancel', close, 'text')}` }); D['DLG-31'].sample = () => ({ eventId: 'e22' });
  D['DLG-32'] = { title: 'dlg.32.title', sample: () => ({ url: 'https://gumushane.edu.tr' }), comp: ({ props, close }) => html`<${DialogFrame} id="DLG-32" title=${t('dlg.32.title')} onClose=${close} icon="external-link" actions=${html`${B(t('common.open'), 'DLG-32.open', () => { close(); app.toast('TST-58', { what: t('dlg.32.link') }); })}${B(t('common.giveUp'), 'DLG-32.cancel', close, 'text')}`}><p class="t-body-s c-sec">${t('dlg.32.body1')} <span class="code break">${props.url}</span></p><p class="t-body-s c-sec">${t('dlg.32.body2')}</p></${DialogFrame}>` };
})();

/* ===== TOASTS ===== 58 toasts (+ extra variants TST-X*). Registry: GU.TOASTS[id] = { kind, text(props), actionLabel(props) } */
(function () {
  const { app } = GU; const t = (k, p) => app.t(k, p); const T = (GU.TOASTS = {});
  const def = (id, kind, text, actionLabel) => { T['TST-' + id] = { kind, text, actionLabel }; };
  const undo = () => t('common.undo');
  def('01', 'error', () => t('tst.01')); def('02', 'info', () => t('tst.02')); def('03', 'success', () => t('tst.03')); def('04', 'info', () => t('tst.04')); def('05', 'success', (p) => t('tst.05', { name: p.name || '' }));
  def('06', 'info', () => t('tst.06'), undo); def('07', 'success', () => t('tst.07')); def('08', 'success', () => t('tst.08')); def('09', 'info', (p) => (p.unblocked ? t('tst.09.unblocked', { name: p.name }) : t('tst.09.blocked', { name: p.name })), undo); def('10', 'info', () => t('tst.10'));
  def('11', 'success', (p) => (p.saved ? t('tst.11.saved') : t('tst.11.removed')), undo); def('12', 'success', () => t('tst.12')); def('13', 'success', () => t('tst.13')); def('14', 'success', () => t('tst.14'), () => t('common.view')); def('15', 'success', () => t('tst.15'));
  def('16', 'info', () => t('tst.16'), undo); def('17', 'success', () => t('tst.17')); def('18', 'success', () => t('tst.18')); def('19', 'success', () => t('tst.19')); def('20', 'info', () => t('tst.20'));
  def('21', 'success', () => t('tst.21')); def('22', 'success', () => t('tst.22')); def('23', 'success', (p) => t('tst.23', { no: p.no || '#GU-4821' })); def('24', 'error', () => t('tst.24')); def('25', 'success', () => t('tst.25'));
  def('26', 'info', () => t('tst.26')); def('27', 'success', (p) => t('tst.27', { name: p.name }), undo); def('28', 'info', (p) => t('tst.28', { name: p.name }), undo); def('29', 'success', () => t('tst.29')); def('30', 'success', () => t('tst.30'), () => t('common.view'));
  def('31', 'success', (p) => t('tst.31', { name: p.name }), undo); def('32', 'error', () => t('tst.32'), () => t('scan.goSettings')); def('33', 'success', () => t('tst.33')); def('34', 'success', () => t('tst.34'), () => t('application.goClub')); def('35', 'success', () => t('tst.35'));
  def('36', 'success', () => t('tst.36')); def('37', 'success', (p) => (p.off ? t('tst.37.off') : t('tst.37.set'))); def('38', 'success', () => t('tst.38')); def('39', 'info', () => t('tst.39')); def('40', 'info', () => t('tst.40'));
  def('41', 'success', () => t('tst.41'), () => t('event.cta.ticket')); def('42', 'info', () => t('tst.42')); def('43', 'success', (p) => t('tst.43', { n: p.n || 1 })); def('44', 'success', () => t('tst.44')); def('45', 'info', (p) => t('tst.45', { what: p.what || '' }), undo);
  def('46', 'success', (p) => t('tst.46', { name: p.name, role: p.role })); def('47', 'info', (p) => t('tst.47', { name: p.name }), undo); def('48', 'info', () => t('tst.48')); def('49', 'success', (p) => t('tst.49', { name: p.name })); def('50', 'info', (p) => (p.suspended ? t('tst.50.suspended') : t('tst.50.activated')));
  def('51', 'success', () => t('tst.51')); def('52', 'info', (p) => (p.suspended ? t('tst.52.suspended') : t('tst.52.unsuspended'))); def('53', 'success', (p) => (p.pinned ? t('tst.53.pinned') : t('tst.53.unpinned'))); def('54', 'info', (p) => (p.open ? t('tst.54.opened') : t('tst.54.closed'))); def('55', 'info', (p) => t('tst.55', { title: p.title || '' }), () => t('common.view'));
  def('56', 'info', () => t('tst.56')); def('57', 'success', () => t('tst.57')); def('58', 'info', (p) => t('tst.58', { what: p.what || '' }));
  // extra situational toasts (not part of the numbered catalog)
  def('X1', 'info', () => t('tst.x1')); def('X2', 'info', () => t('tst.x2')); def('X3', 'info', (p) => t('tst.x3', { s: p.s || 0 })); def('X4', 'info', (p) => t('tst.x4', { date: p.date || '' })); def('X5', 'info', () => t('tst.x5')); def('X6', 'info', () => t('tst.x6')); def('X7', 'info', () => t('tst.x7')); def('X8', 'info', (p) => t('tst.x8', { count: p.count || 0 }));
  def('X9', 'info', () => t('tst.x9')); def('X10', 'info', () => t('tst.x10')); def('X11', 'info', () => t('tst.x11')); def('X12', 'info', () => t('tst.x12')); def('X13', 'success', (p) => t('tst.x13', { name: p.name || '' })); def('X14', 'info', () => t('tst.x14')); def('X15', 'info', (p) => (p.open ? t('tst.x15.opened') : t('tst.x15.closed'))); def('X16', 'info', () => t('tst.x16'));
  def('X17', 'success', () => t('tst.x17')); def('X18', 'info', () => t('tst.x18')); def('X19', 'success', () => t('tst.x19')); def('X20', 'info', () => t('tst.x20'));
  GU.TOAST_IDS = Object.keys(T).filter((k) => /^TST-\d{2}$/.test(k));
})();
