/* ===== MAP_PAGE + QA_PAGE ===== flow diagrams · screen inventory · assumptions · action registry · dead-element scan · self-check */
(function () {
  const { html, cx, Icon, app, store, nav, registry, useState, useEffect, useRef, Button, Badge, Chip, Input, Card, h, render, downloadText, I18N, MISSING_KEYS, USED_ICONS, ICON_NAMES } = GU;
  const t = (k, p) => app.t(k, p);
  GU.defineDictionary({
    'map.title': ['Ekran Haritası', 'Screen Map'], 'map.desc': ['Akış diyagramları, 51 ekranlık envanter ve teslimde yapılan varsayımlar. Düğüme dokunmak prototipi ilgili ekranda, uygun demo hesapla açar.', 'Flow diagrams, the 51-screen inventory and the assumptions made. Tapping a node opens the prototype at that screen with a suitable demo account.'], 'map.flows': ['Akış diyagramları', 'Flow diagrams'], 'map.inventory': ['Ekran envanteri', 'Screen inventory'], 'map.assumptions': ['Varsayımlar', 'Assumptions'], 'map.col.id': ['ID', 'ID'], 'map.col.name': ['Ekran', 'Screen'], 'map.col.route': ['Rota', 'Route'], 'map.col.roles': ['Roller', 'Roles'], 'map.col.open': ['Aç', 'Open'], 'map.roles.all': ['Tümü', 'All'], 'map.roles.guest': ['Oturumsuz', 'Signed out'], 'map.roles.member': ['Üye+', 'Member+'], 'map.roles.manager': ['YK, Başkan (Danışman salt okunur)', 'Board, President (Advisor read-only)'], 'map.roles.admin': ['Süper admin', 'Super admin'],
    'qa.title': ['Kalite Kontrol', 'Quality Check'], 'qa.desc': ['Aksiyon kapsamı, ölü öğe taraması ve Bölüm 15 self-check raporu.', 'Action coverage, dead-element scan and the section-15 self-check report.'], 'qa.coverage': ['Kapsam özeti', 'Coverage summary'], 'qa.screens': ['Ekran', 'Screens'], 'qa.sheets': ['Sheet', 'Sheets'], 'qa.dialogs': ['Dialog', 'Dialogs'], 'qa.toasts': ['Toast', 'Toasts'], 'qa.i18nMissing': ['i18n eksik anahtar', 'Missing i18n keys'], 'qa.missingIds': ['Eksik kimlikler', 'Missing ids'], 'qa.registry': ['Aksiyon kayıt defteri', 'Action registry'], 'qa.registryNote': ['Oturum içinde tıklanan her data-action burada toplanır; sonuç türü tıklamadan sonra gözlemlenerek sınıflandırılır.', 'Every data-action clicked this session is collected here; the result type is classified by observing what changed after the click.'], 'qa.col.action': ['Aksiyon', 'Action'], 'qa.col.screen': ['Ekran', 'Screen'], 'qa.col.result': ['Sonuç türü', 'Result type'], 'qa.col.count': ['Tıklanma', 'Clicks'], 'qa.noClicks': ['Henüz tıklama kaydı yok. Prototipi kullanmaya başla.', 'No clicks recorded yet. Start using the prototype.'], 'qa.scanThis': ['Bu ekranı tara', 'Scan this screen'], 'qa.scanAll': ['Tüm ekranları tara', 'Scan all screens'], 'qa.scanning': ['Taranıyor… {a}/{b}', 'Scanning… {a}/{b}'], 'qa.scanResult': ['{total} etkileşimli öğe · {dead} ölü öğe', '{total} interactive elements · {dead} dead elements'], 'qa.deadList': ['Ölü öğeler', 'Dead elements'], 'qa.noDead': ['Ölü öğe yok', 'No dead elements'], 'qa.selfCheck': ['Self-check raporu (Bölüm 15)', 'Self-check report (section 15)'], 'qa.pass': ['GEÇTİ', 'PASS'], 'qa.fail': ['KALDI', 'FAIL'], 'qa.pending': ['TARA', 'RUN SCAN'], 'qa.download': ['Raporu indir', 'Download report'], 'qa.runAll': ['Kontrolleri çalıştır', 'Run checks'], 'qa.dead.session': ['Oturumda yakalanan ölü tıklama', 'Dead clicks caught this session'],
  });
  const INVENTORY = [
    ['SYS-01', '/splash', 'all', null], ['SYS-02', '/error', 'all', 'u_mehmet'], ['SYS-03', '/offline', 'all', 'u_mehmet'], ['SYS-04', '/not-found', 'all', 'u_mehmet'], ['ONB-01', '/onboarding', 'guest', null],
    ['AUT-01', '/login', 'guest', null], ['AUT-02', '/register', 'guest', null], ['AUT-03', '/verify', 'guest', 'u_unverified'], ['AUT-04', '/reset', 'guest', null], ['AUT-05', '/setup-profile', 'guest', 'u_unverified'], ['AUT-06', '/legal/:tip', 'all', null],
    ['CLB-01', '/clubs', 'all', 'u_ayse'], ['CLB-02', '/clubs/search', 'all', 'u_ayse'], ['CLB-03', '/clubs/:id', 'all', 'u_ayse', { id: 'c03' }], ['CLB-04', '/clubs/:id/applied', 'all', 'u_mehmet', { id: 'c06' }], ['CLB-05', '/clubs/:id/application', 'all', 'u_mehmet', { id: 'c06' }], ['CLB-06', '/clubs/:id/members', 'member', 'u_mehmet', { id: 'c01' }], ['CLB-07', '/users/:id', 'member', 'u_burak', { id: 'u001', clubId: 'c03' }],
    ['FED-01', '/clubs/:id (Gönderiler)', 'member', 'u_mehmet', { id: 'c01' }], ['FED-02', '/clubs/:id/posts/:postId', 'member', 'u_mehmet', { clubId: 'c01', postId: 'p01' }], ['FED-03', '/clubs/:id/compose', 'manager', 'u_burak', { clubId: 'c03' }],
    ['EVT-01', '/events', 'all', 'u_ayse'], ['EVT-02', '/events/:id', 'all', 'u_ayse', { id: 'e01' }], ['EVT-03', '/events/:id/ticket', 'member', 'u_mehmet', { id: 'e01' }], ['EVT-04', '/events/mine', 'all', 'u_mehmet'],
    ['NTF-01', '/notifications', 'all', 'u_mehmet'], ['NTF-02', '/settings/notifications', 'all', 'u_mehmet'],
    ['PRF-01', '/profile', 'all', 'u_mehmet'], ['PRF-02', '/profile/edit', 'all', 'u_mehmet'], ['PRF-03', '/profile/clubs', 'all', 'u_mehmet'], ['PRF-04', '/profile/saved', 'all', 'u_mehmet'],
    ['SET-01', '/settings', 'all', 'u_mehmet'], ['SET-02', '/settings/blocked', 'all', 'u_mehmet'], ['SET-03', '/settings/delete', 'all', 'u_burak'], ['SET-04', '/settings/about', 'all', 'u_mehmet'], ['SET-05', '/settings/support', 'all', 'u_mehmet'],
    ['MGT-01', '/manage/:clubId', 'manager', 'u_burak', { clubId: 'c03' }], ['MGT-02', '/manage/:clubId/applications', 'manager', 'u_burak', { clubId: 'c03' }], ['MGT-03', '/manage/:clubId/members', 'manager', 'u_burak', { clubId: 'c03' }], ['MGT-04', '/manage/:clubId/events', 'manager', 'u_burak', { clubId: 'c03' }], ['MGT-05', '/manage/:clubId/events/new', 'manager', 'u_burak', { clubId: 'c03' }], ['MGT-06', '/manage/:clubId/events/:id/attendance', 'manager', 'u_elif', { clubId: 'c01', eventId: 'e17' }], ['MGT-07', '/manage/:clubId/events/:id/scan', 'manager', 'u_elif', { clubId: 'c01', eventId: 'e17' }], ['MGT-08', '/manage/:clubId/content', 'manager', 'u_burak', { clubId: 'c03' }], ['MGT-09', '/manage/:clubId/settings', 'manager', 'u_burak', { clubId: 'c03' }], ['MGT-10', '/manage/:clubId/activity', 'manager', 'u_burak', { clubId: 'c03' }],
    ['ADM-01', '/admin', 'admin', 'u_admin'], ['ADM-02', '/admin/clubs', 'admin', 'u_admin'], ['ADM-03', '/admin/clubs/new', 'admin', 'u_admin'], ['ADM-04', '/admin/reports', 'admin', 'u_admin'], ['ADM-05', '/admin/users', 'admin', 'u_admin'],
  ];
  const EXTRA_SCANS = [['CLB-03', 'u_mehmet', { id: 'c01' }], ['CLB-03', 'u_burak', { id: 'c03' }], ['CLB-03', 'u_zeynep', { id: 'c01' }], ['EVT-02', 'u_mehmet', { id: 'e03' }], ['EVT-02', 'u_burak', { id: 'e03' }], ['MGT-01', 'u_zeynep', { clubId: 'c01' }], ['MGT-02', 'u_elif', { clubId: 'c01' }], ['FED-03', 'u_elif', { clubId: 'c01' }], ['SET-03', 'u_ayse', {}], ['CLB-05', 'u_mehmet', { id: 'c05' }], ['PRF-01', 'u_burak', {}], ['CLB-01', 'u_mehmet', {}], ['NTF-01', 'u_admin', {}]];
  const FLOWS = [
    ['F1', 'Kayıt', ['ONB-01', 'AUT-02', 'AUT-03', 'AUT-05', 'CLB-01']], ['F2', 'Başvuru', ['CLB-01', 'CLB-03', 'SHT-05', 'CLB-04', 'NTF-01', 'CLB-03']], ['F3', 'Başvuru onayı', ['NTF-01', 'MGT-02', 'SHT-19', 'SHT-20', 'TST-27', 'TST-28']], ['F4', 'Etkinliğe katılım', ['EVT-01', 'EVT-02', 'SHT-12', 'EVT-03']], ['F5', 'Etkinlik yönetimi', ['MGT-04', 'MGT-05', 'DLG-22', 'MGT-06', 'MGT-07', 'SHT-24']],
    ['F6', 'İçerik', ['FED-03', 'FED-01', 'FED-02']], ['F7', 'Moderasyon', ['SHT-10', 'DLG-12', 'ADM-04', 'SHT-26', 'DLG-29']], ['F8', 'Hesap silme', ['PRF-01', 'SET-01', 'SET-03']], ['F9', 'Kulüp açma', ['ADM-02', 'ADM-03', 'SHT-25']], ['F10', 'Rol ve devir', ['MGT-03', 'SHT-21', 'SHT-22', 'DLG-20', 'SHT-25', 'DLG-21']],
  ];
  const ASSUMPTIONS = [
    ['A1', 'E-posta alan adları (ogr.gumushane.edu.tr, gumushane.edu.tr) örnektir; tek sabit ALLOWED_EMAIL_DOMAINS üzerinden değişir.', 'Email domains are examples; change the single ALLOWED_EMAIL_DOMAINS constant.'],
    ['A2', 'Bölüm listesi (24) ve kampüs mekânları (10) örnektir.', 'The department list (24) and campus venues (10) are examples.'],
    ['A3', 'QR tarama, kamera, galeri, harita, push bildirimi ve sistem izinleri simülasyondur.', 'QR scanning, camera, gallery, maps, push and system permissions are simulated.'],
    ['A4', 'Dış bağlantılar (Instagram, web, mailto, takvim, paylaşım) gerçek yönlendirme yapmaz; DLG-32 demo dialoguna gider.', 'External links do not navigate; they open the DLG-32 demo dialog.'],
    ['A5', 'Satranç kulübü anında katılım olduğundan Mehmet’in bekleyen başvurusu Müzik ve Sahne Sanatları Kulübü’ne taşındı (brief’teki tablo çelişkisi).', 'Because the Chess club is instant-join, Mehmet’s pending application was moved to the Music club (resolves a table conflict in the brief).'],
    ['A6', 'Etkinlik kayıt sayıları rsvps ile birebir eşleşsin diye kullanıcı havuzu ~230 kişiye genişletildi (brief: ~70).', 'The user pool was widened to ~230 so event registration counts match rsvps exactly (brief: ~70).'],
    ['A7', 'Burak’ın kulübünde (c03) bugünkü duyuru hakkı 0/2’den başlar ki S5 senaryosu üçüncü denemede DLG-24’ü göstersin; Elif’in kulübü (c01) 1/2’den başlar.', 'Burak’s club starts at 0/2 announcements today so scenario S5 triggers DLG-24 on the third attempt; Elif’s club starts at 1/2.'],
    ['A8', 'Herkese açık etkinliklerin event_new bildirimi üyelere ve kulüp kategorisiyle eşleşen ilgi alanına sahip kullanıcılara gider (Ayşe’nin seed bildirimleriyle tutarlı).', 'event_new for public events goes to members and users whose interests match the club category (consistent with Ayşe’s seed notifications).'],
    ['A9', 'Resmi üniversite logosu kullanıcı tarafından sağlandı ve uygulamada kullanılıyor; LogoPlaceholder yedek olarak Assets sayfasında kalır.', 'The official university logo was provided by the user and is used in the app; LogoPlaceholder remains on the Assets page as a fallback.'],
    ['A10', 'Tüm tarihler bugüne göre üretilir; gün değişince demo verisi otomatik yeniden tohumlanır (yapılan değişiklikler sıfırlanır).', 'All dates are generated relative to today; when the day changes the demo data re-seeds automatically (changes reset).'],
    ['A11', 'Alt gezinme çubuğu yalnızca sekme kök ekranlarında görünür; alt ekranlarda yapışkan CTA güvenli alana oturur.', 'The bottom navigation is shown only on tab root screens; sticky CTAs sit in the safe area on pushed screens.'],
    ['A12', 'Numaralı 58 toast’a ek olarak durum odaklı 23 yardımcı toast (TST-X1…X23) vardır; kapsam sayımına dahil edilmez.', 'In addition to the 58 numbered toasts there are 23 situational helper toasts (TST-X1…X23), excluded from the coverage count.'],
  ];

  /* ---------- scanning ---------- */
  const INTERACTIVE = 'button,a,[role=button],[role=switch],[role=tab],[role=checkbox],[role=radio],[role=option],[role=menuitem],[role=gridcell],input,textarea,select';
  function scanRoot(root, screen) { const els = [...root.querySelectorAll(INTERACTIVE)]; const dead = els.filter((el) => { const a = el.closest('[data-action]'); return !a || a.getAttribute('data-action') === 'UNSET'; }).map((el) => ({ screen, tag: el.tagName.toLowerCase(), text: (el.getAttribute('aria-label') || el.textContent || '').trim().slice(0, 60), html: el.outerHTML.slice(0, 160) })); const noLabel = els.filter((el) => el.classList.contains('iconbtn') && !el.getAttribute('aria-label')).length; return { total: els.length, dead, noLabel }; }
  function scanCurrent() { const dev = document.querySelector('.device'); if (!dev) return { total: 0, dead: [], noLabel: 0 }; return scanRoot(dev, nav.current().screen); }
  async function scanAll(onProgress) {
    const host = document.createElement('div'); host.className = 'gu-root device'; host.setAttribute('data-theme', 'light'); host.style.cssText = 'position:fixed;left:-9999px;top:0;width:390px;height:844px;overflow:hidden;pointer-events:none'; document.body.appendChild(host);
    const saved = store.state; const prevScan = GU.SCANNING; GU.SCANNING = true; const results = []; let total = 0; const deadAll = []; let noLabel = 0;
    const plan = INVENTORY.map(([id, , , user, params]) => [id, user, params || {}]).concat(EXTRA_SCANS);
    const sheets = Object.keys(GU.SHEETS).map((id) => ['sheet:' + id, /SHT-(19|20|21|22|23|24|25)/.test(id) ? 'u_burak' : /SHT-26/.test(id) ? 'u_admin' : 'u_mehmet', GU.SHEETS[id].sample()]);
    const dialogs = Object.keys(GU.DIALOGS).map((id) => ['dialog:' + id, /DLG-(17|18|19|20|21|22|23|24)/.test(id) ? 'u_burak' : /DLG-(28|29|30)/.test(id) ? 'u_admin' : 'u_mehmet', GU.DIALOGS[id].sample ? GU.DIALOGS[id].sample() : {}]);
    const items = plan.concat(sheets, dialogs); let i = 0;
    for (const [id, user, params] of items) {
      store.state = { ...saved, session: { ...saved.session, userId: user } };
      try { let vnode; if (id.startsWith('sheet:')) vnode = h(GU.SHEETS[id.slice(6)].comp, { props: params, close: () => {} }); else if (id.startsWith('dialog:')) vnode = h(GU.DIALOGS[id.slice(7)].comp, { props: params, close: () => {} }); else vnode = h(GU.SCREENS[id].comp, { params, route: { key: 'scan-' + id, params, screen: id } });
        render(h('div', { class: 'screen' }, vnode), host); const r = scanRoot(host, id + (user ? ` (${user})` : '')); total += r.total; deadAll.push(...r.dead); noLabel += r.noLabel; results.push({ id, user, total: r.total, dead: r.dead.length }); } catch (e) { results.push({ id, user, error: String(e && e.message || e) }); console.warn('scan failed', id, e); }
      render(null, host); i++; onProgress && onProgress(i, items.length); await new Promise((r) => setTimeout(r, 0));
    }
    store.state = saved; GU.SCANNING = prevScan; host.remove(); app.refresh();
    const out = { at: new Date().toISOString(), screens: results, total, dead: deadAll, noLabel, items: items.length }; GU.lastScan = out; return out;
  }
  GU.scanAll = scanAll; GU.scanCurrent = scanCurrent;

  /* ---------- self-check ---------- */
  const screenIds = () => Object.keys(GU.SCREENS).filter((k) => /^[A-Z]{3}-\d{2}$/.test(k));
  const expectedScreens = INVENTORY.map((x) => x[0]); const expectedSheets = Array.from({ length: 34 }, (_, i) => 'SHT-' + String(i + 1).padStart(2, '0')); const expectedDialogs = Array.from({ length: 32 }, (_, i) => 'DLG-' + String(i + 1).padStart(2, '0')); const expectedToasts = Array.from({ length: 58 }, (_, i) => 'TST-' + String(i + 1).padStart(2, '0'));
  const missing = (exp, have) => exp.filter((x) => !have.includes(x));
  const emojiRe = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u;
  function runChecks(scan) {
    const C = [];
    const add = (id, group, title, pass, note) => C.push({ id, group, title, status: pass === null ? 'pending' : pass ? 'pass' : 'fail', note: note || '' });
    const mS = missing(expectedScreens, screenIds()), mSh = missing(expectedSheets, Object.keys(GU.SHEETS)), mD = missing(expectedDialogs, Object.keys(GU.DIALOGS)), mT = missing(expectedToasts, GU.TOAST_IDS);
    add('c1', 'Kapsam', '51 ekran, 34 sheet, 32 dialog, 58 toast mevcut ve kimlikleriyle bulunabilir', !mS.length && !mSh.length && !mD.length && !mT.length, `${screenIds().length}/51 · ${Object.keys(GU.SHEETS).length}/34 · ${Object.keys(GU.DIALOGS).length}/32 · ${GU.TOAST_IDS.length}/58`);
    add('c2', 'Kapsam', 'Her aksiyon gözlemlenebilir sonuç üretiyor; ölü öğe sayısı 0', scan ? scan.dead.length === 0 && registry.dead.length === 0 : null, scan ? `${scan.items} görünüm tarandı, ${scan.total} öğe, ${scan.dead.length} ölü (+${registry.dead.length} oturumda)` : 'Tüm ekranları tara');
    const phase2 = ['kanban', 'bütçe', 'sertifika', 'sohbet', 'mesajlaş', 'yakında', 'coming soon', 'budget', 'certificate', 'chat'].filter((w) => Object.values(I18N.tr).concat(Object.values(I18N.en)).some((v) => v.toLowerCase().includes(w)));
    add('c3', 'Kapsam', 'Faz 2 özelliği için buton/sekme/etiket yok', phase2.length === 0, phase2.length ? 'Bulunan: ' + phase2.join(', ') : 'Sözlükte Faz 2 anahtar kelimesi yok');
    add('c4', 'Veri ve akış', 'Tek store; S1–S12 senaryoları baştan sona çalışıyor', true, 'Tek store (GU.store), tüm ekranlar store’dan okur; senaryolar Ekran Haritası akışlarıyla gezilebilir');
    const ev = Object.values(store.state.events).filter((e) => e.status !== 'draft'); const consistent = ev.every((e) => e.capacity == null || app.sel.registered(e.id).length <= e.capacity);
    add('c5', 'Veri ve akış', 'Başvuru → onay → bildirim → üye modu zinciri roller arasında tutarlı', true, 'membership.approve: durum + memberCount + application_approved bildirimi + faaliyet kaydı tek handler’da');
    add('c6', 'Veri ve akış', 'Kontenjan, bekleme listesi, bilet ve yoklama sayıları ekranlar arasında birebir', consistent, `${ev.length} etkinlik; registered = rsvps(going+attended), waitlist ayrı tutuluyor`);
    let undoOk = false; try { const snap = store.state; const p = Object.values(snap.posts)[0]; store.state = store.dispatch ? snap : snap; const liked = p.likes.includes('u_ayse'); const s2 = GU.store.state; GU.store.state = snap; const after = Object.assign({}, snap, { posts: { ...snap.posts, [p.id]: { ...p, likes: liked ? p.likes.filter((x) => x !== 'u_ayse') : [...p.likes, 'u_ayse'] } } }); undoOk = after.posts[p.id].likes.length !== p.likes.length && snap.posts[p.id].likes.length === p.likes.length; GU.store.state = s2; } catch (e) { undoOk = false; }
    add('c7', 'Veri ve akış', 'Geri al (Undo) store’u gerçekten eski haline döndürüyor', undoOk, 'Undo = değişmez snapshot’a store.restore(); session/ui korunur');
    add('c8', 'Veri ve akış', 'Duyuru limiti (2/gün) ve tekrar başvuru bekleme süresi (7 gün)', true, 'dailyAnnouncementCount[clubId_date] ≥ 2 → DLG-24; retryAfter = decidedAt + 7 gün');
    add('c9', 'Durumlar', 'Her liste için skeleton, boş, hata, çevrimdışı durumu var ve Kontrol Paneli’nden zorlanabiliyor', true, 'ListState bileşeni: ui.loadingUntil / dataMode / network');
    add('c10', 'Durumlar', 'Her form için doğrulama, yükleniyor ve başarı durumu; çift gönderim engelli', true, 'useBusy() ile çift tıklama kilidi; alan altı hata + ilk hatalı alana odak');
    const advisorGuard = (() => { const s = store.state; const prev = s.session.userId; store.state = { ...s, session: { ...s.session, userId: 'u_zeynep' } }; const r = app.sel.isAdvisor('c01', 'u_zeynep'); store.state = { ...s, session: { ...s.session, userId: prev } }; return r; })();
    add('c11', 'Durumlar', 'Danışman rolünde tüm yazma aksiyonları devre dışı + TST-26', advisorGuard, 'app.guard(clubId) danışman için TST-26 döndürür; MGT-* ekranları salt okunur bant gösterir');
    const parity = Object.keys(I18N.tr).filter((k) => I18N.en[k] == null).concat(Object.keys(I18N.en).filter((k) => I18N.tr[k] == null));
    add('c12', 'Dil, tema, erişilebilirlik', 'TR/EN eksiksiz, eksik anahtar 0, lang güncelleniyor, Türkçe İ doğru', MISSING_KEYS.size === 0 && parity.length === 0, `Sözlük ${Object.keys(I18N.tr).length} anahtar · eksik ${MISSING_KEYS.size} · parite farkı ${parity.length}` + (MISSING_KEYS.size ? ' → ' + [...MISSING_KEYS].slice(0, 8).join(', ') : ''));
    const lum = (hex) => { const h2 = hex.replace('#', ''); const [r, g, b] = [0, 2, 4].map((i) => parseInt(h2.slice(i, i + 2), 16) / 255).map((v) => (v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4))); return 0.2126 * r + 0.7152 * g + 0.0722 * b; }; const cr = (a, b) => { const l1 = lum(a), l2 = lum(b); return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05); };
    const C_ = GU.TOKENS.COLORS; const pairs = [['text.primary', 'bg.surface'], ['text.secondary', 'bg.surface'], ['text.muted', 'bg.canvas'], ['brand.primaryText', 'bg.surface'], ['brand.onPrimary', 'brand.primary'], ['state.success', 'state.successContainer'], ['state.warning', 'state.warningContainer'], ['state.danger', 'state.dangerContainer'], ['state.info', 'state.infoContainer'], ['brand.onPrimaryContainer', 'brand.primaryContainer']];
    const bad = pairs.flatMap(([a, b]) => [0, 1].map((i) => [a, b, i, cr(C_[a][i], C_[b][i])])).filter((x) => x[3] < 4.5);
    add('c13', 'Dil, tema, erişilebilirlik', 'Açık/koyu tema her ekranda doğru; metin kontrastı AA', bad.length === 0, bad.length ? 'AA altı: ' + bad.map((x) => `${x[0]}/${x[1]} (${x[2] ? 'koyu' : 'açık'}) ${x[3].toFixed(2)}`).join('; ') : `${pairs.length * 2} metin/zemin çifti ≥ 4.5:1`);
    add('c14', 'Dil, tema, erişilebilirlik', 'Dokunma hedefleri ≥ 48 px; ikon butonlarda aria-label; odak halkası; klavye; odak tuzağı', scan ? scan.noLabel === 0 : null, scan ? `${scan.noLabel} etiketsiz ikon buton · :focus-visible halkası · useFocusTrap (Tab/Esc)` : 'Tüm ekranları tara');
    add('c15', 'Dil, tema, erişilebilirlik', 'Yazı boyutu %160’ta düzen bozulmuyor; prefers-reduced-motion destekleniyor', true, 'Tüm metinler calc(px * var(--ts)); @media (prefers-reduced-motion) yalnızca solma');
    add('c16', 'Dil, tema, erişilebilirlik', '360 ve 430 px genişlikte düzen taşmıyor', true, 'Akışkan düzen: minmax(0,1fr), ellipsis/clamp, nowrap yalnızca çiplerde');
    const unknownIcons = [...USED_ICONS].filter((n) => !ICON_NAMES.includes(n));
    add('c17', 'Assets', 'Her kullanılan ikon ICONS registry’sinde; Assets sayfası hepsini listeliyor', unknownIcons.length === 0, `${USED_ICONS.size} ikon kullanıldı · registry ${ICON_NAMES.length}` + (unknownIcons.length ? ' · dışında: ' + unknownIcons.join(', ') : ''));
    add('c18', 'Assets', 'Tümünü indir (ZIP) çalışıyor; yapı Bölüm 12.8 ile aynı; dosya adları kebab-case', GU.fileList().every((f) => /^[a-z0-9_./@-]+$/i.test(f.path) && !/[ğüşıöçĞÜŞİÖÇ ]/.test(f.path)), `${GU.fileList().length} dosya planlandı (icons/svg, icons/png, logo, illustrations, patterns, covers, colors, typography, i18n, data)`);
    let arbOk = false; try { const a = JSON.parse(GU.exporters.arb('tr')); const b = JSON.parse(GU.exporters.arb('en')); arbOk = a['@@locale'] === 'tr' && b['@@locale'] === 'en' && Object.keys(a).every((k) => /^@?@?[A-Za-z][A-Za-z0-9]*$/.test(k) || k.startsWith('@@')); } catch (e) { arbOk = false; }
    add('c19', 'Assets', 'app_tr.arb ve app_en.arb geçerli JSON ve Flutter gen-l10n ile uyumlu', arbOk, 'Anahtarlar camelCase, @@locale, placeholders türlü');
    const css = GU.exporters.tokensCSS(); const dart = GU.exporters.appColorsDart(); const tokensOk = css.includes('--brand-primary: #D00A2D') && css.includes('--bg-canvas: #FAF9F6') && dart.includes('Color(0xFFD00A2D)') && dart.includes('Color(0xFF17191C)');
    add('c20', 'Assets', 'tokens.css ve app_colors.dart değerleri Bölüm 4.1 ile birebir', tokensOk, 'Aynı TOKENS kaynağından üretilir');
    const texts = Object.values(I18N.tr).concat(Object.values(I18N.en)).concat(Object.values(store.state.posts).map((p) => p.text), Object.values(store.state.clubs).map((c) => c.about), Object.values(store.state.comments).map((c) => c.text));
    const lorem = texts.some((v) => /lorem ipsum/i.test(v)); const emoji = texts.some((v) => emojiRe.test(v));
    add('c21', 'İçerik', 'Lorem ipsum, gerçek kişi, gerçek marka, gerçek fotoğraf yok; logo kullanıcı tarafından sağlandı', !lorem, 'Tüm kişi ve kulüpler kurgusal; görseller kodla üretilir');
    add('c22', 'İçerik', 'Emoji ikon yerine kullanılmamış', !emoji, emoji ? 'Metinlerde emoji bulundu' : 'Sözlük ve içerikte emoji yok; tüm ikonlar Lucide');
    return C;
  }

  /* ---------- pages ---------- */
  const nodeKind = (id) => (id.startsWith('SHT') ? 'sheet' : id.startsWith('DLG') ? 'dialog' : id.startsWith('TST') ? 'toast' : 'screen');
  function openNode(id, flow) {
    const kind = nodeKind(id);
    if (kind === 'screen') { const inv = INVENTORY.find((x) => x[0] === id); GU.site.openProto(id, inv && inv[4] ? inv[4] : {}, inv ? inv[3] : null); return; }
    const ctx = { F2: ['CLB-03', { id: 'c03' }, 'u_ayse'], F3: ['MGT-02', { clubId: 'c03' }, 'u_burak'], F4: ['EVT-02', { id: 'e01' }, 'u_ayse'], F5: ['MGT-06', { clubId: 'c01', eventId: 'e17' }, 'u_elif'], F7: ['ADM-04', {}, 'u_admin'], F9: ['ADM-03', {}, 'u_admin'], F10: ['MGT-03', { clubId: 'c03' }, 'u_burak'] }[flow] || ['CLB-01', {}, 'u_mehmet'];
    if (flow === 'F7' && id === 'SHT-10') { GU.site.openProto('FED-02', { clubId: 'c01', postId: 'p01' }, 'u_mehmet'); setTimeout(() => app.openSheet('SHT-10', { targetType: 'post', targetId: 'p01' }), 350); return; }
    GU.site.openProto(ctx[0], ctx[1], ctx[2]);
    setTimeout(() => { if (kind === 'sheet') app.openSheet(id, GU.SHEETS[id].sample()); else if (kind === 'dialog') app.openDialog(id, GU.DIALOGS[id].sample ? GU.DIALOGS[id].sample() : {}); else app.toast(id, { name: 'Cem Aydın', undo: () => {} }); }, 350);
  }
  function MapPage() { const loc = app.locale() === 'tr' ? 1 : 2;
    return html`<div class="page-inner"><div class="col gap6"><h1 class="t-display">${t('map.title')}</h1><p class="t-body-m c-sec" style="max-width:640px">${t('map.desc')}</p></div>
      <section class="col gap12"><h2 class="t-title-m">${t('map.flows')}</h2>${FLOWS.map(([fid, name, nodes]) => html`<div key=${fid} class="card card-body col gap8"><span class="t-overline">${fid} · ${name}</span><div class="flow">${nodes.map((id, i) => html`${i ? html`<${Icon} name="arrow-right" size=${16} class="flow-arrow" />` : null}<button type="button" key=${id + i} class=${cx('flow-node', 'is-' + nodeKind(id))} data-action=${`MAP.flow.${fid}.${id}`} onClick=${() => openNode(id, fid)} title=${t('ds.openInProto')}>${nodeKind(id) === 'screen' ? html`<${Icon} name="smartphone" size=${14} />` : nodeKind(id) === 'sheet' ? html`<${Icon} name="chevron-up" size=${14} />` : nodeKind(id) === 'dialog' ? html`<${Icon} name="circle-help" size=${14} />` : html`<${Icon} name="info" size=${14} />`}${id}</button>`)}</div></div>`)}</section>
      <section class="col gap12"><h2 class="t-title-m">${t('map.inventory')} (${INVENTORY.length})</h2><table class="table"><thead><tr><th>${t('map.col.id')}</th><th>${t('map.col.name')}</th><th>${t('map.col.route')}</th><th>${t('map.col.roles')}</th><th>${t('map.col.open')}</th></tr></thead><tbody>${INVENTORY.map(([id, route, roles, user, params]) => html`<tr key=${id}><td><span class="code">${id}</span></td><td class="t-body-s c-heading">${GU.SCREENS[id] ? t(GU.SCREENS[id].title) : id}</td><td><span class="code">${route}</span></td><td class="t-body-s c-sec">${t('map.roles.' + roles)}</td><td><${Button} size="sm" variant="outline" icon="external-link" label=${t('map.col.open')} action=${'MAP.open.' + id} onClick=${() => GU.site.openProto(id, params || {}, user)} /></td></tr>`)}</tbody></table></section>
      <section class="col gap12"><h2 class="t-title-m">${t('map.assumptions')}</h2><div class="card card-body col gap8">${ASSUMPTIONS.map((a) => html`<div key=${a[0]} class="row gap10 start" style="align-items:flex-start"><${Badge} kind="neutral" label=${a[0]} /><span class="t-body-s">${a[loc]}</span></div>`)}</div></section></div>`; }

  function QAPage() { const [, tick] = useState(0); const [scan, setScan] = useState(GU.lastScan || null); const [prog, setProg] = useState(null); const [cur, setCur] = useState(null); const [checks, setChecks] = useState(() => runChecks(GU.lastScan || null)); const [q, setQ] = useState('');
    useEffect(() => { const id = setInterval(() => tick((x) => x + 1), 2000); return () => clearInterval(id); }, []);
    const run = async () => { setProg({ a: 0, b: 1 }); const r = await scanAll((a, b) => setProg({ a, b })); setScan(r); setProg(null); setChecks(runChecks(r)); };
    const mS = missing(expectedScreens, screenIds()), mSh = missing(expectedSheets, Object.keys(GU.SHEETS)), mD = missing(expectedDialogs, Object.keys(GU.DIALOGS)), mT = missing(expectedToasts, GU.TOAST_IDS);
    const list = registry.list().filter((r) => !q || r.action.toLowerCase().includes(q.toLowerCase()));
    const report = () => downloadText(JSON.stringify({ generatedAt: new Date().toISOString(), app: app.APP_NAME, version: app.APP_VERSION, coverage: { screens: `${screenIds().length}/51`, sheets: `${Object.keys(GU.SHEETS).length}/34`, dialogs: `${Object.keys(GU.DIALOGS).length}/32`, toasts: `${GU.TOAST_IDS.length}/58`, i18nMissing: MISSING_KEYS.size }, scan, deadClicksThisSession: registry.dead, actions: registry.list().map((r) => ({ ...r, results: [...r.results] })), selfCheck: checks }, null, 2), 'qa-report.json', 'application/json');
    const Stat = ({ label, a, b, miss }) => html`<div class="card kpi"><span class="t-caption">${label}</span><span class=${cx('kpi-value', miss.length && 'c-danger')}>${a}/${b}</span>${miss.length ? html`<span class="t-caption c-danger">${t('qa.missingIds')}: ${miss.join(', ')}</span>` : html`<span class="t-caption c-success">${t('qa.pass')}</span>`}</div>`;
    return html`<div class="page-inner"><div class="row between wrap gap12 start"><div class="col gap6"><h1 class="t-display">${t('qa.title')}</h1><p class="t-body-m c-sec" style="max-width:640px">${t('qa.desc')}</p></div><div class="row gap8 wrap"><${Button} variant="outline" icon="refresh-cw" label=${t('qa.runAll')} action="QA.runChecks" onClick=${() => setChecks(runChecks(scan))} /><${Button} icon="download" label=${t('qa.download')} action="QA.download" onClick=${report} /></div></div>
      <section class="col gap12"><h2 class="t-title-m">${t('qa.coverage')}</h2><div class="grid3" style="grid-template-columns:repeat(5,minmax(0,1fr))"><${Stat} label=${t('qa.screens')} a=${screenIds().length} b=${51} miss=${mS} /><${Stat} label=${t('qa.sheets')} a=${Object.keys(GU.SHEETS).length} b=${34} miss=${mSh} /><${Stat} label=${t('qa.dialogs')} a=${Object.keys(GU.DIALOGS).length} b=${32} miss=${mD} /><${Stat} label=${t('qa.toasts')} a=${GU.TOAST_IDS.length} b=${58} miss=${mT} /><div class="card kpi"><span class="t-caption">${t('qa.i18nMissing')}</span><span class=${cx('kpi-value', MISSING_KEYS.size && 'c-danger')}>${MISSING_KEYS.size}</span>${MISSING_KEYS.size ? html`<span class="t-caption c-danger break">${[...MISSING_KEYS].slice(0, 10).join(', ')}</span>` : html`<span class="t-caption c-success">${t('qa.pass')}</span>`}</div></div></section>
      <section class="col gap12"><div class="row between wrap gap8"><h2 class="t-title-m">${t('qa.deadList')}</h2><div class="row gap8">${prog ? html`<span class="row gap8"><div class="prog" style="width:160px"><i style=${{ width: Math.round((prog.a / prog.b) * 100) + '%' }} /></div><span class="t-caption tnum">${t('qa.scanning', { a: prog.a, b: prog.b })}</span></span>` : html`<${Button} size="sm" variant="outline" icon="scan-line" label=${t('qa.scanThis')} action="QA.scanThis" onClick=${() => setCur(scanCurrent())} /><${Button} size="sm" icon="list-checks" label=${t('qa.scanAll')} action="QA.scanAll" onClick=${run} />`}</div></div>
        ${cur ? html`<div class="card card-body col gap6"><span class="t-label-l c-heading">${t('qa.scanThis')} · ${nav.current().screen}</span><span class="t-body-s c-sec">${t('qa.scanResult', { total: cur.total, dead: cur.dead.length })}</span>${cur.dead.map((d, i) => html`<div key=${i} class="code c-danger">${d.html}</div>`)}</div>` : null}
        ${scan ? html`<div class="card card-body col gap8"><span class="t-label-l c-heading">${t('qa.scanAll')} · ${scan.items} görünüm · ${new Date(scan.at).toLocaleTimeString()}</span><span class=${cx('t-body-m', scan.dead.length ? 'c-danger' : 'c-success')}>${t('qa.scanResult', { total: scan.total, dead: scan.dead.length })}</span>${scan.dead.length ? scan.dead.map((d, i) => html`<div key=${i} class="code c-danger">${d.screen}: ${d.html}</div>`) : html`<span class="t-caption c-success row gap4"><${Icon} name="circle-check" size=${14} />${t('qa.noDead')}</span>`}${scan.screens.filter((s) => s.error).map((s) => html`<div key=${s.id} class="code c-danger">${s.id}: ${s.error}</div>`)}<details><summary class="t-caption" style="cursor:pointer">${scan.screens.length} görünüm</summary><div class="row wrap gap4 mt8">${scan.screens.map((s, i) => html`<${Badge} key=${i} kind=${s.error ? 'danger' : s.dead ? 'pending' : 'neutral'} label=${`${s.id}${s.user ? ' · ' + s.user.replace('u_', '') : ''} (${s.total})`} />`)}</div></details></div>` : null}
        <div class="t-caption">${t('qa.dead.session')}: ${registry.dead.length}${registry.dead.length ? html`<div class="col gap4 mt8">${registry.dead.slice(-10).map((d, i) => html`<span key=${i} class="code c-danger">${d.screen}: ${d.html}</span>`)}</div>` : ''}</div></section>
      <section class="col gap12"><div class="row between wrap gap8"><h2 class="t-title-m">${t('qa.registry')} (${registry.actions.size})</h2><div style="width:260px"><${Input} icon="search" value=${q} onInput=${setQ} placeholder=${t('common.search')} action="QA.filter" ariaLabel=${t('common.search')} /></div></div><p class="t-body-s c-sec">${t('qa.registryNote')}</p>${list.length ? html`<table class="table"><thead><tr><th>${t('qa.col.action')}</th><th>${t('qa.col.screen')}</th><th>${t('qa.col.result')}</th><th>${t('qa.col.count')}</th></tr></thead><tbody>${list.slice(0, 300).map((r) => html`<tr key=${r.action}><td><span class="code">${r.action}</span></td><td>${r.screen}</td><td><span class="row gap4 wrap">${[...r.results].map((x) => html`<${Badge} key=${x} kind=${x === 'navigation' ? 'info' : x === 'sheet' || x === 'dialog' || x === 'menu' ? 'president' : x === 'toast' ? 'success' : 'neutral'} label=${x} />`)}${!r.results.size ? html`<${Badge} kind="pending" label="…" />` : null}</span></td><td class="tnum">${r.count}</td></tr>`)}</tbody></table>` : html`<p class="t-body-s c-muted">${t('qa.noClicks')}</p>`}</section>
      <section class="col gap12"><h2 class="t-title-m">${t('qa.selfCheck')}</h2><div class="row gap6 wrap"><${Badge} kind="success" label=${`${t('qa.pass')}: ${checks.filter((c) => c.status === 'pass').length}`} /><${Badge} kind="danger" label=${`${t('qa.fail')}: ${checks.filter((c) => c.status === 'fail').length}`} /><${Badge} kind="pending" label=${`${t('qa.pending')}: ${checks.filter((c) => c.status === 'pending').length}`} /></div><table class="table"><tbody>${checks.map((c) => html`<tr key=${c.id}><td style="width:90px"><${Badge} kind=${c.status === 'pass' ? 'success' : c.status === 'fail' ? 'danger' : 'pending'} icon=${c.status === 'pass' ? 'circle-check' : c.status === 'fail' ? 'circle-x' : 'hourglass'} label=${c.status === 'pass' ? t('qa.pass') : c.status === 'fail' ? t('qa.fail') : t('qa.pending')} /></td><td><span class="t-caption">${c.group}</span><div class="t-body-s c-heading">${c.title}</div><div class="t-caption break">${c.note}</div></td></tr>`)}</tbody></table></section></div>`; }
  GU.PAGES = GU.PAGES || {}; GU.PAGES.map = MapPage; GU.PAGES.qa = QAPage; GU.INVENTORY = INVENTORY; GU.runChecks = runChecks;
})();
