/* ===== ASSETS_PAGE ===== all visual + code assets in one place, bulk ZIP download (JSZip from cdnjs, lazy) */
(function () {
  const { html, cx, Icon, app, useState, useEffect, useRef, Button, IconButton, Input, Chip, Segmented, Badge, Card, TOKENS, cssVar, tokensCSS, ICON_GROUPS, ICON_GROUP_LABELS, ICON_NAMES, ICONS, ALIASES, ICON_SOURCE, iconSVG, svgToPng, flutterIconName, pascal, coverArtSVG, avatarSVG, logoSVG, appIconSVG, illustrationSVG, ILLUSTRATION_NAMES, patternSVG, PALETTES, PATTERNS, PATTERN_NAMES, downloadBlob, downloadText, copyText, slug, I18N, I18N_META, MISSING_KEYS, DialogFrame } = GU;
  const t = (k, p) => app.t(k, p);
  GU.defineDictionary({
    'assets.title': ['Assets', 'Assets'], 'assets.desc': ['Projede kullanılan tüm görsel ve kod varlıkları. Tek tuşla ZIP olarak indir ya da tek tek al.', 'Every visual and code asset used in the project. Download everything as a ZIP or grab items one by one.'], 'assets.downloadAll': ['Tümünü indir (ZIP)', 'Download all (ZIP)'], 'assets.downloadSection': ['Bu bölümü indir (ZIP)', 'Download this section (ZIP)'], 'assets.progress': ['{a}/{b} dosya', '{a}/{b} files'], 'assets.cancel': ['İptal', 'Cancel'], 'assets.zipDone': ['ZIP hazır: {name}', 'ZIP ready: {name}'], 'assets.zipFail': ['ZIP kütüphanesi yüklenemedi; dosyalar tek tek indiriliyor.', 'ZIP library could not load; downloading files one by one.'], 'assets.fontsFail': ['Yazı tipi dosyaları ZIP’e dahil edilemedi; Google Fonts bağlantısını kullan.', 'Font files could not be included in the ZIP; use the Google Fonts link.'], 'assets.search': ['Varlık ara', 'Search assets'],
    'assets.tab.icons': ['İkonlar', 'Icons'], 'assets.tab.colors': ['Renkler', 'Colours'], 'assets.tab.type': ['Tipografi', 'Typography'], 'assets.tab.logo': ['Amblem', 'Logo'], 'assets.tab.illus': ['İllüstrasyonlar', 'Illustrations'], 'assets.tab.covers': ['Kapaklar ve Desenler', 'Covers & Patterns'], 'assets.tab.data': ['Veri ve Dil', 'Data & Language'], 'assets.tab.flutter': ['Flutter Çıktıları', 'Flutter Output'],
    'assets.icons.size': ['Boyut', 'Size'], 'assets.icons.stroke': ['Çizgi kalınlığı', 'Stroke width'], 'assets.icons.color': ['Renk (önizleme)', 'Colour (preview)'], 'assets.icons.copyName': ['Adı kopyala', 'Copy name'], 'assets.icons.copySvg': ['SVG kopyala', 'Copy SVG'], 'assets.icons.svg': ['SVG indir', 'Download SVG'], 'assets.icons.flutter': ['Flutter kodu kopyala', 'Copy Flutter code'], 'assets.icons.count': ['{count} ikon · tek ICONS registry’si · Lucide (ISC)', '{count} icons · single ICONS registry · Lucide (ISC)'], 'assets.icons.source': ['Kaynak: {src}', 'Source: {src}'], 'assets.icons.aliases': ['Eski adlar (alias)', 'Legacy names (aliases)'], 'assets.copied': ['Kopyalandı', 'Copied'],
    'assets.colors.token': ['Token', 'Token'], 'assets.colors.light': ['Açık', 'Light'], 'assets.colors.dark': ['Koyu', 'Dark'], 'assets.colors.usage': ['Kullanım', 'Usage'], 'assets.colors.contrast': ['Kontrast (beyaz/koyu yüzey)', 'Contrast (on surface)'], 'assets.colors.badges': ['Rol ve durum rozetleri', 'Role & status badges'], 'assets.colors.palettes': ['Kapak paletleri', 'Cover palettes'], 'assets.colors.copyHex': ['Hex', 'Hex'], 'assets.colors.copyCss': ['CSS var', 'CSS var'], 'assets.colors.copyDart': ['Flutter', 'Flutter'],
    'assets.type.sample': ['ĞÜŞİÖÇ ğüşıöç — Gümüşhane Üniversitesi — 0123456789', 'ĞÜŞİÖÇ ğüşıöç — Gümüşhane Üniversitesi — 0123456789'], 'assets.type.scale': ['Tipografi ölçeği', 'Type scale'], 'assets.type.copyCss': ['CSS kopyala', 'Copy CSS'], 'assets.type.copyDart': ['TextStyle kopyala', 'Copy TextStyle'], 'assets.type.openGoogle': ['Google Fonts’ta aç', 'Open on Google Fonts'], 'assets.type.woff2': ['woff2 indir (latin + latin-ext)', 'Download woff2 (latin + latin-ext)'], 'assets.type.latinExt': ['latin-ext zorunlu: ğ, ş, İ, ı', 'latin-ext is required: ğ, ş, İ, ı'],
    'assets.logo.real': ['Resmi logo (kullanıcı tarafından sağlandı)', 'Official logo (provided by the user)'], 'assets.logo.realNote': ['Gerçek üniversite logosu app/assets/gu-logo.png olarak projeye eklendi ve uygulamada kullanılıyor. Kullanım izni üniversiteye aittir.', 'The real university logo was added as app/assets/gu-logo.png and is used in the app. Usage rights belong to the university.'], 'assets.logo.placeholder': ['LogoPlaceholder (yedek amblem)', 'LogoPlaceholder (fallback mark)'], 'assets.logo.placeholderNote': ['Gerçek logo sağlanmadan önce kullanılan kırmızı yuvarlak amblem. Gerekirse yerine resmi logoyu koy.', 'The red round mark used before the real logo arrived. Replace with the official logo where needed.'], 'assets.logo.variants': ['Yatay · Dikey · Yalnızca amblem', 'Horizontal · Vertical · Mark only'], 'assets.logo.appIcon': ['Uygulama ikonu önerisi (1024 × 1024)', 'App icon proposal (1024 × 1024)'], 'assets.logo.masks': ['iOS köşeli · Android dairesel maske', 'iOS rounded · Android circular mask'],
    'assets.illus.note': ['12 illüstrasyon · tek renk + kırmızı vurgu · açık/koyu uyumlu', '12 illustrations · single tone + red accent · light/dark ready'],
    'assets.covers.generator': ['CoverArt üreticisi', 'CoverArt generator'], 'assets.covers.seed': ['Seed', 'Seed'], 'assets.covers.icon': ['İkon', 'Icon'], 'assets.covers.clubs': ['14 kulüp kapağı (gerçek seed’lerle)', '14 club covers (real seeds)'], 'assets.covers.avatar': ['Avatar üreticisi', 'Avatar generator'], 'assets.covers.name': ['Ad', 'Name'], 'assets.covers.patterns': ['Desenler', 'Patterns'], 'assets.covers.templates': ['12 şablon (3 palet × 4 desen)', '12 templates (3 palettes × 4 patterns)'],
    'assets.data.demo': ['demo-data.json', 'demo-data.json'], 'assets.data.demoNote': ['Bölüm 11’in tamamı: kullanıcılar, kulüpler, etkinlikler, gönderiler, bildirimler, başvurular, şikayetler. Tarihler ISO 8601 + göreli gün ofseti.', 'All of section 11: users, clubs, events, posts, notifications, applications, reports. Dates as ISO 8601 + relative day offset.'], 'assets.data.arb': ['Dil dosyaları (ARB)', 'Language files (ARB)'], 'assets.data.arbNote': ['Sözlükten otomatik üretilir: @@locale, ICU çoğul/parametre, her anahtar için @anahtar açıklaması. Anahtarlar Flutter gen-l10n için camelCase’e çevrilir.', 'Generated from the dictionary: @@locale, ICU plurals/params, @key description for each key. Keys are camelCased for Flutter gen-l10n.'], 'assets.data.missing': ['Eksik çeviri', 'Missing translations'], 'assets.data.keys': ['{count} anahtar', '{count} keys'], 'assets.data.key': ['Anahtar', 'Key'], 'assets.data.filter': ['Anahtar veya metin ara', 'Search key or text'], 'assets.data.showing': ['İlk {n} satır gösteriliyor', 'Showing first {n} rows'],
    'assets.flutter.note': ['Tasarım tokenlarından üretilen Dart dosyaları. Değerler Bölüm 4.1 ile birebirdir.', 'Dart files generated from the design tokens. Values match section 4.1 exactly.'], 'assets.flutter.copy': ['Kopyala', 'Copy'], 'assets.flutter.download': ['İndir', 'Download'],
  });

  /* ---------- helpers ---------- */
  const hexToRgb = (hex) => { const h = hex.replace('#', ''); return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)); };
  const lum = (hex) => { const [r, g, b] = hexToRgb(hex).map((v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); }); return 0.2126 * r + 0.7152 * g + 0.0722 * b; };
  const contrast = (a, b) => { if (!/^#/.test(a) || !/^#/.test(b)) return null; const l1 = lum(a), l2 = lum(b); return Math.round(((Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05)) * 100) / 100; };
  const dartColor = (c) => { if (c.startsWith('#')) return `Color(0xFF${c.slice(1).toUpperCase()})`; const m = c.match(/rgba\((\d+),(\d+),(\d+),([\d.]+)\)/); return m ? `Color.fromRGBO(${m[1]}, ${m[2]}, ${m[3]}, ${m[4]})` : `Color(0xFF000000)`; };
  const camel = (k) => k.split(/[.\-_]/).map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('').replace(/[^A-Za-z0-9]/g, '');
  const dartName = (k) => camel(k.replace(/\./g, '_'));

  const exporters = {
    tokensJSON() { const { COLORS, COLOR_USAGE, RADIUS, SHADOWS, MOTION, SPACING } = TOKENS; return JSON.stringify({ colors: Object.fromEntries(Object.entries(COLORS).map(([k, v]) => [k, { light: v[0], dark: v[1], usage: COLOR_USAGE[k] || '' }])), radius: RADIUS, shadows: SHADOWS, motion: MOTION, spacing: SPACING }, null, 2); },
    tokensCSS: () => tokensCSS(),
    appColorsDart() { const { COLORS } = TOKENS; const cls = (name, idx) => `class ${name} {\n  ${name}._();\n${Object.entries(COLORS).map(([k, v]) => `  static const Color ${dartName(k)} = ${dartColor(v[idx])}; // ${TOKENS.COLOR_USAGE[k] || ''}`).join('\n')}\n}`; return `// GENERATED from design tokens — GÜ Kulüpler\nimport 'package:flutter/material.dart';\n\n${cls('AppColors', 0)}\n\n${cls('AppColorsDark', 1)}\n`; },
    appThemeDart() { const scheme = (C, b) => `ColorScheme(\n    brightness: Brightness.${b},\n    primary: ${C}.brandPrimary,\n    onPrimary: ${C}.brandOnPrimary,\n    primaryContainer: ${C}.brandPrimaryContainer,\n    onPrimaryContainer: ${C}.brandOnPrimaryContainer,\n    secondary: ${C}.stateInfo,\n    onSecondary: ${C}.brandOnPrimary,\n    error: ${C}.stateDanger,\n    onError: ${C}.brandOnPrimary,\n    errorContainer: ${C}.stateDangerContainer,\n    surface: ${C}.bgSurface,\n    onSurface: ${C}.textPrimary,\n    surfaceContainerHighest: ${C}.bgSurfaceMuted,\n    outline: ${C}.borderDefault,\n    outlineVariant: ${C}.borderSoft,\n    scrim: ${C}.overlayScrim,\n  )`; return `// GENERATED — GÜ Kulüpler theme\nimport 'package:flutter/material.dart';\nimport 'app_colors.dart';\nimport 'text_theme.dart';\n\nclass AppRadius { static const double sm = 12; static const double md = 16; static const double lg = 20; static const double xl = 28; static const double full = 999; }\nclass AppSpacing { static const List<double> scale = [4, 8, 12, 16, 20, 24, 32, 40, 48]; static const double page = 16; static const double section = 24; static const double card = 16; }\nclass AppMotion { static const Duration fast = Duration(milliseconds: 120); static const Duration base = Duration(milliseconds: 200); static const Duration slow = Duration(milliseconds: 320); static const Curve standard = Cubic(.2, 0, 0, 1); static const Curve emphasized = Cubic(.3, 0, 0, 1); }\n\nThemeData _base(ColorScheme cs, Color canvas) => ThemeData(\n  useMaterial3: true,\n  colorScheme: cs,\n  scaffoldBackgroundColor: canvas,\n  textTheme: appTextTheme(cs.onSurface),\n  cardTheme: CardTheme(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(AppRadius.lg)), elevation: 0),\n  filledButtonTheme: FilledButtonThemeData(style: FilledButton.styleFrom(minimumSize: const Size(48, 48), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(AppRadius.sm)))),\n  inputDecorationTheme: InputDecorationTheme(filled: true, border: OutlineInputBorder(borderRadius: BorderRadius.circular(AppRadius.sm), borderSide: BorderSide.none)),\n  bottomSheetTheme: const BottomSheetThemeData(shape: RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(AppRadius.xl)))),\n  dialogTheme: DialogTheme(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(AppRadius.lg))),\n);\n\nfinal ThemeData lightTheme = _base(const ${scheme('AppColors', 'light')}, AppColors.bgCanvas);\nfinal ThemeData darkTheme = _base(const ${scheme('AppColorsDark', 'dark')}, AppColorsDark.bgCanvas);\n`; },
    typographyJSON: () => JSON.stringify({ fonts: { heading: 'Montserrat', body: 'Inter', weights: { Montserrat: [400, 500, 600, 700], Inter: [400, 500, 600] }, subsets: ['latin', 'latin-ext'] }, scale: TOKENS.TYPE_SCALE, textScales: [1, 1.3, 1.6] }, null, 2),
    textThemeDart() { const map = { display: 'displaySmall', titleL: 'headlineSmall', titleM: 'titleLarge', titleS: 'titleMedium', bodyL: 'bodyLarge', bodyM: 'bodyMedium', bodyS: 'bodySmall', labelL: 'labelLarge', labelM: 'labelMedium', caption: 'labelSmall' }; const style = (s) => `TextStyle(fontFamily: '${s.font}', fontSize: ${s.size}, height: ${(s.line / s.size).toFixed(3)}, fontWeight: FontWeight.w${s.weight}${s.letterSpacing ? `, letterSpacing: ${(s.size * 0.08).toFixed(2)}` : ''}, color: color)`; return `// GENERATED — GÜ Kulüpler text theme (Montserrat headings · Inter body)\nimport 'package:flutter/material.dart';\n\nTextTheme appTextTheme(Color color) => TextTheme(\n${TOKENS.TYPE_SCALE.filter((s) => map[s.id]).map((s) => `  ${map[s.id]}: ${style(s)}, // ${s.name}`).join('\n')}\n);\n\n/// Overline (Montserrat 11/14, +8% tracking, uppercase)\nTextStyle overline(Color color) => ${style(TOKENS.TYPE_SCALE.find((s) => s.id === 'overline'))};\n`; },
    fontsMD: () => `# Fonts\n\n- **Montserrat** (400, 500, 600, 700) — headings, numerals, overline. Licence: SIL Open Font License 1.1.\n- **Inter** (400, 500, 600) — body, labels. Licence: SIL Open Font License 1.1.\n- Subsets: latin + **latin-ext** (required for ğ, ş, İ, ı, ç, ö, ü).\n\n## pubspec.yaml\n\n\`\`\`yaml\nflutter:\n  fonts:\n    - family: Montserrat\n      fonts:\n        - asset: assets/fonts/montserrat-400.woff2\n        - asset: assets/fonts/montserrat-500.woff2\n          weight: 500\n        - asset: assets/fonts/montserrat-600.woff2\n          weight: 600\n        - asset: assets/fonts/montserrat-700.woff2\n          weight: 700\n    - family: Inter\n      fonts:\n        - asset: assets/fonts/inter-400.woff2\n        - asset: assets/fonts/inter-500.woff2\n          weight: 500\n        - asset: assets/fonts/inter-600.woff2\n          weight: 600\n\`\`\`\n\nAlternatively use the \`google_fonts\` package: \`GoogleFonts.montserrat()\`, \`GoogleFonts.inter()\`.\n`,
    l10nYaml: () => `arb-dir: lib/l10n\ntemplate-arb-file: app_tr.arb\noutput-localization-file: app_localizations.dart\nnullable-getter: false\n`,
    arb(loc) { const dict = I18N[loc]; const out = { '@@locale': loc, '@@last_modified': new Date().toISOString() }; Object.keys(dict).sort().forEach((k) => { const v = dict[k]; const name = dartName(k); out[name] = v; const ph = {}; for (const m of v.matchAll(/\{(\w+)(,\s*(plural|select))?/g)) ph[m[1]] = { type: m[3] === 'plural' || m[1] === 'count' || m[1] === 'n' ? 'int' : 'String' }; out['@' + name] = { description: I18N_META[k] || `Key ${k}`, ...(Object.keys(ph).length ? { placeholders: ph } : {}) }; }); return JSON.stringify(out, null, 2); },
    demoData() { const s = app.state; const today = GU.today0(); const walk = (o) => { if (Array.isArray(o)) return o.map(walk); if (o && typeof o === 'object') { const r = {}; for (const [k, v] of Object.entries(o)) { r[k] = walk(v); if (/At$|^retryAfter$|^startsAt$|^endsAt$/.test(k) && typeof v === 'number') { r[k] = new Date(v).toISOString(); r[k + '_rel_days'] = Math.round((v - today) / GU.DAY * 100) / 100; } } return r; } return o; }; const { users, clubs, memberships, posts, comments, events, rsvps, notifications, reports, activity, settings, saved, dailyAnnouncementCount } = s; return JSON.stringify({ meta: { app: app.APP_NAME, version: app.APP_VERSION, generatedAt: new Date().toISOString(), today: new Date(today).toISOString(), note: 'All data is fictional. *_rel_days = days relative to today.' }, categories: GU.CATEGORIES, interests: GU.INTERESTS, departments: GU.DEPARTMENTS, places: GU.PLACES, ...walk({ users, clubs, memberships, posts, comments, events, rsvps, notifications, reports, activity, settings, saved, dailyAnnouncementCount }) }, null, 2); },
    readme: (fontsOk) => `# GÜ Kulüpler — Assets\n\nGenerated ${new Date().toISOString()} from the design prototype. All demo data is fictional.\n\n## Contents\n- icons/svg, icons/png — ${ICON_NAMES.length} Lucide icons (ISC licence), stroke 1.75, 24×24 viewBox\n- logo/ — official university logo (gu-logo.png, provided by the client) + LogoPlaceholder SVG/PNG fallback\n- illustrations/ — 12 single-tone SVG illustrations\n- patterns/, covers/ — CoverArt templates + 14 club covers\n- colors/ — tokens.json, tokens.css, app_colors.dart, app_theme.dart\n- typography/ — typography.json, text_theme.dart, FONTS.md${fontsOk ? ', fonts/*.woff2' : ' (fonts could not be fetched — use Google Fonts)'}\n- i18n/ — app_tr.arb, app_en.arb (Flutter gen-l10n compatible; keys camelCased)\n- data/ — demo-data.json\n\n## Flutter\n1. Copy colors/*.dart and typography/text_theme.dart into lib/theme/.\n2. Copy i18n/*.arb into lib/l10n/ and add l10n.yaml (see typography/FONTS.md for fonts).\n3. Icons: use lucide_icons_flutter or flutter_svg with icons/svg.\n\n## Licences\nLucide — ISC · Montserrat, Inter — SIL OFL 1.1 · Logo — © Gümüşhane Üniversitesi\n`,
  };
  GU.exporters = exporters; GU.exportDemoData = exporters.demoData;

  /* ---------- file list + zip ---------- */
  const ICON_INK = '#1D293D';
  function fileList(section) {
    const all = !section; const files = [];
    if (all) files.push({ path: 'README.md', content: () => exporters.readme(true) });
    if (all || section === 'icons') { ICON_NAMES.forEach((n) => { files.push({ path: `icons/svg/${n}.svg`, content: () => iconSVG(n, { size: 24, color: ICON_INK }) }); [48, 96, 192].forEach((s) => files.push({ path: `icons/png/${n}@${s}.png`, content: () => svgToPng(iconSVG(n, { size: s, color: ICON_INK }), s) })); }); }
    if (all || section === 'logo') { files.push({ path: 'logo/gu-logo.png', content: () => fetch(GU.LOGO_SRC).then((r) => r.blob()) }); ['emblem', 'horizontal', 'vertical'].forEach((v) => { files.push({ path: `logo/placeholder-${v}.svg`, content: () => logoSVG({ size: 128, variant: v }) }); files.push({ path: `logo/placeholder-${v}-dark.svg`, content: () => logoSVG({ size: 128, variant: v, dark: true }) }); }); [64, 128, 256, 512].forEach((s) => files.push({ path: `logo/placeholder-emblem@${s}.png`, content: () => svgToPng(logoSVG({ size: s }), s) })); files.push({ path: 'logo/app-icon-1024.svg', content: () => appIconSVG(1024) }); files.push({ path: 'logo/app-icon-1024.png', content: () => svgToPng(appIconSVG(1024), 1024) }); }
    if (all || section === 'illus') ILLUSTRATION_NAMES.forEach((n) => files.push({ path: `illustrations/${n}.svg`, content: () => illustrationSVG(n, { size: 160, base: '#62748E' }) }));
    if (all || section === 'covers') { PATTERNS.forEach((p) => files.push({ path: `patterns/${p}.svg`, content: () => patternSVG(p) })); Object.keys(PALETTES).forEach((pal) => PATTERNS.forEach((p) => files.push({ path: `covers/template-${pal}-${p}.svg`, content: () => coverArtSVG('template', 'sparkles', pal, p) }))); Object.values(app.state.clubs).forEach((c) => files.push({ path: `covers/${slug(c.name)}.svg`, content: () => coverArtSVG(c.coverSeed, c.iconName, c.palette, c.pattern) })); }
    if (all || section === 'colors') { files.push({ path: 'colors/tokens.json', content: exporters.tokensJSON }, { path: 'colors/tokens.css', content: exporters.tokensCSS }, { path: 'colors/app_colors.dart', content: exporters.appColorsDart }, { path: 'colors/app_theme.dart', content: exporters.appThemeDart }); }
    if (all || section === 'type') { files.push({ path: 'typography/typography.json', content: exporters.typographyJSON }, { path: 'typography/text_theme.dart', content: exporters.textThemeDart }, { path: 'typography/FONTS.md', content: exporters.fontsMD }); files.push({ path: '__fonts__', content: null }); }
    if (all || section === 'data') { files.push({ path: 'i18n/app_tr.arb', content: () => exporters.arb('tr') }, { path: 'i18n/app_en.arb', content: () => exporters.arb('en') }, { path: 'data/demo-data.json', content: exporters.demoData }); }
    if (all || section === 'flutter') { files.push({ path: 'flutter/app_colors.dart', content: exporters.appColorsDart }, { path: 'flutter/app_theme.dart', content: exporters.appThemeDart }, { path: 'flutter/text_theme.dart', content: exporters.textThemeDart }, { path: 'flutter/l10n.yaml', content: exporters.l10nYaml }, { path: 'flutter/FONTS.md', content: exporters.fontsMD }); }
    return files;
  }
  async function fetchFonts() {
    const css = await (await fetch('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Inter:wght@400;500;600&display=swap')).text();
    const out = []; const re = /\/\*\s*(latin(?:-ext)?)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g; let m;
    while ((m = re.exec(css))) { const block = m[2]; const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1]; const w = (block.match(/font-weight:\s*(\d+)/) || [])[1]; const url = (block.match(/url\(([^)]+)\)/) || [])[1]; if (fam && url) out.push({ path: `typography/fonts/${slug(fam)}-${w}-${m[1]}.woff2`, url }); }
    const blobs = []; for (const f of out) { try { blobs.push({ path: f.path, blob: await (await fetch(f.url)).blob() }); } catch (e) { } }
    if (!blobs.length) throw new Error('fonts');
    return blobs;
  }
  function loadJSZip() { if (window.JSZip) return Promise.resolve(window.JSZip); return new Promise((res, rej) => { const s = document.createElement('script'); s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js'; s.onload = () => res(window.JSZip); s.onerror = () => rej(new Error('jszip')); document.head.appendChild(s); }); }
  async function buildZip(section, onProgress, cancelRef) {
    const files = fileList(section).filter((f) => f.path !== '__fonts__'); const wantFonts = !section || section === 'type'; let JSZip = null; let fontsOk = false;
    try { JSZip = await loadJSZip(); } catch (e) { JSZip = null; }
    const total = files.length + (wantFonts ? 1 : 0); let done = 0; const results = [];
    for (const f of files) { if (cancelRef.current) return null; try { const c = await f.content(); results.push({ path: f.path, data: c }); } catch (e) { console.warn('asset failed', f.path, e); } done++; onProgress(done, total); }
    if (wantFonts) { try { const fonts = await fetchFonts(); fonts.forEach((x) => results.push({ path: x.path, data: x.blob })); fontsOk = true; } catch (e) { fontsOk = false; } done++; onProgress(done, total); }
    if (!section) { const i = results.findIndex((r) => r.path === 'README.md'); if (i >= 0) results[i].data = exporters.readme(fontsOk); }
    if (!JSZip) { results.forEach((r, k) => setTimeout(() => (typeof r.data === 'string' ? downloadText(r.data, r.path.split('/').pop()) : downloadBlob(r.data, r.path.split('/').pop())), k * 150)); return { fallback: true, fontsOk, count: results.length }; }
    const zip = new JSZip(); results.forEach((r) => zip.file(r.path, r.data)); const blob = await zip.generateAsync({ type: 'blob' }); const name = section ? `gu-kulupler-${section}.zip` : 'gu-kulupler-assets.zip'; downloadBlob(blob, name); return { name, fontsOk, count: results.length };
  }
  GU.buildZip = buildZip; GU.fileList = fileList;

  /* ---------- page ---------- */
  const PageToast = ({ msg }) => (msg ? html`<div style="position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:2000" class="gu-root" data-theme=${app.theme()}><div class="toast" style=${{ '--toast-color': 'var(--state-success)' }} role="status"><${Icon} name="circle-check" size=${18} class="toast-icon" /><span class="toast-text">${msg}</span></div></div>` : null);
  function useFlash() { const [msg, setMsg] = useState(''); const flash = (m) => { setMsg(m); setTimeout(() => setMsg(''), 2500); }; return [msg, flash]; }
  function ZipButton({ section, flash, full }) { const [prog, setProg] = useState(null); const cancel = useRef(false);
    const run = async () => { cancel.current = false; setProg({ a: 0, b: 1 }); const res = await buildZip(section, (a, b) => setProg({ a, b }), cancel); setProg(null); if (!res) return; if (res.fallback) flash(t('assets.zipFail')); else { flash(t('assets.zipDone', { name: res.name })); if (!res.fontsOk && (!section || section === 'type')) setTimeout(() => flash(t('assets.fontsFail')), 2600); } };
    if (prog) return html`<div class="row gap8" style="min-width:260px"><div class="prog"><i style=${{ width: Math.round((prog.a / prog.b) * 100) + '%' }} /></div><span class="t-caption tnum">${t('assets.progress', { a: prog.a, b: prog.b })}</span><${Button} size="sm" variant="text" label=${t('assets.cancel')} action="ASSETS.zip.cancel" onClick=${() => { cancel.current = true; }} /></div>`;
    return html`<${Button} variant=${section ? 'outline' : 'primary'} size=${section ? 'sm' : 'md'} icon="download" label=${section ? t('assets.downloadSection') : t('assets.downloadAll')} action=${section ? 'ASSETS.zip.' + section : 'ASSETS.zip.all'} onClick=${run} full=${full} />`;
  }
  function Tab({ id, cur, set, label }) { return html`<button type="button" role="tab" aria-selected=${cur === id ? 'true' : 'false'} data-action=${'ASSETS.tab.' + id} onClick=${() => set(id)}>${label}</button>`; }

  function IconsTab({ q, flash }) { const [size, setSize] = useState(32); const [stroke, setStroke] = useState(1.75); const [color, setColor] = useState(''); const [group, setGroup] = useState('all');
    const names = ICON_NAMES.filter((n) => (group === 'all' || (ICON_GROUPS[group] || []).includes(n)) && (!q || n.includes(q.toLowerCase())));
    const ink = color || 'var(--text-heading)';
    return html`<div class="col gap16"><p class="t-body-s c-sec">${t('assets.icons.count', { count: ICON_NAMES.length })} · ${t('assets.icons.source', { src: ICON_SOURCE.lib === 'lucide' ? 'lucide@0.468.0 (unpkg/jsdelivr)' : 'fallback' })}</p>
      <div class="row wrap gap16"><label class="col gap4 t-caption">${t('assets.icons.size')}: ${size}px<input type="range" min="16" max="48" value=${size} onInput=${(e) => setSize(+e.target.value)} data-action="ASSETS.icons.size" aria-label=${t('assets.icons.size')} /></label><label class="col gap4 t-caption">${t('assets.icons.stroke')}: ${stroke}<input type="range" min="1" max="2.5" step="0.25" value=${stroke} onInput=${(e) => setStroke(+e.target.value)} data-action="ASSETS.icons.stroke" aria-label=${t('assets.icons.stroke')} /></label><label class="col gap4 t-caption">${t('assets.icons.color')}<input type="color" value=${color || '#1d293d'} onInput=${(e) => setColor(e.target.value)} data-action="ASSETS.icons.color" aria-label=${t('assets.icons.color')} style="width:48px;height:32px;border:0;background:none" /></label></div>
      <div class="row wrap gap8"><${Chip} label=${t('common.all')} selected=${group === 'all'} action="ASSETS.icons.group.all" onClick=${() => setGroup('all')} />${Object.keys(ICON_GROUPS).filter((g) => ICON_GROUPS[g].length).map((g) => html`<${Chip} key=${g} label=${`${ICON_GROUP_LABELS[g]} (${ICON_GROUPS[g].length})`} selected=${group === g} action=${'ASSETS.icons.group.' + g} onClick=${() => setGroup(g)} />`)}</div>
      <div class="asset-grid">${names.map((n) => html`<div class="asset-card" key=${n}><div class="asset-prev" style=${{ color: ink }}><${Icon} name=${n} size=${size} stroke=${stroke} /></div><span class="asset-name">${n}</span><span class="t-caption">${ALIASES && Object.entries(ALIASES).filter(([, v]) => v === n).map(([a]) => a).join(', ')}</span><div class="asset-actions">
        <button type="button" class="btn btn-outline" data-action=${'ASSETS.icon.copyName.' + n} onClick=${() => { copyText(n); flash(t('assets.copied')); }} title=${t('assets.icons.copyName')}>${t('assets.icons.copyName')}</button>
        <button type="button" class="btn btn-outline" data-action=${'ASSETS.icon.copySvg.' + n} onClick=${() => { copyText(iconSVG(n, { size: 24, color: ICON_INK })); flash(t('assets.copied')); }}>SVG</button>
        <button type="button" class="btn btn-outline" data-action=${'ASSETS.icon.svg.' + n} onClick=${() => downloadText(iconSVG(n, { size: 24, color: ICON_INK }), n + '.svg', 'image/svg+xml')}>↓ SVG</button>
        ${[48, 96, 192].map((s) => html`<button type="button" key=${s} class="btn btn-outline" data-action=${`ASSETS.icon.png.${n}.${s}`} onClick=${async () => downloadBlob(await svgToPng(iconSVG(n, { size: s, color: ICON_INK }), s), `${n}@${s}.png`)}>PNG ${s}</button>`)}
        <button type="button" class="btn btn-outline" data-action=${'ASSETS.icon.flutter.' + n} onClick=${() => { copyText(`Icon(${flutterIconName(n)}, size: 24, strokeWidth: 1.75) // ${flutterIconName(n)}`); flash(t('assets.copied')); }}>Flutter</button></div></div>`)}</div></div>`; }

  function ColorsTab({ flash }) { const { COLORS, COLOR_USAGE } = TOKENS; const surfaceL = COLORS['bg.surface'][0], surfaceD = COLORS['bg.surface'][1];
    const copy = (txt) => { copyText(txt); flash(t('assets.copied')); };
    return html`<div class="col gap24"><table class="table"><thead><tr><th>${t('assets.colors.token')}</th><th>${t('assets.colors.light')}</th><th>${t('assets.colors.dark')}</th><th>${t('assets.colors.usage')}</th><th>${t('assets.colors.contrast')}</th><th></th></tr></thead><tbody>${Object.entries(COLORS).map(([k, [l, d]]) => { const isText = /^(text\.|brand\.primaryText|state\.(success|warning|danger|info)$|brand\.onPrimaryContainer)/.test(k); const cl = isText ? contrast(l, surfaceL) : null; const cd = isText ? contrast(d, surfaceD) : null; const badge = (c) => (c == null ? null : html`<${Badge} kind=${c >= 7 ? 'success' : c >= 4.5 ? 'success' : c >= 3 ? 'pending' : 'danger'} label=${`${c}:1 ${c >= 7 ? 'AAA' : c >= 4.5 ? 'AA' : c >= 3 ? 'AA-L' : '✕'}`} />`);
        return html`<tr key=${k}><td><span class="code">${k}</span></td><td><span class="row gap8"><span class="swatch" style=${{ width: '40px', height: '28px', background: l }} /><span class="code">${l}</span></span></td><td><span class="row gap8"><span class="swatch" style=${{ width: '40px', height: '28px', background: d }} /><span class="code">${d}</span></span></td><td class="t-body-s c-sec">${COLOR_USAGE[k]}</td><td><span class="row gap4 wrap">${badge(cl)}${badge(cd)}</span></td><td><span class="row gap4"><button type="button" class="btn btn-outline btn-sm" data-action=${'ASSETS.color.hex.' + k} onClick=${() => copy(l)}>${t('assets.colors.copyHex')}</button><button type="button" class="btn btn-outline btn-sm" data-action=${'ASSETS.color.css.' + k} onClick=${() => copy(`var(${cssVar(k)})`)}>${t('assets.colors.copyCss')}</button><button type="button" class="btn btn-outline btn-sm" data-action=${'ASSETS.color.dart.' + k} onClick=${() => copy(dartColor(l))}>${t('assets.colors.copyDart')}</button></span></td></tr>`; })}</tbody></table>
      <div class="col gap8"><h3 class="t-title-s">${t('assets.colors.badges')}</h3><div class="row wrap gap8">${['president', 'board', 'advisor', 'member', 'superadmin'].map((r) => html`<${GU.RoleBadge} key=${r} role=${r} />`)}${['pending', 'approved', 'rejected', 'full'].map((s) => html`<${GU.StatusBadge} key=${s} status=${s} />`)}</div></div>
      <div class="col gap8"><h3 class="t-title-s">${t('assets.colors.palettes')}</h3><div class="grid3">${Object.values(PALETTES).map((p) => html`<div key=${p.id} class="col gap6"><div style=${{ height: '64px', borderRadius: '12px', background: `linear-gradient(120deg, ${p.stops.join(', ')})` }} /><span class="t-label-m c-heading">${p.name[app.locale() === 'tr' ? 0 : 1]}</span><span class="code">${p.stops.join(' · ')}</span></div>`)}</div></div>
      <div class="row wrap gap8">${[['tokens.json', exporters.tokensJSON, 'application/json'], ['tokens.css', exporters.tokensCSS, 'text/css'], ['app_colors.dart', exporters.appColorsDart, 'text/plain'], ['app_theme.dart', exporters.appThemeDart, 'text/plain']].map(([n, fn, ty]) => html`<${Button} key=${n} size="sm" variant="outline" icon="download" label=${n} action=${'ASSETS.colors.file.' + n} onClick=${() => downloadText(fn(), n, ty)} />`)}</div></div>`; }

  function TypeTab({ flash, openLink }) { const sample = t('assets.type.sample'); const copy = (txt) => { copyText(txt); flash(t('assets.copied')); };
    const cssFor = (s) => `font: ${s.weight} ${s.size}px/${s.line}px ${s.font}, sans-serif;${s.letterSpacing ? ` letter-spacing: ${s.letterSpacing}; text-transform: uppercase;` : ''}`; const dartFor = (s) => `TextStyle(fontFamily: '${s.font}', fontSize: ${s.size}, height: ${(s.line / s.size).toFixed(3)}, fontWeight: FontWeight.w${s.weight}${s.letterSpacing ? `, letterSpacing: ${(s.size * 0.08).toFixed(2)}` : ''})`;
    return html`<div class="col gap24">${[['Montserrat', [400, 500, 600, 700]], ['Inter', [400, 500, 600]]].map(([fam, ws]) => html`<div key=${fam} class="col gap8"><div class="row between wrap gap8"><h3 class="t-title-s">${fam}</h3><span class="row gap8"><${Button} size="sm" variant="outline" icon="external-link" label=${t('assets.type.openGoogle')} action=${'ASSETS.type.google.' + fam} onClick=${() => openLink('https://fonts.google.com/specimen/' + fam)} /><${ZipButton} section="type" flash=${flash} /></span></div>${ws.map((w) => html`<div key=${w} class="row gap12 start"><span class="t-caption tnum" style="width:40px">${w}</span><span style=${{ fontFamily: fam, fontWeight: w, fontSize: '20px', lineHeight: 1.4 }}>${sample}</span></div>`)}</div>`)}
      <p class="t-caption row gap6"><${Icon} name="info" size=${14} />${t('assets.type.latinExt')}</p>
      <div class="col gap8"><h3 class="t-title-s">${t('assets.type.scale')}</h3><table class="table"><thead><tr><th>Stil</th><th>Font</th><th>px / lh</th><th>W</th><th>TR / EN</th><th></th></tr></thead><tbody>${TOKENS.TYPE_SCALE.map((s) => html`<tr key=${s.id}><td class="t-label-m">${s.name}</td><td>${s.font}</td><td class="tnum">${s.size} / ${s.line}</td><td>${s.weight}</td><td><div style=${{ font: `${s.weight} ${s.size}px/${s.line}px ${s.font}, sans-serif`, letterSpacing: s.letterSpacing || 'normal', textTransform: s.uppercase ? 'uppercase' : 'none' }}>Kampüsteki tüm kulüpler</div><div style=${{ font: `${s.weight} ${s.size}px/${s.line}px ${s.font}, sans-serif`, letterSpacing: s.letterSpacing || 'normal', textTransform: s.uppercase ? 'uppercase' : 'none', color: 'var(--text-muted)' }}>Every club on campus</div></td><td><span class="row gap4"><button type="button" class="btn btn-outline btn-sm" data-action=${'ASSETS.type.css.' + s.id} onClick=${() => copy(cssFor(s))}>CSS</button><button type="button" class="btn btn-outline btn-sm" data-action=${'ASSETS.type.dart.' + s.id} onClick=${() => copy(dartFor(s))}>TextStyle</button></span></td></tr>`)}</tbody></table></div>
      <div class="row wrap gap8">${[['typography.json', exporters.typographyJSON, 'application/json'], ['text_theme.dart', exporters.textThemeDart, 'text/plain'], ['FONTS.md', exporters.fontsMD, 'text/markdown']].map(([n, fn, ty]) => html`<${Button} key=${n} size="sm" variant="outline" icon="download" label=${n} action=${'ASSETS.type.file.' + n} onClick=${() => downloadText(fn(), n, ty)} />`)}</div></div>`; }

  function LogoTab({ flash }) { const dark = app.theme() === 'dark';
    return html`<div class="col gap24"><div class="col gap8"><h3 class="t-title-s">${t('assets.logo.real')}</h3><p class="t-body-s c-sec">${t('assets.logo.realNote')}</p><div class="ds-pair"><div class="ds-pane" data-theme="light" style="align-items:center"><${GU.Logo} size=${120} /><${GU.Logo} size=${40} variant="horizontal" /></div><div class="ds-pane" data-theme="dark" style="align-items:center"><${GU.Logo} size=${120} /><${GU.Logo} size=${40} variant="horizontal" /></div></div><div><${Button} size="sm" variant="outline" icon="download" label="gu-logo.png" action="ASSETS.logo.real" onClick=${async () => downloadBlob(await (await fetch(GU.LOGO_SRC)).blob(), 'gu-logo.png')} /></div></div>
      <div class="col gap8"><h3 class="t-title-s">${t('assets.logo.placeholder')}</h3><p class="t-body-s c-sec">${t('assets.logo.placeholderNote')} ${t('assets.logo.variants')}</p><div class="ds-pair">${[false, true].map((dk) => html`<div key=${dk} class="ds-pane" data-theme=${dk ? 'dark' : 'light'} style="align-items:center"><span dangerouslySetInnerHTML=${{ __html: logoSVG({ size: 56, variant: 'horizontal', dark: dk }) }} /><span dangerouslySetInnerHTML=${{ __html: logoSVG({ size: 56, variant: 'vertical', dark: dk }) }} /><span class="row gap12" style="align-items:flex-end">${[16, 32, 64, 128].map((s) => html`<span key=${s} dangerouslySetInnerHTML=${{ __html: logoSVG({ size: s }) }} />`)}</span></div>`)}</div><div class="row wrap gap8">${['emblem', 'horizontal', 'vertical'].map((v) => html`<${Button} key=${v} size="sm" variant="outline" icon="download" label=${`${v}.svg`} action=${'ASSETS.logo.svg.' + v} onClick=${() => downloadText(logoSVG({ size: 256, variant: v, dark }), `placeholder-${v}.svg`, 'image/svg+xml')} />`)}${[64, 128, 256, 512].map((s) => html`<${Button} key=${s} size="sm" variant="outline" icon="download" label=${`PNG ${s}`} action=${'ASSETS.logo.png.' + s} onClick=${async () => downloadBlob(await svgToPng(logoSVG({ size: s }), s), `placeholder-emblem@${s}.png`)} />`)}</div></div>
      <div class="col gap8"><h3 class="t-title-s">${t('assets.logo.appIcon')}</h3><p class="t-body-s c-sec">${t('assets.logo.masks')}</p><div class="row gap16 wrap"><span style="width:96px;height:96px;border-radius:22px;overflow:hidden;display:inline-block" dangerouslySetInnerHTML=${{ __html: appIconSVG(96) }} /><span style="width:96px;height:96px;border-radius:50%;overflow:hidden;display:inline-block" dangerouslySetInnerHTML=${{ __html: appIconSVG(96) }} /><img src=${GU.LOGO_SRC} alt="" width="96" height="96" style="width:96px;height:96px;border-radius:22px;background:#fff;object-fit:cover" /><${Button} size="sm" variant="outline" icon="download" label="app-icon-1024.png" action="ASSETS.logo.appIcon" onClick=${async () => downloadBlob(await svgToPng(appIconSVG(1024), 1024), 'app-icon-1024.png')} /></div></div></div>`; }

  function IllusTab() { return html`<div class="col gap16"><p class="t-body-s c-sec">${t('assets.illus.note')}</p><div class="asset-grid" style="grid-template-columns:repeat(auto-fill,minmax(220px,1fr))">${ILLUSTRATION_NAMES.map((n) => html`<div key=${n} class="asset-card"><div class="row gap8" style="align-items:flex-end;color:var(--text-disabled)">${[48, 80, 120].map((s) => html`<span key=${s} dangerouslySetInnerHTML=${{ __html: illustrationSVG(n, { size: s }) }} />`)}</div><span class="asset-name">${n}</span><div class="asset-actions"><button type="button" class="btn btn-outline" data-action=${'ASSETS.illus.svg.' + n} onClick=${() => downloadText(illustrationSVG(n, { size: 160, base: '#62748E' }), n + '.svg', 'image/svg+xml')}>↓ SVG</button></div></div>`)}</div></div>`; }

  function CoversTab() { const [seed, setSeed] = useState('club-c03'); const [pal, setPal] = useState('bordeaux'); const [pat, setPat] = useState('mountain'); const [icon, setIcon] = useState('mountain'); const [name, setName] = useState('Ayşe Demir'); const loc = app.locale() === 'tr' ? 0 : 1;
    return html`<div class="col gap24"><div class="col gap12"><h3 class="t-title-s">${t('assets.covers.generator')}</h3><div class="row wrap gap12 start"><div style="width:220px"><${Input} label=${t('assets.covers.seed')} value=${seed} onInput=${setSeed} action="ASSETS.covers.seed" /></div><div style="width:200px"><${Input} label=${t('assets.covers.icon')} value=${icon} onInput=${setIcon} action="ASSETS.covers.icon" /></div><div class="col gap6"><span class="field-label">Palet</span><div class="row gap6">${Object.values(PALETTES).map((p) => html`<${Chip} key=${p.id} label=${p.name[loc]} selected=${pal === p.id} action=${'ASSETS.covers.palette.' + p.id} onClick=${() => setPal(p.id)} />`)}</div></div><div class="col gap6"><span class="field-label">Desen</span><div class="row gap6">${PATTERNS.map((p) => html`<${Chip} key=${p} label=${PATTERN_NAMES[p][loc]} selected=${pat === p} action=${'ASSETS.covers.pattern.' + p} onClick=${() => setPat(p)} />`)}</div></div></div><div class="cover r16-9" style="max-width:520px;border-radius:16px"><div style="position:absolute;inset:0" dangerouslySetInnerHTML=${{ __html: coverArtSVG(seed, icon, pal, pat) }} /></div><div><${Button} size="sm" variant="outline" icon="download" label="SVG" action="ASSETS.covers.download" onClick=${() => downloadText(coverArtSVG(seed, icon, pal, pat), `cover-${slug(seed)}.svg`, 'image/svg+xml')} /></div></div>
      <div class="col gap8"><h3 class="t-title-s">${t('assets.covers.templates')}</h3><div class="asset-grid">${Object.keys(PALETTES).flatMap((p) => PATTERNS.map((pt) => html`<div key=${p + pt} class="asset-card"><div class="cover r16-9" style="width:100%;border-radius:10px"><div style="position:absolute;inset:0" dangerouslySetInnerHTML=${{ __html: coverArtSVG('template', 'sparkles', p, pt) }} /></div><span class="asset-name">${p} · ${pt}</span><div class="asset-actions"><button type="button" class="btn btn-outline" data-action=${`ASSETS.covers.template.${p}.${pt}`} onClick=${() => downloadText(coverArtSVG('template', 'sparkles', p, pt), `template-${p}-${pt}.svg`, 'image/svg+xml')}>↓ SVG</button></div></div>`))}</div></div>
      <div class="col gap8"><h3 class="t-title-s">${t('assets.covers.clubs')}</h3><div class="asset-grid">${Object.values(app.state.clubs).map((c) => html`<div key=${c.id} class="asset-card"><div class="cover r16-9" style="width:100%;border-radius:10px"><div style="position:absolute;inset:0" dangerouslySetInnerHTML=${{ __html: coverArtSVG(c.coverSeed, c.iconName, c.palette, c.pattern) }} /></div><span class="asset-name">${c.name}</span><span class="t-caption">${c.coverSeed}</span><div class="asset-actions"><button type="button" class="btn btn-outline" data-action=${'ASSETS.covers.club.' + c.id} onClick=${() => downloadText(coverArtSVG(c.coverSeed, c.iconName, c.palette, c.pattern), slug(c.name) + '.svg', 'image/svg+xml')}>↓ SVG</button></div></div>`)}</div></div>
      <div class="col gap8"><h3 class="t-title-s">${t('assets.covers.avatar')}</h3><div class="row gap12 wrap" style="align-items:flex-end"><div style="width:220px"><${Input} label=${t('assets.covers.name')} value=${name} onInput=${setName} action="ASSETS.covers.avatarName" /></div>${[24, 32, 40, 56, 96].map((s) => html`<${GU.Avatar} key=${s} name=${name} seed=${name} size=${s} />`)}<${Button} size="sm" variant="outline" icon="download" label="SVG" action="ASSETS.covers.avatarSvg" onClick=${() => downloadText(avatarSVG(name, name, 96), `avatar-${slug(name)}.svg`, 'image/svg+xml')} /></div></div>
      <div class="col gap8"><h3 class="t-title-s">${t('assets.covers.patterns')}</h3><div class="grid2" style="grid-template-columns:repeat(4,1fr)">${PATTERNS.map((p) => html`<div key=${p} class="asset-card"><div class="cover r16-9" style="width:100%;border-radius:10px;color:var(--text-heading)"><div style="position:absolute;inset:0" dangerouslySetInnerHTML=${{ __html: patternSVG(p) }} /></div><span class="asset-name">${PATTERN_NAMES[p][loc]}</span><div class="asset-actions"><button type="button" class="btn btn-outline" data-action=${'ASSETS.covers.patternSvg.' + p} onClick=${() => downloadText(patternSVG(p), p + '.svg', 'image/svg+xml')}>↓ SVG</button></div></div>`)}</div></div></div>`; }

  function DataTab({ q }) { const keys = Object.keys(I18N.tr).sort(); const missing = keys.filter((k) => !I18N.en[k]).concat(Object.keys(I18N.en).filter((k) => !I18N.tr[k])).concat([...MISSING_KEYS]); const rows = keys.filter((k) => !q || (k + ' ' + I18N.tr[k] + ' ' + I18N.en[k]).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))).slice(0, 150);
    const s = app.state; const counts = { users: Object.keys(s.users).length, clubs: Object.keys(s.clubs).length, events: Object.keys(s.events).length, posts: Object.keys(s.posts).length, comments: Object.keys(s.comments).length, memberships: Object.keys(s.memberships).length, rsvps: Object.keys(s.rsvps).length, notifications: Object.keys(s.notifications).length, reports: Object.keys(s.reports).length, activity: s.activity.length };
    return html`<div class="col gap24"><div class="col gap8"><h3 class="t-title-s">${t('assets.data.demo')}</h3><p class="t-body-s c-sec">${t('assets.data.demoNote')}</p><div class="row wrap gap6">${Object.entries(counts).map(([k, v]) => html`<${Badge} key=${k} kind="neutral" label=${`${k}: ${v}`} />`)}</div><div><${Button} size="sm" variant="outline" icon="download" label="demo-data.json" action="ASSETS.data.demo" onClick=${() => downloadText(exporters.demoData(), 'demo-data.json', 'application/json')} /></div></div>
      <div class="col gap8"><div class="row between wrap gap8"><h3 class="t-title-s">${t('assets.data.arb')}</h3><span class="row gap8"><${Badge} kind=${missing.length ? 'danger' : 'success'} icon=${missing.length ? 'circle-x' : 'circle-check'} label=${`${t('assets.data.missing')}: ${missing.length}`} /><${Badge} kind="neutral" label=${t('assets.data.keys', { count: keys.length })} /></span></div><p class="t-body-s c-sec">${t('assets.data.arbNote')}</p><div class="row gap8"><${Button} size="sm" variant="outline" icon="download" label="app_tr.arb" action="ASSETS.data.arb.tr" onClick=${() => downloadText(exporters.arb('tr'), 'app_tr.arb', 'application/json')} /><${Button} size="sm" variant="outline" icon="download" label="app_en.arb" action="ASSETS.data.arb.en" onClick=${() => downloadText(exporters.arb('en'), 'app_en.arb', 'application/json')} /></div>${missing.length ? html`<div class="pre">${missing.join('\n')}</div>` : null}
        <table class="table"><thead><tr><th>${t('assets.data.key')}</th><th>ARB</th><th>TR</th><th>EN</th></tr></thead><tbody>${rows.map((k) => html`<tr key=${k}><td><span class="code">${k}</span></td><td><span class="code">${dartName(k)}</span></td><td class="t-body-s">${I18N.tr[k]}</td><td class="t-body-s">${I18N.en[k]}</td></tr>`)}</tbody></table>${rows.length === 150 ? html`<p class="t-caption">${t('assets.data.showing', { n: 150 })}</p>` : null}</div></div>`; }

  function FlutterTab({ flash }) { const files = [['app_colors.dart', exporters.appColorsDart], ['app_theme.dart', exporters.appThemeDart], ['text_theme.dart', exporters.textThemeDart], ['l10n.yaml', exporters.l10nYaml], ['FONTS.md', exporters.fontsMD]]; const [open, setOpen] = useState('app_colors.dart'); const cur = files.find((f) => f[0] === open);
    return html`<div class="col gap16"><p class="t-body-s c-sec">${t('assets.flutter.note')}</p><div class="row wrap gap8">${files.map(([n]) => html`<${Chip} key=${n} label=${n} selected=${open === n} action=${'ASSETS.flutter.open.' + n} onClick=${() => setOpen(n)} />`)}</div><div class="row gap8"><${Button} size="sm" variant="outline" icon="copy" label=${t('assets.flutter.copy')} action=${'ASSETS.flutter.copy.' + open} onClick=${() => { copyText(cur[1]()); flash(t('assets.copied')); }} /><${Button} size="sm" variant="outline" icon="download" label=${t('assets.flutter.download')} action=${'ASSETS.flutter.download.' + open} onClick=${() => downloadText(cur[1](), open)} /></div><pre class="pre" style="max-height:520px">${cur[1]()}</pre></div>`; }

  function AssetsPage() { const [tab, setTab] = useState('icons'); const [q, setQ] = useState(''); const [msg, flash] = useFlash(); const [link, setLink] = useState(null);
    const TABS = [['icons', 'assets.tab.icons'], ['colors', 'assets.tab.colors'], ['type', 'assets.tab.type'], ['logo', 'assets.tab.logo'], ['illus', 'assets.tab.illus'], ['covers', 'assets.tab.covers'], ['data', 'assets.tab.data'], ['flutter', 'assets.tab.flutter']];
    const body = { icons: html`<${IconsTab} q=${q} flash=${flash} />`, colors: html`<${ColorsTab} flash=${flash} />`, type: html`<${TypeTab} flash=${flash} openLink=${setLink} />`, logo: html`<${LogoTab} flash=${flash} />`, illus: html`<${IllusTab} />`, covers: html`<${CoversTab} />`, data: html`<${DataTab} q=${q} />`, flutter: html`<${FlutterTab} flash=${flash} />` }[tab];
    return html`<div class="page-inner"><div class="row between wrap gap12 start"><div class="col gap6"><h1 class="t-display">${t('assets.title')}</h1><p class="t-body-m c-sec" style="max-width:640px">${t('assets.desc')}</p></div><${ZipButton} flash=${flash} /></div>
      <div class="row wrap gap12 between"><div class="page-tabs" style="border:0;padding:0" role="tablist">${TABS.map(([id, k]) => html`<${Tab} key=${id} id=${id} cur=${tab} set=${setTab} label=${t(k)} />`)}</div><div style="width:260px"><${Input} icon="search" placeholder=${t('assets.search')} value=${q} onInput=${setQ} action="ASSETS.search" ariaLabel=${t('assets.search')} /></div></div>
      ${tab !== 'type' ? html`<div><${ZipButton} section=${tab} flash=${flash} /></div>` : null}
      ${body}
      <${PageToast} msg=${msg} />
      ${link ? html`<div style="position:fixed;inset:0;z-index:1500" class="gu-root" data-theme=${app.theme()}><${DialogFrame} id="DLG-32" title=${t('dlg.32.title')} onClose=${() => setLink(null)} icon="external-link" actions=${html`<${Button} label=${t('common.open')} action="DLG-32.open" onClick=${() => { setLink(null); flash(t('tst.58', { what: t('dlg.32.link') })); }} /><${Button} variant="text" label=${t('common.giveUp')} action="DLG-32.cancel" onClick=${() => setLink(null)} />`}><p class="t-body-s c-sec">${t('dlg.32.body1')} <span class="code break">${link}</span></p><p class="t-body-s c-sec">${t('dlg.32.body2')}</p></${DialogFrame}></div>` : null}</div>`; }
  GU.PAGES = GU.PAGES || {}; GU.PAGES.assets = AssetsPage;
})();
