/* ===== SCREENS: CLB · FED ===== */
(function () {
  const { html, cx, Icon, app, useState, useEffect, useRef, useMemo, useForm, useBusy, Button, IconButton, Input, Picker, Switch, Chip, Segmented, Tabs, Badge, RoleBadge, StatusBadge, Card, Tile, AppBar, Banner, Scroll, Cover, Avatar, AvatarGroup, EmptyState, ListState, SectionTitle, ListEnd, StickyCTA, SuccessCheck, SkeletonList, Skeleton, ClubCard, MyClubChip, ClubCTA, startJoin, EventCard, PostCard, UserRow, MemberRow, catName, deptYear, userName, Progress, CATEGORIES, POPULAR_SEARCHES, PopMenu } = GU;
  const t = (k, p) => app.t(k, p); const S = GU.SCREENS; const sel = () => app.sel;
  const DEFAULT_FILTERS = { categories: [], membership: 'all', openOnly: false, instantOnly: false, sort: 'popular' };
  const filtersOf = () => ({ ...DEFAULT_FILTERS, ...(app.state.ui.clubFilters || {}) });
  const activeFilterCount = (f) => (f.categories.length ? 1 : 0) + (f.membership !== 'all' ? 1 : 0) + (f.openOnly ? 1 : 0) + (f.instantOnly ? 1 : 0) + (f.sort !== 'popular' ? 1 : 0);
  function applyClubFilters(list, f, u) {
    let out = list.filter((c) => c.status === 'active');
    if (f.categories.length) out = out.filter((c) => f.categories.includes(c.categoryId));
    if (f.membership === 'mine') out = out.filter((c) => sel().isMemberOf(c.id, u)); if (f.membership === 'notMine') out = out.filter((c) => !sel().isMemberOf(c.id, u));
    if (f.openOnly) out = out.filter((c) => c.applicationsOpen); if (f.instantOnly) out = out.filter((c) => !c.approvalRequired);
    if (f.sort === 'popular') out.sort((a, b) => b.memberCount - a.memberCount); else if (f.sort === 'new') out.sort((a, b) => b.createdAt - a.createdAt); else out.sort((a, b) => a.name.localeCompare(b.name, 'tr'));
    return out;
  }
  GU.clubFilters = { DEFAULT_FILTERS, filtersOf, applyClubFilters, activeFilterCount };

  /* CLB-01 */
  S['CLB-01'] = { tab: 'clubs', title: 'nav.clubs', comp: function Clubs({ route }) {
    const u = app.uid(); const f = filtersOf(); const grid = app.state.ui.viewMode === 'grid'; const mine = sel().myClubs(u); const all = applyClubFilters(sel().allClubs(), f, u); const nAct = activeFilterCount(f);
    const setF = (patch) => app.dispatch('ui.set', { clubFilters: { ...f, ...patch } });
    const [tick, setTick] = useState(0);
    return html`<${AppBar} large title=${t('nav.clubs')}><${IconButton} icon="search" label=${t('common.search')} action="CLB-01.search" onClick=${() => app.nav.push('CLB-02', { tab: 'clubs' })} /></${AppBar}>
      <${Scroll} routeKey=${route.key} onRefresh=${() => setTick(tick + 1)} refreshAction="CLB-01.refresh">
        ${mine.length ? html`<div class="section-title" style="margin-top:0"><h2 class="t-title-m">${t('clubs.my.title')}</h2></div><div class="hscroll pb16">${mine.map((m) => html`<${MyClubChip} key=${m.clubId} club=${m.club} manager=${m.role === 'board' || m.role === 'president'} unread=${sel().notifsFor(u).some((n) => !n.read && n.refs && n.refs.clubId === m.clubId)} />`)}<button type="button" class="card is-tappable" style="width:100px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px" data-action="CLB-01.myClubsAll" onClick=${() => app.nav.push('PRF-03')}><${Icon} name="arrow-right" size=${22} class="c-brand" /><span class="t-label-m c-brand">${t('common.all')}</span></button></div>`
        : html`<div class="px16 pb16"><${Card} class="card-body row gap12" muted><${GU.Illustration} name="empty-clubs" size=${72} /><div class="flex1 col gap6"><span class="t-title-s">${t('clubs.first.title')}</span><span class="t-body-s c-sec">${t('clubs.first.desc')}</span><div><${Button} size="sm" variant="tonal" label=${t('clubs.first.cta')} action="CLB-01.discover" onClick=${() => { const el = document.querySelector('.screen .screen-scroll'); const target = document.getElementById('club-list'); if (el && target) el.scrollTo({ top: target.offsetTop - 60, behavior: 'smooth' }); }} /></div></div></${Card}></div>`}
        <div class="hscroll pb16"><${Chip} label=${t('common.all')} selected=${!f.categories.length} action="CLB-01.category.all" onClick=${() => setF({ categories: [] })} />${CATEGORIES.map((c) => html`<${Chip} key=${c.id} icon=${c.icon} label=${t('cat.' + c.id)} selected=${f.categories.length === 1 && f.categories[0] === c.id} action=${'CLB-01.category.' + c.id} onClick=${() => setF({ categories: f.categories.length === 1 && f.categories[0] === c.id ? [] : [c.id] })} />`)}</div>
        <div class="row between px16 pb16" id="club-list"><span class="t-label-l c-sec tnum">${t('clubs.count', { count: all.length })}</span><span class="row gap4"><${Button} variant="outline" size="sm" icon="sliders-horizontal" label=${t('common.filterSort')} action="CLB-01.filter" onClick=${() => app.openSheet('SHT-04')} />${nAct ? html`<span class="badge-count" aria-label=${t('clubs.activeFilters', { count: nAct })}>${nAct}</span>` : null}<${IconButton} icon=${grid ? 'list' : 'layout-grid'} label=${grid ? t('common.listView') : t('common.gridView')} action="CLB-01.toggleView" onClick=${() => app.dispatch('ui.set', { viewMode: grid ? 'list' : 'grid' })} /></span></div>
        <${ListState} n=${6} variant="card" emptyProps=${{ illustration: 'empty-clubs', title: t('clubs.empty.title'), desc: t('clubs.empty.desc'), cta: t('clubs.empty.clear'), ctaAction: 'CLB-01.clearFilters', onCta: () => app.dispatch('ui.set', { clubFilters: null, dataMode: 'normal' }) }}>
          ${all.length ? html`<div class=${cx(grid ? 'grid2 px16' : 'col gap12 px16')}>${all.map((c) => html`<${ClubCard} key=${c.id + tick} club=${c} grid=${grid} />`)}</div><${ListEnd} />`
          : html`<${EmptyState} illustration="empty-clubs" title=${t('clubs.empty.title')} desc=${t('clubs.empty.desc')} cta=${t('clubs.empty.clear')} ctaAction="CLB-01.clearFilters" onCta=${() => app.dispatch('ui.set', { clubFilters: null })} />`}
        </${ListState}></${Scroll}>`;
  } };

  /* CLB-02 search */
  function Highlight({ text, q }) { if (!q) return text; const i = text.toLocaleLowerCase('tr').indexOf(q.toLocaleLowerCase('tr')); if (i < 0) return text; return html`${text.slice(0, i)}<b>${text.slice(i, i + q.length)}</b>${text.slice(i + q.length)}`; }
  S['CLB-02'] = { tab: 'clubs', title: 'search.title', comp: function Search({ params }) {
    const u = app.uid(); const [q, setQ] = useState(''); const [dq, setDq] = useState(''); const [tab, setTab] = useState(params.tab || 'clubs'); const [busy, setBusy] = useState(false);
    useEffect(() => { setBusy(true); const id = setTimeout(() => { setDq(q.trim()); setBusy(false); }, 250); return () => clearTimeout(id); }, [q]);
    const recents = app.state.ui.recentSearches; const me = app.me();
    const suggested = useMemo(() => { const ints = (me && me.interests) || []; const cats = GU.INTERESTS.filter((i) => ints.includes(i.id)).map((i) => i.cat); return sel().visibleClubs().filter((c) => !sel().isMemberOf(c.id, u)).sort((a, b) => (cats.includes(b.categoryId) ? 1 : 0) - (cats.includes(a.categoryId) ? 1 : 0)).slice(0, 3); }, [u]);
    const clubs = dq ? sel().visibleClubs().filter((c) => (c.name + ' ' + c.summary + ' ' + c.about + ' ' + catName(c)).toLocaleLowerCase('tr').includes(dq.toLocaleLowerCase('tr'))) : [];
    const events = dq ? sel().visibleEvents(u).filter((e) => (e.title + ' ' + e.desc + ' ' + GU.placeName(e)).toLocaleLowerCase('tr').includes(dq.toLocaleLowerCase('tr'))) : [];
    const commit = () => { if (q.trim()) app.dispatch('search.add', { q: q.trim() }); };
    return html`<div class="row gap4" style="padding:4px 8px 4px 16px"><div class="input flex1" style="min-height:44px"><${Icon} name="search" size=${20} class="c-muted" /><input type="search" value=${q} placeholder=${t('search.placeholder')} aria-label=${t('common.search')} data-action="CLB-02.input" data-autofocus="1" ref=${(el) => el && !el.dataset.f && (el.dataset.f = 1, setTimeout(() => el.focus(), 50))} onInput=${(e) => setQ(e.target.value)} onKeyDown=${(e) => e.key === 'Enter' && commit()} />${q ? html`<${IconButton} small icon="x" label=${t('common.clear')} action="CLB-02.clear" onClick=${() => setQ('')} />` : null}</div><${Button} variant="text" label=${t('common.cancel')} action="CLB-02.cancel" onClick=${() => app.nav.back()} /></div>
      <${Tabs} tabs=${[{ id: 'clubs', label: t('nav.clubs') }, { id: 'events', label: t('nav.events') }]} value=${tab} onChange=${setTab} action="CLB-02.tab" />
      <${Scroll} routeKey="search">
        ${!dq ? html`${recents.length ? html`<${SectionTitle} title=${t('search.recent')} actionLabel=${t('common.clear')} action="CLB-02.clearRecent" onAction=${() => { const prev = recents; app.dispatch('search.set', { list: [] }); app.toast('TST-06', { undo: () => app.dispatch('search.set', { list: prev }) }); }} />${recents.map((r, i) => html`<${Tile} key=${r} leading=${html`<${Icon} name="history" size=${20} class="c-muted" />`} title=${r} action=${'CLB-02.recent.' + i} onClick=${() => setQ(r)} trailing=${html`<${IconButton} small icon="x" label=${t('common.remove')} action=${'CLB-02.removeRecent.' + i} onClick=${(e) => { e.stopPropagation(); app.dispatch('search.remove', { i }); }} />`} />`)}` : null}
          <${SectionTitle} title=${t('search.popular')} /><div class="row wrap gap8 px16">${POPULAR_SEARCHES.map((p, i) => html`<${Chip} key=${p} icon="trending-up" label=${p} action=${'CLB-02.popular.' + i} onClick=${() => setQ(p)} />`)}</div>
          ${tab === 'clubs' ? html`<${SectionTitle} title=${t('search.suggested')} /><div class="col gap12 px16">${suggested.map((c) => html`<${ClubCard} key=${c.id} club=${c} screen="CLB-02" grid=${false} />`)}</div>` : null}`
        : busy ? html`<${SkeletonList} n=${3} />`
        : tab === 'clubs' ? (clubs.length ? html`<div class="col">${clubs.map((c) => html`<${Tile} key=${c.id} leading=${html`<span class="emblem is-sm"><${Icon} name=${c.iconName} size=${20} /></span>`} title=${html`<${Highlight} text=${c.name} q=${dq} />`} subtitle=${`${catName(c)} · ${t('clubs.card.members', { count: c.memberCount })}`} chevron action=${'CLB-02.result.club.' + c.id} onClick=${() => { commit(); app.nav.push('CLB-03', { id: c.id }); }} />`)}</div>` : html`<${NoResults} q=${dq} onPick=${setQ} />`)
        : (events.length ? html`<div class="col">${events.map((e) => html`<${Tile} key=${e.id} leading=${html`<${GU.DateBadge} ts=${e.startsAt} />`} title=${html`<${Highlight} text=${e.title} q=${dq} />`} subtitle=${`${sel().club(e.clubId).name} · ${app.fmt.time(e.startsAt)}`} chevron action=${'CLB-02.result.event.' + e.id} onClick=${() => { commit(); app.nav.push('EVT-02', { id: e.id }); }} />`)}</div>` : html`<${NoResults} q=${dq} onPick=${setQ} />`)}
      </${Scroll}>`;
  } };
  function NoResults({ q, onPick }) { return html`<div class="empty"><${GU.Illustration} name="empty-clubs" size=${100} /><h3 class="t-title-s">${t('search.noResults', { q })}</h3><div class="row wrap gap8" style="justify-content:center">${POPULAR_SEARCHES.slice(0, 4).map((p, i) => html`<${Chip} key=${p} label=${p} action=${'CLB-02.suggest.' + i} onClick=${() => onPick(p)} />`)}</div></div>`; }

  /* FED-01 feed (component used inside CLB-03) */
  function Feed({ clubId, screen = 'FED-01', highlightId }) {
    const u = app.uid(); const club = sel().club(clubId); const manager = sel().isManager(clubId, u); const [filter, setFilter] = useState('all'); const posts = sel().clubPosts(clubId, u);
    const countRef = useRef(posts.length); const [fresh, setFresh] = useState(0);
    useEffect(() => { if (posts.length > countRef.current) setFresh(posts.length - countRef.current); }, [posts.length]);
    const filtered = posts.filter((p) => filter === 'all' || (filter === 'announcements' && p.type === 'announcement') || (filter === 'polls' && p.type === 'poll') || (filter === 'images' && p.images.length));
    const compose = () => app.nav.push('FED-03', { clubId });
    return html`<div class="col gap12 pt16">
      ${manager ? html`<div class="px16"><button type="button" class="card row gap12" style="padding:12px 16px;width:100%;text-align:left" data-action="FED-01.compose" onClick=${compose}><${Avatar} user=${app.me()} size=${36} /><span class="t-body-m c-muted flex1">${t('feed.composePlaceholder')}</span><${Icon} name="pencil" size=${18} class="c-brand" /></button></div>` : null}
      <div class="hscroll">${[['all', t('common.all')], ['announcements', t('feed.filter.announcements')], ['polls', t('feed.filter.polls')], ['images', t('feed.filter.images')]].map(([id, label]) => html`<${Chip} key=${id} label=${label} selected=${filter === id} action=${'FED-01.filter.' + id} onClick=${() => setFilter(id)} />`)}</div>
      ${fresh ? html`<div class="row" style="justify-content:center"><${Chip} icon="arrow-up" label=${t('feed.newPosts', { count: fresh })} selected action="FED-01.newPosts" onClick=${() => { countRef.current = posts.length; setFresh(0); const sc = document.querySelector('.screen .screen-scroll'); sc && sc.scrollTo({ top: 0, behavior: 'smooth' }); }} /></div>` : null}
      <${ListState} n=${3} variant="card" emptyProps=${{ illustration: 'empty-posts', title: t('feed.empty.title'), desc: manager ? t('feed.empty.descManager') : t('feed.empty.desc'), cta: manager ? t('feed.empty.cta') : null, ctaAction: 'FED-01.compose', onCta: compose }}>
        ${filtered.length ? html`<div class="col gap12 px16">${filtered.map((p) => html`<${PostCard} key=${p.id} post=${p} screen=${screen} highlight=${p.id === highlightId} />`)}</div><${ListEnd} />` : html`<${EmptyState} illustration="empty-posts" title=${t('feed.empty.title')} desc=${manager ? t('feed.empty.descManager') : t('feed.empty.desc')} cta=${manager ? t('feed.empty.cta') : null} ctaAction="FED-01.compose" onCta=${compose} />`}
      </${ListState}></div>`;
  }
  S['FED-01'] = { tab: 'clubs', title: 'feed.title', comp: function FeedScreen({ params }) { return html`<${AppBar} onBack=${() => app.nav.back()} backAction="FED-01.back" title=${t('feed.title')} /><${Scroll} routeKey=${'feed-' + params.id}><${Feed} clubId=${params.id || 'c01'} /></${Scroll}>`; }, embedded: true };
  GU.Feed = Feed;

  /* CLB-03 club detail */
  S['CLB-03'] = { tab: 'clubs', title: 'club.title', comp: function ClubDetail({ params, route }) {
    const u = app.uid(); const club = sel().club(params.id); const [tab, setTab] = useState(params.tab || 'about'); const [py, setPy] = useState(0); const [more, setMore] = useState(false); const [evSeg, setEvSeg] = useState('upcoming');
    if (!club) return html`${S['SYS-04'].comp({})}`;
    const mode = sel().mode(club.id, u); const inside = sel().canSeeInside(club.id, u); const members = sel().clubMembers(club.id); const board = sel().board(club.id); const advisor = sel().user(club.advisorId); const m = sel().membership(club.id, u);
    const events = sel().clubEvents(club.id).filter((e) => e.status !== 'draft' && (inside || e.visibility === 'public')).filter((e) => (evSeg === 'upcoming' ? e.endsAt >= Date.now() && e.status !== 'cancelled' : e.endsAt < Date.now() || e.status === 'cancelled')).sort((a, b) => (evSeg === 'upcoming' ? a.startsAt - b.startsAt : b.startsAt - a.startsAt));
    const onScroll = (e) => setPy(Math.min(220, e.target.scrollTop));
    const link = (type, url) => app.openDialog('DLG-32', { url, action: `CLB-03.about.link.${type}` });
    const lockBlock = (text) => html`<div class="empty"><${GU.Illustration} name="locked" size=${100} /><p class="t-body-m c-sec">${text}</p>${mode === 'visitor' || mode === 'pending' || mode === 'rejected' || mode === 'removed' ? html`<${ClubCTA} club=${club} screen="CLB-03" />` : null}</div>`;
    return html`<div class="screen-scroll no-safe" onScroll=${onScroll} style="padding-top:0;margin-top:calc(-1 * var(--safe-top))">
      <div class="parallax" style=${{ '--py': py }}><${Cover} seed=${club.coverSeed} icon=${club.iconName} palette=${club.palette} pattern=${club.pattern} style=${{ height: '100%' }} /><div class="parallax-bar"><${IconButton} onCover icon="arrow-left" label=${t('a11y.back')} action="CLB-03.back" onClick=${() => app.nav.back()} /><span class="spacer" /><${IconButton} onCover icon="share-2" label=${t('common.share')} action="CLB-03.share" onClick=${() => app.openSheet('SHT-15', { type: 'club', id: club.id })} /><${IconButton} onCover icon="more-vertical" label=${t('a11y.more')} action="CLB-03.menu" onClick=${() => app.openSheet('SHT-06', { clubId: club.id })} /></div></div>
      ${club.status === 'suspended' ? html`<${Banner} kind="warning" icon="ban" text=${t('club.suspendedBanner')} />` : null}
      ${mode === 'advisor' ? html`<${Banner} kind="readonly" text=${t('mgt.readOnlyBanner')} />` : null}
      <div class="px16" style="margin-top:-36px;position:relative"><span class="emblem"><${Icon} name=${club.iconName} size=${34} /></span></div>
      <div class="col gap8 px16 pt8"><h1 class="t-title-l">${club.name}</h1>
        <div class="row gap6 wrap"><${Badge} kind="neutral" label=${catName(club)} /><${Badge} kind=${club.approvalRequired ? 'info' : 'success'} icon=${club.approvalRequired ? 'shield-check' : 'sparkles'} label=${club.approvalRequired ? t('club.type.approval') : t('club.type.instant')} />${m && m.status === 'active' ? html`<${RoleBadge} role=${m.role} />` : null}</div>
        <button type="button" class="row gap8" style="text-align:left" data-action="CLB-03.memberCount" onClick=${() => setTab('members')} aria-label=${t('clubs.card.members', { count: club.memberCount })}><${AvatarGroup} users=${members.slice(0, 4).map((x) => x.user)} size=${28} total=${club.memberCount} /><span class="t-body-s c-sec tnum">${t('clubs.card.members', { count: club.memberCount })}</span></button></div>
      <div class="pt16"><${Tabs} sticky tabs=${[{ id: 'about', label: t('club.tab.about') }, { id: 'events', label: t('club.tab.events') }, { id: 'posts', label: t('club.tab.posts') }, { id: 'members', label: t('club.tab.members') }]} value=${tab} onChange=${setTab} action="CLB-03.tab" /></div>
      ${tab === 'about' ? html`<div class="col gap20 px16 pt16 pb24">
        <div class="col gap8"><p class=${cx('t-body-m', !more && 'clamp3')}>${club.about}</p>${!more ? html`<button type="button" class="t-label-l c-brand" style="text-align:left" data-action="CLB-03.about.more" onClick=${() => setMore(true)}>${t('common.readMore')}</button>` : null}<span class="t-caption row gap4"><${Icon} name="landmark" size=${14} />${t('club.founded', { year: club.founded })}</span></div>
        <${Card}><${Tile} inCard leading=${html`<${Icon} name="mail" size=${20} class="c-brand" />`} title=${club.social.email} subtitle=${t('club.contact.email')} action="CLB-03.about.link.email" onClick=${() => link('email', 'mailto:' + club.social.email)} /><div class="divider" /><${Tile} inCard leading=${html`<${Icon} name="camera" size=${20} class="c-brand" />`} title=${club.social.instagram} subtitle="Instagram" action="CLB-03.about.link.instagram" onClick=${() => link('instagram', 'https://instagram.com/' + club.social.instagram.slice(1))} /><div class="divider" /><${Tile} inCard leading=${html`<${Icon} name="globe" size=${20} class="c-brand" />`} title=${club.social.web.replace('https://', '')} subtitle=${t('club.contact.web')} action="CLB-03.about.link.web" onClick=${() => link('web', club.social.web)} /></${Card}>
        <div class="col gap8"><h2 class="t-title-s">${t('club.advisor')}</h2><${Card}><${UserRow} user=${advisor} sub=${t('role.advisor')} action=${'CLB-03.about.person.' + (advisor ? advisor.id : 'x')} onClick=${() => advisor && app.nav.push('CLB-07', { id: advisor.id, clubId: club.id })} inCard chevron /></${Card}></div>
        <div class="col gap8"><h2 class="t-title-s">${t('club.board')}</h2><${Card}>${board.map((b, i) => html`${i ? html`<div class="divider" />` : null}<${UserRow} key=${b.userId} user=${b.user} sub=${deptYear(b.user)} badge=${html`<${RoleBadge} role=${b.role} />`} action=${'CLB-03.about.person.' + b.userId} onClick=${() => app.nav.push('CLB-07', { id: b.userId, clubId: club.id })} inCard chevron />`)}</${Card}></div>
        <div class="col gap8"><h2 class="t-title-s">${t('club.conditions')}</h2><ul class="col gap6 t-body-m c-sec">${club.conditions.map((c) => html`<li key=${c}>${c}</li>`)}</ul></div>
        <${Button} variant="text" icon="flag" label=${t('club.report')} action="CLB-03.report" onClick=${() => app.openSheet('SHT-10', { targetType: 'club', targetId: club.id })} />
      </div>` : null}
      ${tab === 'events' ? html`<div class="col gap12 px16 pt16 pb24"><${Segmented} options=${[{ id: 'upcoming', label: t('event.upcoming') }, { id: 'past', label: t('event.past') }]} value=${evSeg} onChange=${setEvSeg} action="CLB-03.eventSeg" />
        ${!inside ? html`<${Banner} kind="info" icon="lock" text=${t('club.eventsVisitorNote')} />` : null}
        <${ListState} n=${3} variant="card" emptyProps=${{ illustration: 'empty-events', title: t('event.empty.title') }}>${events.length ? events.map((e) => html`<${EventCard} key=${e.id} ev=${e} screen="CLB-03" compact showClub=${false} />`) : html`<${EmptyState} illustration="empty-events" title=${t('event.empty.title')} compact />`}</${ListState}></div>` : null}
      ${tab === 'posts' ? (inside ? html`<${Feed} clubId=${club.id} highlightId=${params.highlight} />` : lockBlock(t('club.postsLocked'))) : null}
      ${tab === 'members' ? (inside ? html`<div class="col gap8 pt16 pb24"><div class="px16 t-label-l c-sec tnum">${t('clubs.card.members', { count: club.memberCount })}</div>${members.slice(0, 5).map((mm) => html`<${MemberRow} key=${mm.userId} m=${mm} screen="CLB-03" clubId=${club.id} />`)}<div class="px16"><${Button} variant="outline" full label=${t('club.allMembers')} iconRight="arrow-right" action="CLB-03.allMembers" onClick=${() => app.nav.push('CLB-06', { id: club.id })} /></div></div>` : lockBlock(t('club.membersLocked', { count: club.memberCount }))) : null}
    </div>
    ${club.status === 'suspended' ? null : mode === 'manager' || mode === 'super' ? html`<${StickyCTA}><${Button} icon="layout-grid" label=${t('club.cta.manage')} action="CLB-03.openManage" onClick=${() => app.nav.push('MGT-01', { clubId: club.id })} /><${Button} variant="tonal" icon="calendar-plus" label=${t('club.cta.createEvent')} action="CLB-03.createEvent" onClick=${() => app.nav.push('MGT-05', { clubId: club.id })} /></${StickyCTA}>`
      : mode === 'advisor' ? html`<${StickyCTA}><${Button} variant="tonal" icon="eye" label=${t('club.cta.viewManage')} action="CLB-03.openManage" onClick=${() => app.nav.push('MGT-01', { clubId: club.id })} /></${StickyCTA}>`
      : mode === 'member' ? null
      : html`<${StickyCTA}><div class="flex1 col gap4">${mode === 'visitor' && !club.applicationsOpen ? html`<span class="t-caption center">${t('club.closedNote')}</span>` : null}${mode === 'rejected' && m && m.retryAfter > Date.now() ? html`<span class="t-caption center">${t('application.retryAt', { date: app.fmt.date(m.retryAfter) })}</span>` : null}<${ClubCTA} club=${club} screen="CLB-03" size="lg" full /></div></${StickyCTA}>`}`;
  } };

  /* CLB-04 applied */
  S['CLB-04'] = { tab: 'clubs', title: 'applied.title', comp: function Applied({ params }) {
    const u = app.uid(); const club = sel().club(params.id); const m = sel().membership(params.id, u); const perm = app.state.session.notifPermission;
    return html`<${AppBar} onBack=${() => app.nav.popTo('CLB-03') || app.nav.back()} backAction="CLB-04.close" closeIcon title="" /><${Scroll} routeKey="applied"><div class="col gap16 px16 center" style="align-items:center;padding-top:16px"><${SuccessCheck} size=${110} /><h1 class="t-title-l">${t('applied.title')}</h1><p class="t-body-m c-sec">${t('applied.desc')}</p>
      <${Card} class="card-body col gap8" style="width:100%;text-align:left"><div class="row gap12"><span class="emblem is-sm"><${Icon} name=${club.iconName} size=${20} /></span><div class="flex1"><div class="t-title-s">${club.name}</div><div class="t-caption">${t('applied.sentAt', { date: app.fmt.dateTime(m ? m.appliedAt : Date.now()) })}</div></div></div>${m && m.note ? html`<p class="t-body-s c-sec" style="font-style:italic">“${m.note}”</p>` : null}</${Card}>
      ${perm !== 'granted' ? html`<${Card} muted class="card-body row gap12" style="width:100%;text-align:left"><${Icon} name="bell-ring" size=${22} class="c-brand" /><span class="flex1 t-body-s">${t('applied.enableNotif')}</span><${Button} size="sm" variant="tonal" label=${t('common.open')} action="CLB-04.enableNotifications" onClick=${() => app.openDialog('DLG-03')} /></${Card}>` : null}
      <${Button} size="lg" full label=${t('applied.browse')} action="CLB-04.browse" onClick=${() => app.nav.resetTo('CLB-01')} /><${Button} variant="text" label=${t('applied.myApplications')} action="CLB-04.myApplications" onClick=${() => app.nav.openInTab('profile', [{ screen: 'PRF-03', params: { tab: 'pending' } }])} /></div></${Scroll}>`;
  } };

  /* CLB-05 application status */
  S['CLB-05'] = { tab: 'clubs', title: 'application.title', comp: function ApplicationStatus({ params }) {
    const u = app.uid(); const club = sel().club(params.id); const m = sel().membership(params.id, u); const [note, setNote] = useState(m ? m.note : ''); const [busy, run] = useBusy();
    if (!club) return html`${S['SYS-04'].comp({})}`;
    const st = m ? m.status : 'none'; const steps = [{ k: 'sent', done: true }, { k: 'review', done: st !== 'pending', active: st === 'pending' }, { k: 'result', done: st === 'active' || st === 'rejected' || st === 'removed', danger: st === 'rejected' || st === 'removed' }];
    const canRetry = sel().canReapply(m);
    return html`<${AppBar} onBack=${() => app.nav.back()} backAction="CLB-05.back" title=${t('application.title')} /><${Scroll} routeKey="appstatus"><div class="col gap20 px16 pt8 pb24">
      <${Card} tappable action="CLB-05.openClub" onClick=${() => app.nav.push('CLB-03', { id: club.id })} label=${club.name}><div class="row gap12 card-body" style="padding:12px 16px"><span class="emblem is-sm"><${Icon} name=${club.iconName} size=${20} /></span><div class="flex1"><div class="t-title-s">${club.name}</div><div class="t-caption">${catName(club)}</div></div><${StatusBadge} status=${st === 'active' ? 'approved' : st === 'none' ? 'cancelled' : st} /></div></${Card}>
      <div class="timeline">${steps.map((s, i) => html`<div class="timeline-item" key=${s.k}><div class="timeline-rail"><span class=${cx('timeline-dot', s.done && (s.danger ? 'is-danger' : 'is-done'), s.active && 'is-active')} />${i < 2 ? html`<span class="timeline-line" />` : null}</div><div class="col gap2 pb16"><span class="t-label-l c-heading">${t('application.step.' + s.k)}</span><span class="t-caption">${i === 0 && m ? app.fmt.dateTime(m.appliedAt) : i === 1 ? (st === 'pending' ? t('application.reviewing') : m && m.decidedAt ? app.fmt.dateTime(m.decidedAt) : '') : i === 2 ? (st === 'active' ? t('status.approved') : st === 'rejected' ? t('status.rejected') : st === 'removed' ? t('status.removed') : t('application.waitingResult')) : ''}</span></div></div>`)}</div>
      ${st === 'pending' ? html`<${Input} label=${t('application.yourNote')} multiline maxLength=${300} counter value=${note} onInput=${setNote} action="CLB-05.note" /><${Button} variant="tonal" label=${t('common.save')} loading=${busy} disabled=${note === (m.note || '')} action="CLB-05.saveNote" onClick=${() => run(async () => { if (!app.requireOnline()) return; await app.api(); app.dispatch('membership.saveNote', { clubId: club.id, userId: u, note }); app.toast('TST-07'); })} /><${Button} variant="danger-outline" label=${t('application.cancel')} action="CLB-05.cancel" onClick=${() => app.openDialog('DLG-07', { clubId: club.id })} />` : null}
      ${st === 'rejected' || st === 'removed' ? html`${m.rejectReason ? html`<${Card} muted class="card-body col gap4"><span class="t-overline">${t('application.reason')}</span><span class="t-body-m">${t('rejectReason.' + m.rejectReason)}</span>${m.rejectNote ? html`<span class="t-body-s c-sec">${m.rejectNote}</span>` : null}</${Card}>` : null}
        <div class="row gap8"><${Badge} kind=${canRetry ? 'success' : 'pending'} icon="hourglass" label=${canRetry ? t('application.canReapply') : t('application.retryAt', { date: app.fmt.date(m.retryAfter) })} />${!canRetry ? html`<span class="t-caption">${app.fmt.countdown(m.retryAfter)}</span>` : null}</div>
        <${Button} label=${t('application.reapply')} disabled=${!canRetry || !club.applicationsOpen} action="CLB-05.reapply" onClick=${() => startJoin(club.id)} onDisabledClick=${() => app.toast(!club.applicationsOpen ? 'TST-X1' : 'TST-X4', { date: app.fmt.date(m.retryAfter) })} />${!canRetry ? html`<p class="t-caption">${t('application.retryNote')}</p>` : null}` : null}
      ${st === 'active' ? html`<${Banner} kind="success" text=${t('application.approvedNote')} /><${Button} label=${t('application.goClub')} action="CLB-05.openClub" onClick=${() => app.nav.push('CLB-03', { id: club.id })} />` : null}
      ${st === 'none' ? html`<${Banner} kind="info" text=${t('application.noneNote')} /><${Button} label=${t('clubs.card.join')} action="CLB-05.reapply" onClick=${() => startJoin(club.id)} />` : null}
    </div></${Scroll}>`;
  } };

  /* CLB-06 members */
  S['CLB-06'] = { tab: 'clubs', title: 'members.title', comp: function Members({ params }) {
    const u = app.uid(); const club = sel().club(params.id); const [q, setQ] = useState(''); const [role, setRole] = useState('all'); const manager = sel().isManager(club.id, u) || sel().isSuper(u);
    const all = sel().clubMembers(club.id).filter((m) => !q || m.user.name.toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))).filter((m) => role === 'all' || (role === 'board' && (m.role === 'board' || m.role === 'president')) || (role === 'member' && m.role === 'member'));
    const groups = [['president', all.filter((m) => m.role === 'president')], ['board', all.filter((m) => m.role === 'board')], ['advisor', all.filter((m) => m.role === 'advisor')], ['member', all.filter((m) => m.role === 'member').sort((a, b) => a.user.name.localeCompare(b.user.name, 'tr'))]].filter(([, l]) => l.length);
    return html`<${AppBar} onBack=${() => app.nav.back()} backAction="CLB-06.back" title=${t('members.title')} subtitle=${club.name} /><div class="px16 pb16"><${Input} icon="search" placeholder=${t('members.search')} value=${q} onInput=${setQ} action="CLB-06.search" ariaLabel=${t('members.search')} /></div><div class="hscroll pb16">${[['all', t('common.all')], ['board', t('members.filter.board')], ['member', t('role.member')]].map(([id, l]) => html`<${Chip} key=${id} label=${l} selected=${role === id} action=${'CLB-06.filter.' + id} onClick=${() => setRole(id)} />`)}</div>
      <${Scroll} routeKey=${'members-' + club.id}><${ListState} n=${6} emptyProps=${{ title: t('members.noResults') }}>${all.length ? html`<div class="px16 t-caption tnum pb16">${t('members.total', { count: all.length })}</div>${groups.map(([r, list]) => html`<div key=${r}><div class="group-head"><span class="t-overline">${t('role.' + r)}</span><span class="t-caption tnum">${list.length}</span></div>${list.map((m) => html`<${MemberRow} key=${m.userId} m=${m} screen="CLB-06" clubId=${club.id} onMenu=${manager && m.role !== 'president' && m.role !== 'advisor' ? () => app.openSheet('SHT-21', { clubId: club.id, userId: m.userId }) : null} />`)}</div>`)}` : html`<${EmptyState} illustration="empty-clubs" title=${t('members.noResults')} compact />`}</${ListState}></${Scroll}>`;
  } };

  /* CLB-07 other user's profile */
  S['CLB-07'] = { tab: null, title: 'userprofile.title', comp: function UserProfile({ params }) {
    const u = app.uid(); const usr = sel().user(params.id); const me = app.me(); if (!usr) return html`${S['SYS-04'].comp({})}`;
    const common = sel().commonClubs(u, usr.id); const ctxClub = params.clubId ? sel().club(params.clubId) : null; const managerCtx = ctxClub && (sel().isManager(ctxClub.id, u) || sel().isSuper(u)) && sel().membership(ctxClub.id, usr.id); const blocked = (me.blocked || []).includes(usr.id); const visible = common.length > 0 || managerCtx || sel().isSuper(u) || usr.id === u;
    const roles = common.map((c) => ({ club: c, role: sel().roleIn(c.id, usr.id) })).filter((x) => x.role && x.role !== 'member');
    return html`<${AppBar} onBack=${() => app.nav.back()} backAction="CLB-07.back" title=${t('userprofile.title')}>${usr.id !== u ? html`<${IconButton} icon="more-vertical" label=${t('a11y.more')} action="CLB-07.menu" onClick=${() => app.openSheet('SHT-27', { userId: usr.id })} />` : null}</${AppBar}>
      <${Scroll} routeKey=${'user-' + usr.id}>${blocked ? html`<${Banner} kind="warning" icon="ban" text=${t('userprofile.blockedBanner')} actionLabel=${t('userprofile.unblock')} action="CLB-07.unblock" onAction=${() => { const snap = app.store.get(); app.dispatch('user.unblock', { userId: u, targetId: usr.id }); app.toast('TST-09', { name: usr.name, unblocked: true, undo: () => app.store.restore(snap) }); }} />` : null}
      <div class="col gap8 center px16 pt16" style="align-items:center"><${Avatar} user=${usr} size=${96} /><h1 class="t-title-l">${usr.name}</h1>${visible ? html`<span class="t-body-m c-sec">${deptYear(usr)}</span>` : null}${usr.global === 'superadmin' ? html`<${RoleBadge} role="superadmin" />` : null}${roles.length ? html`<div class="row gap6 wrap" style="justify-content:center">${roles.map((r) => html`<${RoleBadge} key=${r.club.id} role=${r.role} />`)}</div>` : null}${visible && usr.bio ? html`<p class="t-body-s c-sec center" style="max-width:280px">${usr.bio}</p>` : null}</div>
      ${!visible ? html`<div class="empty"><${GU.Illustration} name="locked" size=${96} /><p class="t-body-s c-sec">${t('userprofile.private')}</p></div>` : html`<div class="col gap20 px16 pt24">
        ${common.length ? html`<div class="col gap8"><h2 class="t-title-s">${t('userprofile.commonClubs')}</h2><div class="row wrap gap8">${common.map((c) => html`<${Chip} key=${c.id} icon=${c.iconName} label=${c.name} action=${'CLB-07.club.' + c.id} onClick=${() => app.nav.push('CLB-03', { id: c.id })} />`)}</div></div>` : null}
        ${managerCtx || sel().isSuper(u) ? html`<${Card}><${Tile} inCard leading=${html`<${Icon} name="mail" size=${20} class="c-muted" />`} title=${usr.email} subtitle=${t('auth.email')} trailing=${html`<${Button} size="sm" variant="text" icon="copy" label=${t('common.copy')} action="CLB-07.copyEmail" onClick=${() => { GU.copyText(usr.email); app.toast('TST-08'); }} />`} />${managerCtx ? html`<div class="divider" /><${Tile} inCard leading=${html`<${Icon} name="shield-check" size=${20} class="c-muted" />`} title=${t('role.' + managerCtx.role)} subtitle=${t('userprofile.roleIn', { club: ctxClub.name })} /><div class="divider" /><${Tile} inCard leading=${html`<${Icon} name="calendar-check" size=${20} class="c-muted" />`} title=${managerCtx.decidedAt ? app.fmt.date(managerCtx.decidedAt) : '—'} subtitle=${t('userprofile.memberSince')} />` : null}</${Card}>` : null}
        ${managerCtx && managerCtx.role !== 'president' && managerCtx.role !== 'advisor' ? html`<div class="col gap8">${sel().isPresident(ctxClub.id, u) || sel().isSuper(u) ? html`<${Button} variant="outline" icon="user-cog" label=${t('userprofile.changeRole')} action="CLB-07.changeRole" onClick=${() => app.openSheet('SHT-22', { clubId: ctxClub.id, userId: usr.id })} />` : null}<${Button} variant="danger-outline" icon="user-x" label=${t('userprofile.remove')} action="CLB-07.remove" onClick=${() => app.openDialog('DLG-19', { clubId: ctxClub.id, userId: usr.id })} /></div>` : null}
      </div>`}</${Scroll}>`;
  } };

  /* FED-02 post detail */
  S['FED-02'] = { tab: 'clubs', title: 'post.title', comp: function PostDetail({ params }) {
    const u = app.uid(); const post = sel().post(params.postId); const [text, setText] = useState(''); const [busy, run] = useBusy(); const listRef = useRef();
    if (!post || post.deleted || post.hidden) return html`${S['SYS-04'].comp({})}`;
    const comments = sel().postComments(post.id, u); const advisor = sel().isAdvisor(post.clubId, u); const manager = sel().isManager(post.clubId, u) || sel().isSuper(u); const canView = sel().canSeeInside(post.clubId, u);
    const send = () => run(async () => { if (!text.trim()) return; if (!app.requireOnline()) return; await app.api(); app.dispatch('comment.add', { postId: post.id, authorId: u, text: text.trim() }); setText(''); app.toast('TST-12'); setTimeout(() => { const sc = document.querySelector('.screen .screen-scroll'); sc && sc.scrollTo({ top: sc.scrollHeight, behavior: 'smooth' }); }, 60); });
    const commentMenu = (c) => { if (c.authorId === u) app.openDialog('DLG-11', { commentId: c.id }); else if (manager) app.openSheet('SHT-27', { userId: c.authorId, commentId: c.id, canDelete: true }); else app.openSheet('SHT-27', { userId: c.authorId, commentId: c.id }); };
    if (!canView) return html`<${AppBar} onBack=${() => app.nav.back()} backAction="FED-02.back" title=${t('post.title')} /><div class="empty"><${GU.Illustration} name="locked" /><p class="t-body-m c-sec">${t('club.postsLocked')}</p><${Button} label=${t('club.goClub')} action="FED-02.club" onClick=${() => app.nav.push('CLB-03', { id: post.clubId })} /></div>`;
    return html`<${AppBar} onBack=${() => app.nav.back()} backAction="FED-02.back" title=${t('post.title')} subtitle=${sel().club(post.clubId).name} />
      <${Scroll} routeKey=${'post-' + post.id}><div class="px16 col gap16"><${PostCard} post=${post} screen="FED-02" expanded showClub />
        <h2 class="t-title-s tnum">${t('post.comments', { count: comments.length })}</h2>
        ${comments.length ? html`<div class="col gap4">${comments.map((c) => { const a = sel().user(c.authorId); const role = a ? sel().roleIn(post.clubId, a.id) : null; return html`<div key=${c.id} class="row gap10 start" style="padding:8px 0;align-items:flex-start"><button type="button" data-action=${'FED-02.author.' + c.id} onClick=${() => a && app.nav.push('CLB-07', { id: a.id, clubId: post.clubId })} aria-label=${userName(a)}><${Avatar} user=${a} size=${32} /></button><div class="flex1 col gap2"><span class="row gap6 wrap"><span class="t-label-l c-heading">${userName(a)}</span>${role && role !== 'member' ? html`<${RoleBadge} role=${role} />` : null}<span class="t-caption">${app.fmt.rel(c.createdAt)}</span></span><p class="t-body-m break">${c.text}</p></div><${IconButton} small icon="more-horizontal" label=${t('a11y.more')} action=${'FED-02.commentMenu.' + c.id} onClick=${() => commentMenu(c)} /></div>`; })}</div>` : html`<p class="t-body-s c-muted center" style="padding:16px">${t('post.noComments')}</p>`}</div></${Scroll}>
      ${advisor ? html`<${Banner} kind="readonly" text=${t('post.advisorNoComment')} />` : html`<div class="ctabar" style="align-items:flex-end;gap:8px"><${Avatar} user=${app.me()} size=${36} /><div class="flex1"><${Input} multiline rows=${1} value=${text} onInput=${(v) => setText(v.slice(0, 500))} maxLength=${500} counter=${400} placeholder=${t('post.writeComment')} action="FED-02.commentInput" ariaLabel=${t('post.writeComment')} /></div><${IconButton} icon="send" label=${t('common.send')} brand action="FED-02.sendComment" disabled=${!text.trim() || busy} onClick=${send} onDisabledClick=${() => {}} /></div>`}`;
  } };

  /* FED-03 compose */
  S['FED-03'] = { tab: 'clubs', title: 'compose.title', comp: function Compose({ params }) {
    const u = app.uid(); const editing = params.edit ? sel().post(params.edit) : null; const clubId = params.clubId || (editing && editing.clubId); const club = sel().club(clubId); const draft = app.state.ui.drafts[clubId];
    const init = () => editing ? { type: editing.type, text: editing.text, title: editing.title || '', images: editing.images, pinned: editing.pinned, push: editing.pushSent, options: editing.poll ? editing.poll.options.map((o) => o.text) : ['', ''], duration: 3, showAfterVote: true, errors: {}, dirty: false, preview: false } : { type: 'post', text: '', title: '', images: [], pinned: false, push: true, options: ['', ''], duration: 3, showAfterVote: true, errors: {}, dirty: false, preview: false, ...(draft || {}) };
    const [f, set, reset] = useForm('compose-' + clubId + (params.edit || ''), init); const [busy, run] = useBusy(); const [menu, setMenu] = useState(false);
    const upd = (p) => set({ ...p, dirty: true }); const used = sel().dailyAnnouncements(clubId); const limitReached = used >= 2;
    if (!club || !(sel().isManager(clubId, u) || sel().isSuper(u))) return html`<${AppBar} onBack=${() => app.nav.back()} backAction="FED-03.back" title=${t('compose.title')} /><div class="empty"><${GU.Illustration} name="locked" /><p class="t-body-s c-sec">${t('compose.noAccess')}</p></div>`;
    const valid = f.type === 'poll' ? f.text.trim() && f.options.filter((o) => o.trim()).length >= 2 : f.type === 'announcement' ? f.title.trim() && f.text.trim() : f.text.trim();
    const validate = () => { const e = {}; if (!f.text.trim()) e.text = t('auth.err.required'); if (f.type === 'announcement' && !f.title.trim()) e.title = t('auth.err.required'); if (f.type === 'poll') { const opts = f.options.map((o) => o.trim()); if (opts.filter(Boolean).length < 2) e.options = t('compose.err.minOptions'); else if (new Set(opts.filter(Boolean)).size !== opts.filter(Boolean).length) e.options = t('compose.err.dupOptions'); } set({ errors: e }); return !Object.keys(e).length; };
    const close = () => { if (f.dirty) app.openDialog('DLG-25', { onSave: () => { saveDraft(); app.closeDialog(); reset(); app.nav.back(); }, onDiscard: () => { app.closeDialog(); reset(); app.nav.back(); }, onKeep: () => app.closeDialog() }); else { reset(); app.nav.back(); } };
    const saveDraft = () => { app.dispatch('ui.set', { drafts: { ...app.state.ui.drafts, [clubId]: { ...f, dirty: false, errors: {}, preview: false } } }); app.toast('TST-13'); };
    const doPublish = (push) => run(async () => { if (!app.guard(clubId)) return; await app.api(); const poll = f.type === 'poll' ? { options: f.options.filter((o) => o.trim()).map((o, i) => ({ id: 'o' + (i + 1), text: o.trim(), votes: [] })), endsAt: Date.now() + f.duration * GU.DAY, showResultsAfterVote: f.showAfterVote } : null;
      let id; if (editing) { app.dispatch('post.update', { postId: editing.id, patch: { text: f.text.trim(), title: f.type === 'announcement' ? f.title.trim() : null, images: f.images, pinned: f.pinned, type: f.type, poll: poll || editing.poll } }); id = editing.id; } else id = app.dispatch('post.create', { clubId, authorId: u, type: f.type, title: f.type === 'announcement' ? f.title.trim() : null, text: f.text.trim(), images: f.type === 'post' ? f.images : [], poll, pinned: f.type === 'post' ? f.pinned : f.type === 'announcement' ? f.pinned : false, push: f.type === 'announcement' && push });
      const drafts = { ...app.state.ui.drafts }; delete drafts[clubId]; app.dispatch('ui.set', { drafts }); reset();
      app.nav.popTo('CLB-03'); app.nav.replace('CLB-03', { id: clubId, tab: 'posts', highlight: id }); app.toast('TST-14', { action: () => app.nav.push('FED-02', { clubId, postId: id }) }); });
    const publish = () => { if (!validate()) return; if (f.type === 'announcement' && f.push && limitReached) { app.openDialog('DLG-24', { onPublishSilent: () => { app.closeDialog(); doPublish(false); } }); return; } doPublish(f.push); };
    const authorPreview = { id: 'preview', clubId, authorId: u, type: f.type, title: f.title, text: f.text || '…', images: f.images, poll: f.type === 'poll' ? { options: f.options.filter(Boolean).map((o, i) => ({ id: 'o' + i, text: o, votes: [] })), endsAt: Date.now() + f.duration * GU.DAY, showResultsAfterVote: true } : null, pinned: f.pinned, createdAt: Date.now(), likes: [], commentIds: [], pushSent: f.push };
    return html`<${AppBar} onBack=${close} backAction="FED-03.close" closeIcon title=${editing ? t('compose.editTitle') : t('compose.title')}><${IconButton} icon="more-vertical" label=${t('a11y.more')} action="FED-03.menu" onClick=${() => setMenu(true)} /><${Button} size="sm" label=${editing ? t('common.save') : t('compose.publish')} loading=${busy} disabled=${!valid} action="FED-03.publish" onClick=${publish} onDisabledClick=${validate} /></${AppBar}>
      ${menu ? html`<${PopMenu} id="FED-03" onClose=${() => setMenu(false)}><${Tile} title=${t('compose.saveDraft')} leading=${html`<${Icon} name="file-text" size=${20} />`} action="FED-03.saveDraft" onClick=${() => { setMenu(false); saveDraft(); }} /><${Tile} title=${f.preview ? t('compose.edit') : t('compose.preview')} leading=${html`<${Icon} name="eye" size=${20} />`} action="FED-03.preview" onClick=${() => { setMenu(false); set({ preview: !f.preview }); }} /><${Tile} title=${t('compose.clear')} leading=${html`<${Icon} name="trash-2" size=${20} />`} danger action="FED-03.clear" onClick=${() => { setMenu(false); set({ text: '', title: '', images: [], options: ['', ''], errors: {}, dirty: true }); }} /></${PopMenu}>` : null}
      <${Scroll} routeKey=${'compose-' + clubId}><div class="col gap16 px16 pt8 pb24">
        ${f.preview ? html`<${Banner} kind="info" icon="eye" text=${t('compose.previewNote')} actionLabel=${t('compose.edit')} action="FED-03.preview" onAction=${() => set({ preview: false })} /><${PostCard} post=${authorPreview} screen="FED-03" hideActions />` : html`
        <${Segmented} options=${[{ id: 'post', label: t('feed.type.post'), icon: 'file-text' }, { id: 'announcement', label: t('feed.type.announcement'), icon: 'megaphone' }, { id: 'poll', label: t('feed.type.poll'), icon: 'chart-column' }]} value=${f.type} onChange=${(v) => upd({ type: v, errors: {} })} action="FED-03.type" />
        <div class="row gap10"><${Avatar} user=${app.me()} size=${36} /><div class="flex1 col"><span class="t-label-l c-heading">${app.me().name}</span>${sel().managedClubs(u).length > 1 ? html`<button type="button" class="t-caption c-brand row gap4" data-action="FED-03.switchClub" onClick=${() => app.openSheet('SHT-18', { onSelect: (cid) => { app.closeSheet(); app.nav.replace('FED-03', { clubId: cid }); } })}>${club.name} <${Icon} name="chevron-down" size=${12} /></button>` : html`<span class="t-caption">${club.name}</span>`}</div></div>
        ${f.type === 'announcement' ? html`<${Input} label=${t('compose.announcementTitle')} value=${f.title} onInput=${(v) => upd({ title: v.slice(0, 80) })} maxLength=${80} counter error=${f.errors.title} action="FED-03.title" />` : null}
        <${Input} label=${f.type === 'poll' ? t('compose.question') : t('compose.text')} multiline rows=${f.type === 'poll' ? 2 : 5} value=${f.text} onInput=${(v) => upd({ text: v.slice(0, 1000) })} maxLength=${1000} counter error=${f.errors.text} action="FED-03.text" placeholder=${t('feed.composePlaceholder')} autofocus />
        ${f.type === 'post' ? html`<div class="col gap8"><div class="row between"><span class="field-label">${t('compose.images')} (${f.images.length}/4)</span><${Button} size="sm" variant="tonal" icon="image" label=${t('compose.addImage')} disabled=${f.images.length >= 4} action="FED-03.addImage" onClick=${() => app.openSheet('SHT-16', { multi: true, max: 4 - f.images.length, onPick: (seeds) => upd({ images: [...f.images, ...seeds].slice(0, 4) }) })} onDisabledClick=${() => app.toast('TST-X5')} /></div>${f.images.length ? html`<div class="row gap8 wrap">${f.images.map((s, i) => html`<div key=${s} class="rel" style="width:72px;height:72px;border-radius:12px;overflow:hidden"><div style="position:absolute;inset:0" dangerouslySetInnerHTML=${{ __html: GU.coverArtSVG(s, club.iconName, club.palette, undefined, { w: 200, h: 200 }) }} /><button type="button" class="iconbtn is-sm on-cover" style="position:absolute;right:2px;top:2px;width:28px;height:28px" aria-label=${t('common.remove')} data-action=${'FED-03.removeImage.' + i} onClick=${() => upd({ images: f.images.filter((_, k) => k !== i) })}><${Icon} name="x" size=${14} /></button></div>`)}</div>` : null}</div>
          <div class="row between"><span class="t-body-m">${t('compose.pin')}</span><${Switch} checked=${f.pinned} onChange=${(v) => upd({ pinned: v })} action="FED-03.pin" label=${t('compose.pin')} /></div>` : null}
        ${f.type === 'announcement' ? html`<div class="row between"><div class="col"><span class="t-body-m">${t('compose.pushToggle')}</span><span class="t-caption">${limitReached ? t('compose.limitReached') : t('compose.pushHelp')}</span></div><${Switch} checked=${f.push && !limitReached} onChange=${(v) => upd({ push: v })} action="FED-03.pushToggle" label=${t('compose.pushToggle')} disabled=${limitReached} onDisabledClick=${() => app.openDialog('DLG-24', { onPublishSilent: () => app.closeDialog() })} /></div>
          <div class="col gap6"><div class="row between t-caption"><span>${t('compose.dailyQuota')}</span><span class="tnum">${used}/2</span></div><${Progress} value=${used} max=${2} kind=${limitReached ? 'warning' : undefined} label=${t('compose.dailyQuota')} /></div>
          <div class="row between"><span class="t-body-m">${t('compose.pin')}</span><${Switch} checked=${f.pinned} onChange=${(v) => upd({ pinned: v })} action="FED-03.pin" label=${t('compose.pin')} /></div>
          <div class="col gap6"><span class="field-label">${t('compose.notifPreview')}</span><div class="card card-body row gap12" style="border-radius:16px"><span class="emblem is-xs"><${GU.Logo} size=${20} /></span><div class="flex1 col gap2"><span class="row between"><span class="t-label-m c-heading">${club.name}</span><span class="t-caption">${t('time.justNow')}</span></span><span class="t-label-l c-heading ellipsis">${f.title || t('compose.announcementTitle')}</span><span class="t-body-s c-sec clamp2">${f.text || t('compose.text')}</span></div></div></div>` : null}
        ${f.type === 'poll' ? html`<div class="col gap8"><span class="field-label">${t('compose.options')}</span>${f.options.map((o, i) => html`<div key=${i} class="row gap8"><div class="flex1"><${Input} value=${o} onInput=${(v) => upd({ options: f.options.map((x, k) => (k === i ? v.slice(0, 60) : x)) })} placeholder=${t('compose.optionN', { n: i + 1 })} action=${'FED-03.option.' + i} ariaLabel=${t('compose.optionN', { n: i + 1 })} /></div>${f.options.length > 2 ? html`<${IconButton} icon="trash-2" label=${t('common.remove')} action=${'FED-03.removeOption.' + i} onClick=${() => upd({ options: f.options.filter((_, k) => k !== i) })} />` : null}</div>`)}${f.errors.options ? html`<div class="field-help is-error" role="alert"><${Icon} name="triangle-alert" size=${14} /><span>${f.errors.options}</span></div>` : null}${f.options.length < 4 ? html`<${Button} size="sm" variant="text" icon="plus" label=${t('compose.addOption')} action="FED-03.addOption" onClick=${() => upd({ options: [...f.options, ''] })} />` : null}</div>
          <div class="col gap6"><span class="field-label">${t('compose.duration')}</span><${Segmented} options=${[1, 3, 7].map((d) => ({ id: String(d), label: t('time.days', { count: d }) }))} value=${String(f.duration)} onChange=${(v) => upd({ duration: Number(v) })} action="FED-03.duration" /></div>
          <div class="row between"><span class="t-body-m">${t('compose.showAfterVote')}</span><${Switch} checked=${f.showAfterVote} onChange=${(v) => upd({ showAfterVote: v })} action="FED-03.showAfterVote" label=${t('compose.showAfterVote')} /></div>` : null}`}
      </div></${Scroll}>`;
  } };
})();
