/* ===== SCREENS: MGT (club management) ===== */
(function () {
  const { html, cx, Icon, app, useState, useEffect, useRef, useForm, useBusy, Button, IconButton, Input, Picker, Switch, Chip, Segmented, Tabs, Badge, RoleBadge, StatusBadge, Card, Tile, AppBar, Banner, Scroll, Cover, Avatar, EmptyState, ListState, SectionTitle, ListEnd, StickyCTA, Progress, KPI, Quick, MiniLineChart, Stepbar, Checkbox, PopMenu, UserRow, MemberRow, ApplicationRow, EventCard, placeName, deptYear, userName, EVENT_TYPES, PLACES, DAY, startOfDay, today0, dayKey, downloadText } = GU;
  const t = (k, p) => app.t(k, p); const S = GU.SCREENS; const sel = () => app.sel;

  function useMgt(params) { const u = app.uid(); const club = sel().club(params.clubId); const readOnly = club ? sel().isAdvisor(club.id, u) : false; const allowed = club && (sel().isManager(club.id, u) || sel().isSuper(u) || readOnly); return { u, club, readOnly, allowed, guard: () => app.guard(club && club.id) }; }
  function MgtHeader({ club, title, screen, children, back }) {
    const u = app.uid(); const managed = sel().managedClubs(u); const role = sel().roleIn(club.id, u) || (sel().isSuper(u) ? 'superadmin' : 'member');
    return html`<${AppBar} onBack=${back || (() => app.nav.back())} backAction=${screen + '.back'} titleNode=${html`<div class="col"><span class="t-caption">${title}</span>${managed.length > 1 ? html`<button type="button" class="row gap4 t-title-s" style="text-align:left" data-action=${screen + '.switchClub'} onClick=${() => app.openSheet('SHT-18')} aria-haspopup="dialog"><span class="ellipsis" style="max-width:190px">${club.name}</span><${Icon} name="chevron-down" size=${16} /></button>` : html`<span class="t-title-s ellipsis">${club.name}</span>`}</div>`}><${RoleBadge} role=${role} />${children}</${AppBar}>`;
  }
  function NoAccess({ screen }) { return html`<${AppBar} onBack=${() => app.nav.back()} backAction=${screen + '.back'} title="" /><div class="empty"><${GU.Illustration} name="locked" /><p class="t-body-s c-sec">${t('mgt.noAccess')}</p></div>`; }
  const ROBanner = ({ readOnly }) => (readOnly ? html`<${Banner} kind="readonly" text=${t('mgt.readOnlyBanner')} />` : null);
  GU.MgtHeader = MgtHeader;

  /* MGT-01 */
  S['MGT-01'] = { tab: 'clubs', title: 'mgt.title', comp: function Panel({ params, route }) {
    const { u, club, readOnly, allowed } = useMgt(params); if (!allowed) return html`<${NoAccess} screen="MGT-01" />`;
    const k = sel().kpis(club.id); const growth = sel().memberGrowth(club.id); const used = sel().dailyAnnouncements(club.id); const upcoming = sel().clubEvents(club.id).filter((e) => e.status === 'published' && e.startsAt > Date.now()).sort((a, b) => a.startsAt - b.startsAt).slice(0, 2); const acts = sel().activityOf(club.id).slice(0, 5); const members = sel().clubMembers(club.id).filter((m) => m.role === 'member');
    const ro = () => app.toast('TST-26'); const go = (s, p) => () => app.nav.push(s, { clubId: club.id, ...(p || {}) }); const write = (fn) => (readOnly ? ro : fn);
    const labels = growth.map((_, i) => t('mgt.weekN', { n: i - 7 }));
    return html`<${MgtHeader} club=${club} title=${t('mgt.title')} screen="MGT-01" /><${ROBanner} readOnly=${readOnly} />
      <${Scroll} routeKey=${route.key}><div class="col gap20 px16 pb24">
        ${!members.length && !readOnly ? html`<${Card} muted class="card-body col gap8" style="align-items:center;text-align:center"><${GU.Illustration} name="empty-clubs" size=${80} /><span class="t-title-s">${t('mgt.newClub.title')}</span><span class="t-body-s c-sec">${t('mgt.newClub.desc')}</span><${Button} size="sm" icon="share-2" label=${t('common.share')} action="MGT-01.share" onClick=${() => app.openSheet('SHT-15', { type: 'club', id: club.id })} /></${Card}>` : null}
        <div class="grid2"><${KPI} label=${t('mgt.kpi.members')} value=${k.members} sub=${t('mgt.kpi.newThisMonth', { count: k.newMembers })} icon="users" action="MGT-01.kpi.members" onClick=${go('MGT-03')} /><${KPI} label=${t('mgt.kpi.pending')} value=${k.pending} accent icon="user-plus" action="MGT-01.kpi.pending" onClick=${go('MGT-02')} /><${KPI} label=${t('mgt.kpi.events')} value=${k.upcoming} icon="calendar" action="MGT-01.kpi.events" onClick=${go('MGT-04')} /><${KPI} label=${t('mgt.kpi.announcements')} value=${k.announcements} icon="megaphone" action="MGT-01.kpi.announcements" onClick=${go('MGT-08', { tab: 'announcements' })} /></div>
        <div class="col gap8"><h2 class="t-title-s">${t('mgt.quick.title')}</h2><div class="grid3"><${Quick} icon="pencil" label=${t('mgt.quick.post')} action="MGT-01.quick.post" onClick=${write(() => app.nav.push('FED-03', { clubId: club.id }))} /><${Quick} icon="megaphone" label=${t('mgt.quick.announce')} action="MGT-01.quick.announce" onClick=${write(() => { app.forms['compose-' + club.id] = { ...(app.forms['compose-' + club.id] || {}), type: 'announcement' }; app.nav.push('FED-03', { clubId: club.id }); })} /><${Quick} icon="calendar-plus" label=${t('mgt.quick.event')} action="MGT-01.quick.event" onClick=${write(go('MGT-05'))} /><${Quick} icon="scan-line" label=${t('mgt.quick.attendance')} action="MGT-01.quick.attendance" onClick=${() => { const ev = upcoming[0] || sel().clubEvents(club.id).find((e) => e.status === 'published'); ev ? app.nav.push('MGT-06', { clubId: club.id, eventId: ev.id }) : app.toast('TST-X12'); }} /><${Quick} icon="users" label=${t('mgt.quick.members')} action="MGT-01.quick.members" onClick=${go('MGT-03')} /><${Quick} icon="settings" label=${t('mgt.quick.settings')} action="MGT-01.quick.settings" onClick=${go('MGT-09')} /></div></div>
        <${Card} class="card-body col gap8"><div class="row between"><span class="t-label-l c-heading">${t('mgt.growth')}</span><span class="t-caption">${t('mgt.weeks8')}</span></div><${MiniLineChart} data=${growth} labels=${labels} action="MGT-01.chart.point" /></${Card}>
        <${Card} class="card-body col gap8"><div class="row between"><span class="t-label-l c-heading">${t('compose.dailyQuota')}</span><span class="t-caption tnum">${used}/2</span></div><${Progress} value=${used} max=${2} kind=${used >= 2 ? 'warning' : undefined} label=${t('compose.dailyQuota')} /><span class="t-caption">${used >= 2 ? t('compose.limitReached') : t('mgt.quotaLeft', { count: 2 - used })}</span></${Card}>
        <div class="col gap8"><div class="row between"><h2 class="t-title-s">${t('mgt.upcoming')}</h2><${Button} size="sm" variant="text" label=${t('common.all')} action="MGT-01.eventsAll" onClick=${go('MGT-04')} /></div>${upcoming.length ? upcoming.map((e) => html`<${Card} key=${e.id} tappable action=${'MGT-01.event.' + e.id} onClick=${() => app.nav.push('MGT-06', { clubId: club.id, eventId: e.id })} label=${e.title}><div class="row gap12" style="padding:12px 16px"><${GU.DateBadge} ts=${e.startsAt} /><div class="flex1 col gap2"><span class="t-title-s ellipsis">${e.title}</span><span class="t-caption">${app.fmt.time(e.startsAt)} · ${placeName(e)}</span><span class="row gap8"><${Progress} value=${sel().registered(e.id).length} max=${e.capacity || 1} thin label=${t('event.capacity')} /><span class="t-caption tnum">${sel().registered(e.id).length}${e.capacity != null ? '/' + e.capacity : ''}</span></span></div><${Icon} name="chevron-right" size=${20} class="c-muted" /></div></${Card}>`) : html`<p class="t-body-s c-muted">${t('mgt.noUpcoming')}</p>`}</div>
        <div class="col gap8"><div class="row between"><h2 class="t-title-s">${t('mgt.recent')}</h2><${Button} size="sm" variant="text" label=${t('common.all')} action="MGT-01.activityAll" onClick=${go('MGT-10')} /></div><${Card}>${acts.map((a, i) => html`${i ? html`<div class="divider" />` : null}<${ActivityRow} key=${a.id} a=${a} screen="MGT-01" club=${club} />`)}${!acts.length ? html`<p class="t-body-s c-muted p16">${t('activity.empty')}</p>` : null}</${Card}></div>
      </div></${Scroll}>`;
  } };
  const ACT_ICON = { application_received: 'user-plus', application_approved: 'user-check', application_rejected: 'user-x', member_joined: 'user-plus', member_left: 'log-out', member_removed: 'user-x', role_changed: 'user-cog', event_published: 'calendar-plus', event_cancelled: 'calendar-x', post_created: 'file-text', announcement: 'megaphone', poll: 'chart-column', settings_changed: 'settings' };
  const ACT_CAT = { application_received: 'membership', application_approved: 'membership', application_rejected: 'membership', member_joined: 'membership', member_left: 'membership', member_removed: 'membership', role_changed: 'membership', event_published: 'event', event_cancelled: 'event', post_created: 'content', announcement: 'content', poll: 'content', settings_changed: 'settings' };
  function ActivityRow({ a, screen, club }) {
    const actor = sel().user(a.actorId); const target = a.refs.userId ? sel().user(a.refs.userId) : null; const ev = a.refs.eventId ? sel().event(a.refs.eventId) : null; const post = a.refs.postId ? sel().post(a.refs.postId) : null;
    const text = t('activity.' + a.kind, { actor: userName(actor), user: userName(target), event: ev ? ev.title : '', role: a.refs.role ? t('role.' + a.refs.role) : '' });
    const go = () => { if (ev) app.nav.push('EVT-02', { id: ev.id }); else if (post) app.nav.push('FED-02', { clubId: club.id, postId: post.id }); else if (a.kind.startsWith('application')) app.nav.push('MGT-02', { clubId: club.id }); else if (target) app.nav.push('CLB-07', { id: target.id, clubId: club.id }); else app.nav.push('MGT-09', { clubId: club.id }); };
    return html`<${Tile} inCard leading=${html`<${Avatar} user=${actor} size=${36} />`} title=${html`<span class="t-body-s c-heading" dangerouslySetInnerHTML=${{ __html: GU.escapeHtml(text).replace(GU.escapeHtml(userName(actor)), `<b>${GU.escapeHtml(userName(actor))}</b>`) }} />`} subtitle=${app.fmt.rel(a.createdAt)} trailing=${html`<${Icon} name=${ACT_ICON[a.kind] || 'info'} size=${18} />`} action=${`${screen}.row.${a.id}`} onClick=${go} />`;
  }
  GU.ActivityRow = ActivityRow; GU.ACT_CAT = ACT_CAT;

  /* MGT-02 applications */
  S['MGT-02'] = { tab: 'clubs', title: 'applications.title', comp: function Applications({ params, route }) {
    const { u, club, readOnly, allowed } = useMgt(params); const [tab, setTab] = useState(params.tab || 'pending'); const [q, setQ] = useState(''); const [desc, setDesc] = useState(true); const [selecting, setSelecting] = useState(false); const [selected, setSelected] = useState([]); const [leaving, setLeaving] = useState([]);
    if (!allowed) return html`<${NoAccess} screen="MGT-02" />`;
    const pending = sel().pendingApps(club.id); const list = (tab === 'pending' ? pending : tab === 'approved' ? sel().approvedApps(club.id) : sel().rejectedApps(club.id)).filter((m) => !q || m.user.name.toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))).sort((a, b) => (desc ? 1 : -1) * ((b.appliedAt || 0) - (a.appliedAt || 0)));
    const stale = (m) => { if (m.stale) { app.openDialog('DLG-18', { result: t('status.rejected'), onOk: () => { app.dispatch('membership.reject', { clubId: club.id, userId: m.userId, actorId: 'u_other', reason: 'quota' }); } }); return true; } return false; };
    const approve = (m) => { if (!app.guard(club.id)) return; if (stale(m)) return; const snap = app.store.get(); setLeaving((l) => [...l, m.userId]); setTimeout(() => { setLeaving((l) => l.filter((x) => x !== m.userId)); app.dispatch('membership.approve', { clubId: club.id, userId: m.userId, actorId: u }); app.toast('TST-27', { name: m.user.name, undo: () => app.store.restore(snap) }); }, 250); };
    const reject = (m) => { if (!app.guard(club.id)) return; if (stale(m)) return; app.openSheet('SHT-20', { clubId: club.id, userId: m.userId }); };
    const bulk = (kind) => { if (!app.guard(club.id)) return; app.openDialog('DLG-17', { kind, count: selected.length, onConfirm: () => { const snap = app.store.get(); selected.forEach((uid) => app.dispatch(kind === 'approve' ? 'membership.approve' : 'membership.reject', { clubId: club.id, userId: uid, actorId: u, reason: kind === 'reject' ? 'quota' : undefined })); app.closeDialog(); app.toast(kind === 'approve' ? 'TST-27' : 'TST-28', { name: t('applications.nApplicants', { count: selected.length }), undo: () => app.store.restore(snap) }); setSelected([]); setSelecting(false); } }); };
    const toggleSel = (id) => { setSelecting(true); setSelected((s) => (s.includes(id) ? s.filter((x) => x !== id) : [...s, id])); };
    return html`${selecting ? html`<${AppBar} onBack=${() => { setSelecting(false); setSelected([]); }} backAction="MGT-02.cancelSelect" closeIcon title=${t('applications.selected', { count: selected.length })}><${Button} size="sm" variant="text" label=${t('applications.selectAll')} action="MGT-02.selectAll" onClick=${() => setSelected(list.map((m) => m.userId))} /><${IconButton} icon="check" label=${t('applications.approve')} action="MGT-02.bulkApprove" disabled=${!selected.length} onClick=${() => bulk('approve')} style=${{ color: 'var(--state-success)' }} /><${IconButton} icon="x" label=${t('applications.reject')} action="MGT-02.bulkReject" disabled=${!selected.length} onClick=${() => bulk('reject')} style=${{ color: 'var(--state-danger)' }} /></${AppBar}>` : html`<${MgtHeader} club=${club} title=${t('applications.title')} screen="MGT-02"><${IconButton} icon="arrow-up-down" label=${t('common.sort')} action="MGT-02.sort" onClick=${() => setDesc(!desc)} /></${MgtHeader}>`}
      <${ROBanner} readOnly=${readOnly} />
      ${!club.applicationsOpen ? html`<${Banner} kind="info" icon="lock" text=${t('applications.closedBanner')}><span style="margin-left:8px;display:inline-flex;vertical-align:middle"><${Switch} checked=${false} onChange=${() => { if (!app.guard(club.id)) return; app.dispatch('club.update', { clubId: club.id, patch: { applicationsOpen: true }, actorId: u }); app.toast('TST-54', { open: true }); }} action="MGT-02.toggleOpen" label=${t('applications.openToggle')} /></span></${Banner}>` : null}
      <${Tabs} tabs=${[{ id: 'pending', label: t('applications.tab.pending'), count: pending.length || undefined }, { id: 'approved', label: t('applications.tab.approved') }, { id: 'rejected', label: t('applications.tab.rejected') }]} value=${tab} onChange=${(v) => { setTab(v); setSelecting(false); setSelected([]); }} action="MGT-02.tab" />
      <div class="px16 py8"><${Input} icon="search" placeholder=${t('members.search')} value=${q} onInput=${setQ} action="MGT-02.search" ariaLabel=${t('members.search')} /></div>
      <${Scroll} routeKey=${route.key}><${ListState} n=${5} emptyProps=${{ illustration: 'empty-applications', title: t('applications.empty.' + tab) }}>${list.length ? html`${tab === 'pending' ? html`<p class="t-caption px16 pb16">${t('applications.hint')}</p>` : null}<div class="col">${list.map((m) => tab === 'pending' ? html`<div key=${m.userId} style=${{ transition: 'opacity .25s, transform .25s', opacity: leaving.includes(m.userId) ? 0 : 1, transform: leaving.includes(m.userId) ? 'translateX(40px)' : 'none' }}><${ApplicationRow} m=${m} selecting=${selecting} selected=${selected.includes(m.userId)} onSelect=${() => toggleSel(m.userId)} onApprove=${() => approve(m)} onReject=${() => reject(m)} onOpen=${() => (selecting ? toggleSel(m.userId) : app.openSheet('SHT-19', { clubId: club.id, userId: m.userId }))} readOnly=${readOnly} /></div>` : html`<${Tile} key=${m.userId} leading=${html`<${Avatar} user=${m.user} size=${40} />`} title=${m.user.name} subtitle=${`${deptYear(m.user)} · ${app.fmt.date(m.decidedAt)}`} sub2=${tab === 'rejected' && m.rejectReason ? t('rejectReason.' + m.rejectReason) : null} trailing=${html`<${StatusBadge} status=${tab === 'approved' ? 'approved' : 'rejected'} />`} action=${'MGT-02.row.' + m.userId} onClick=${() => app.openSheet('SHT-19', { clubId: club.id, userId: m.userId })} />`)}</div><${ListEnd} />` : html`<${EmptyState} illustration="empty-applications" title=${t('applications.empty.' + tab)} />`}</${ListState}></${Scroll}>`;
  } };

  /* MGT-03 members */
  S['MGT-03'] = { tab: 'clubs', title: 'mgtMembers.title', comp: function MgtMembers({ params, route }) {
    const { u, club, readOnly, allowed } = useMgt(params); const [q, setQ] = useState(''); const [role, setRole] = useState('all'); const [sort, setSort] = useState('name'); const [menu, setMenu] = useState(null);
    if (!allowed) return html`<${NoAccess} screen="MGT-03" />`;
    const isPres = sel().isPresident(club.id, u) || sel().isSuper(u);
    const list = sel().clubMembers(club.id).filter((m) => !q || m.user.name.toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))).filter((m) => role === 'all' || m.role === role).sort((a, b) => sort === 'name' ? a.user.name.localeCompare(b.user.name, 'tr') : sort === 'joined' ? (b.decidedAt || 0) - (a.decidedAt || 0) : (sel().attendanceRate(club.id, b.userId) || 0) - (sel().attendanceRate(club.id, a.userId) || 0));
    const exportCsv = () => { const rows = [['ad', 'eposta', 'bolum', 'sinif', 'rol', 'katilim_tarihi']].concat(list.map((m) => [m.user.name, m.user.email, m.user.department ? t('dept.' + m.user.department) : '', m.user.year ? t('year.' + m.user.year) : '', t('role.' + m.role), m.decidedAt ? new Date(m.decidedAt).toISOString().slice(0, 10) : ''])); downloadText('\ufeff' + rows.map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(';')).join('\n'), 'uyeler.csv', 'text/csv;charset=utf-8'); app.toast('TST-29'); };
    return html`<${MgtHeader} club=${club} title=${t('mgtMembers.title')} screen="MGT-03"><${IconButton} icon="more-vertical" label=${t('a11y.more')} action="MGT-03.menu" onClick=${() => setMenu('top')} /></${MgtHeader}><${ROBanner} readOnly=${readOnly} />
      <div class="px16 py8"><${Input} icon="search" placeholder=${t('members.search')} value=${q} onInput=${setQ} action="MGT-03.search" ariaLabel=${t('members.search')} /></div>
      <div class="hscroll pb16">${['all', 'president', 'board', 'advisor', 'member'].map((r) => html`<${Chip} key=${r} label=${r === 'all' ? t('common.all') : t('role.' + r)} selected=${role === r} action=${'MGT-03.filter.' + r} onClick=${() => setRole(r)} />`)}</div>
      <div class="row between px16 pb16"><span class="t-label-l c-sec tnum">${t('members.total', { count: list.length })}</span><${Button} size="sm" variant="outline" icon="arrow-up-down" label=${t('mgtMembers.sort.' + sort)} action="MGT-03.sort" onClick=${() => setMenu('sort')} /></div>
      <${Scroll} routeKey=${route.key}><${ListState} n=${6} emptyProps=${{ illustration: 'empty-clubs', title: t('members.noResults') }}>${list.length ? html`<div class="col">${list.map((m) => html`<${MemberRow} key=${m.userId} m=${m} screen="MGT-03" clubId=${club.id} showRate sub=${t('mgtMembers.since', { date: app.fmt.monthYear(m.decidedAt || m.appliedAt || Date.now()) })} onMenu=${m.role !== 'president' && m.role !== 'advisor' && !readOnly ? () => app.openSheet('SHT-21', { clubId: club.id, userId: m.userId }) : null} />`)}</div>
        ${isPres ? html`<div class="px16 pt16"><${Card} class="card-body col gap8"><span class="t-label-l c-heading row gap6"><${Icon} name="crown" size=${18} class="c-brand" />${t('mgtMembers.transferTitle')}</span><span class="t-body-s c-sec">${t('mgtMembers.transferDesc')}</span><${Button} variant="outline" label=${t('mgtMembers.transfer')} action="MGT-03.transfer" onClick=${() => app.openSheet('SHT-25', { mode: 'transfer', clubId: club.id, onSelect: (uid) => { app.closeSheet(); app.openDialog('DLG-21', { clubId: club.id, userId: uid }); } })} /></${Card}></div>` : null}<${ListEnd} />` : html`<${EmptyState} illustration="empty-clubs" title=${t('members.noResults')} />`}</${ListState}></${Scroll}>
      ${menu === 'top' ? html`<${PopMenu} id="MGT-03" onClose=${() => setMenu(null)}><${Tile} title=${t('mgtMembers.export')} leading=${html`<${Icon} name="download" size=${20} />`} action="MGT-03.export" onClick=${() => { setMenu(null); exportCsv(); }} /></${PopMenu}>` : null}
      ${menu === 'sort' ? html`<${PopMenu} id="MGT-03" onClose=${() => setMenu(null)}>${['name', 'joined', 'rate'].map((s) => html`<${Tile} key=${s} title=${t('mgtMembers.sort.' + s)} trailing=${sort === s ? html`<${Icon} name="check" size=${18} class="c-brand" />` : null} action=${'MGT-03.sort.' + s} onClick=${() => { setSort(s); setMenu(null); }} />`)}</${PopMenu}>` : null}`;
  } };

  /* MGT-04 events */
  S['MGT-04'] = { tab: 'clubs', title: 'mgtEvents.title', comp: function MgtEvents({ params, route }) {
    const { u, club, readOnly, allowed } = useMgt(params); const [tab, setTab] = useState(params.tab || 'published'); if (!allowed) return html`<${NoAccess} screen="MGT-04" />`;
    const evs = sel().clubEvents(club.id).filter((e) => tab === 'draft' ? e.status === 'draft' : tab === 'published' ? e.status === 'published' && e.endsAt >= Date.now() : tab === 'past' ? e.status === 'published' && e.endsAt < Date.now() : e.status === 'cancelled').sort((a, b) => (tab === 'past' ? b.startsAt - a.startsAt : a.startsAt - b.startsAt));
    return html`<${MgtHeader} club=${club} title=${t('mgtEvents.title')} screen="MGT-04" /><${ROBanner} readOnly=${readOnly} /><div class="px16 pb16"><${Segmented} options=${[{ id: 'draft', label: t('status.draft') }, { id: 'published', label: t('status.published') }, { id: 'past', label: t('event.past') }, { id: 'cancelled', label: t('status.cancelled') }]} value=${tab} onChange=${setTab} action="MGT-04.tab" /></div>
      <${Scroll} routeKey=${route.key}><${ListState} n=${4} emptyProps=${{ illustration: 'empty-events', title: t('mgtEvents.empty.' + tab) }}>${evs.length ? evs.map((e) => html`<${Tile} key=${e.id} leading=${html`<${GU.DateBadge} ts=${e.startsAt} />`} title=${e.title} subtitle=${`${app.fmt.dateTime(e.startsAt)} · ${e.capacity != null ? `${sel().registered(e.id).length}/${e.capacity}` : t('event.unlimited')}`} sub2=${html`<span class="row gap6"><${StatusBadge} status=${e.visibility === 'members' ? 'members' : e.status} label=${e.visibility === 'members' ? t('event.visibility.members') : undefined} />${e.visibility === 'members' ? html`<${StatusBadge} status=${e.status} />` : null}</span>`} action=${'MGT-04.event.' + e.id} onClick=${() => app.nav.push('EVT-02', { id: e.id })} trailing=${html`<${IconButton} icon="more-vertical" label=${t('a11y.more')} action=${'MGT-04.menu.' + e.id} onClick=${(ev) => { ev.stopPropagation(); app.openSheet('SHT-23', { eventId: e.id }); }} />`} />`) : html`<${EmptyState} illustration="empty-events" title=${t('mgtEvents.empty.' + tab)} cta=${readOnly ? null : t('mgtEvents.create')} ctaAction="MGT-04.create" onCta=${() => app.nav.push('MGT-05', { clubId: club.id })} />`}</${ListState}></${Scroll}>
      ${readOnly ? null : html`<button type="button" class="fab" data-action="MGT-04.create" onClick=${() => app.nav.push('MGT-05', { clubId: club.id })}><${Icon} name="plus" size=${22} />${t('mgtEvents.create')}</button>`}`;
  } };

  /* MGT-05 event form */
  S['MGT-05'] = { tab: 'clubs', title: 'eventForm.title', comp: function EventForm({ params }) {
    const { u, club, readOnly, allowed } = useMgt(params); const editing = params.eventId ? sel().event(params.eventId) : null;
    const init = () => editing ? { step: 1, title: editing.title, desc: editing.desc, type: editing.type, cover: { palette: editing.coverPalette, pattern: editing.coverPattern, seed: editing.coverSeed }, startsAt: editing.startsAt, endsAt: editing.endsAt, placeId: editing.placeId, placeText: editing.placeText, capacity: editing.capacity, unlimited: editing.capacity == null, visibility: editing.visibility, autoReminder: editing.autoReminder, errors: {}, dirty: false } : { step: 1, title: '', desc: '', type: 'sosyal', cover: { palette: club ? club.palette : 'red', pattern: 'mountain', seed: 'event-new-' + Date.now() }, startsAt: GU.at(7, 18, 0), endsAt: GU.at(7, 20, 0), placeId: null, placeText: null, capacity: 40, unlimited: false, visibility: 'public', autoReminder: true, errors: {}, dirty: false };
    const [f, set, reset] = useForm('eventForm-' + (params.eventId || params.clubId), init); const [busy, run] = useBusy();
    if (!allowed || readOnly) return html`<${NoAccess} screen="MGT-05" />`;
    const upd = (p) => set({ ...p, dirty: true }); const registered = editing ? sel().registered(editing.id).length : 0;
    const conflicts = sel().clubEvents(club.id).filter((e) => e.id !== (editing && editing.id) && e.status === 'published' && e.startsAt < f.endsAt && e.endsAt > f.startsAt).length;
    const validate = () => { const e = {}; if (f.step === 1) { if (!f.title.trim()) e.title = t('auth.err.required'); } if (f.step === 2) { if (f.startsAt < Date.now() && !editing) e.start = t('eventForm.err.future'); if (f.endsAt <= f.startsAt) e.end = t('eventForm.err.endAfter'); if (!f.placeId && !f.placeText) e.place = t('auth.err.required'); if (!f.unlimited && editing && editing.status === 'published' && f.capacity < registered) e.capacity = t('eventForm.err.capacity', { count: registered }); } set({ errors: e }); return !Object.keys(e).length; };
    const close = () => { if (f.dirty) app.openDialog('DLG-25', { onSave: () => { app.closeDialog(); saveDraft(); }, onDiscard: () => { app.closeDialog(); reset(); app.nav.back(); }, onKeep: () => app.closeDialog() }); else { reset(); app.nav.back(); } };
    const payload = () => ({ id: editing ? editing.id : undefined, clubId: club.id, title: f.title.trim(), desc: f.desc.trim(), type: f.type, startsAt: f.startsAt, endsAt: f.endsAt, placeId: f.placeId, placeText: f.placeText, capacity: f.unlimited ? null : f.capacity, visibility: f.visibility, autoReminder: f.autoReminder, coverPalette: f.cover.palette, coverPattern: f.cover.pattern, coverSeed: f.cover.seed, createdBy: editing ? editing.createdBy : u });
    const saveDraft = () => { if (!app.guard(club.id)) return; app.dispatch('event.save', { event: { ...payload(), status: editing ? editing.status : 'draft' } }); reset(); app.toast('TST-13'); app.nav.popTo('MGT-04') || app.nav.replace('MGT-04', { clubId: club.id, tab: 'draft' }); };
    const publish = () => { if (!app.guard(club.id)) return; const members = sel().clubMembers(club.id).length; app.openDialog('DLG-22', { count: members, onConfirm: (notifyMembers) => run(async () => { await app.api(); const id = app.dispatch('event.save', { event: payload() }); if (!editing || editing.status !== 'published') app.dispatch('event.publish', { eventId: id, notifyMembers, actorId: u }); app.closeDialog(); reset(); app.nav.popTo('MGT-04') || app.nav.replace('MGT-04', { clubId: club.id }); app.toast('TST-30', { action: () => app.nav.push('EVT-02', { id }) }); }) }); };
    const setDate = (key, ts) => { const cur = new Date(f[key]); const d = new Date(ts); d.setHours(cur.getHours(), cur.getMinutes(), 0, 0); const patch = { [key]: d.getTime() }; if (key === 'startsAt' && d.getTime() >= f.endsAt) patch.endsAt = d.getTime() + 2 * 36e5; upd(patch); };
    const setTime = (key, hhmm) => { const [h, m] = hhmm.split(':').map(Number); const d = new Date(f[key]); d.setHours(h, m, 0, 0); const patch = { [key]: d.getTime() }; if (key === 'startsAt' && d.getTime() >= f.endsAt) patch.endsAt = d.getTime() + 2 * 36e5; upd(patch); };
    const preview = { id: 'preview', clubId: club.id, title: f.title || t('eventForm.untitled'), desc: f.desc, type: f.type, startsAt: f.startsAt, endsAt: f.endsAt, placeId: f.placeId, placeText: f.placeText, capacity: f.unlimited ? null : f.capacity, visibility: f.visibility, status: 'published', coverSeed: f.cover.seed, coverPalette: f.cover.palette, coverPattern: f.cover.pattern, registrationOpen: true };
    return html`<${AppBar} onBack=${close} backAction="MGT-05.close" closeIcon titleNode=${html`<div class="col gap6"><span class="t-caption">${editing ? t('eventForm.editTitle') : t('eventForm.title')} · ${f.step}/3</span><${Stepbar} step=${f.step} total=${3} /></div>`} />
      <${Scroll} routeKey=${'eventform-' + f.step}><div class="col gap16 px16 pt8 pb24">
        ${f.step === 1 ? html`<button type="button" class="cover r16-9" style="border-radius:16px;width:100%;position:relative" data-action="MGT-05.cover" onClick=${() => app.openSheet('SHT-31', { value: f.cover, icon: club.iconName, onSelect: (c) => upd({ cover: c }) })} aria-label=${t('eventForm.cover')}><div style="position:absolute;inset:0" dangerouslySetInnerHTML=${{ __html: GU.coverArtSVG(f.cover.seed, club.iconName, f.cover.palette, f.cover.pattern) }} /><span class="btn btn-sm btn-outline" style="position:absolute;right:12px;bottom:12px"><${Icon} name="image" size=${16} />${t('eventForm.changeCover')}</span></button>
          <${Input} label=${t('eventForm.name')} value=${f.title} onInput=${(v) => upd({ title: v.slice(0, 80) })} maxLength=${80} counter error=${f.errors.title} action="MGT-05.title" autofocus />
          <${Input} label=${t('eventForm.desc')} multiline rows=${5} value=${f.desc} onInput=${(v) => upd({ desc: v.slice(0, 1000) })} maxLength=${1000} counter action="MGT-05.desc" />
          <div class="col gap8"><span class="field-label">${t('eventForm.type')}</span><div class="row wrap gap8">${EVENT_TYPES.map((ty) => html`<${Chip} key=${ty} label=${t('eventType.' + ty)} selected=${f.type === ty} action=${'MGT-05.type.' + ty} onClick=${() => upd({ type: ty })} />`)}</div></div>` : null}
        ${f.step === 2 ? html`<div class="row gap8"><div class="flex1"><${Picker} label=${t('eventForm.startDate')} icon="calendar" value=${app.fmt.dateShort(f.startsAt)} error=${f.errors.start} action="MGT-05.startDate" onClick=${() => app.openSheet('SHT-28', { value: f.startsAt, min: editing ? null : Date.now(), onSelect: (ts) => setDate('startsAt', ts) })} /></div><div style="width:120px"><${Picker} label=${t('eventForm.time')} icon="clock" value=${app.fmt.time(f.startsAt)} action="MGT-05.startTime" onClick=${() => app.openSheet('SHT-29', { value: app.fmt.time(f.startsAt), onSelect: (v) => setTime('startsAt', v) })} /></div></div>
          <div class="row gap8"><div class="flex1"><${Picker} label=${t('eventForm.endDate')} icon="calendar" value=${app.fmt.dateShort(f.endsAt)} error=${f.errors.end} action="MGT-05.endDate" onClick=${() => app.openSheet('SHT-28', { value: f.endsAt, min: f.startsAt, onSelect: (ts) => setDate('endsAt', ts) })} /></div><div style="width:120px"><${Picker} label=${t('eventForm.time')} icon="clock" value=${app.fmt.time(f.endsAt)} action="MGT-05.endTime" onClick=${() => app.openSheet('SHT-29', { value: app.fmt.time(f.endsAt), onSelect: (v) => setTime('endsAt', v) })} /></div></div>
          ${conflicts ? html`<${Banner} kind="info" icon="calendar-days" text=${t('eventForm.conflict', { count: conflicts })} card />` : null}
          <${Picker} label=${t('eventForm.place')} icon="map-pin" value=${f.placeId ? t('place.' + f.placeId) : f.placeText || ''} placeholder=${t('common.select')} error=${f.errors.place} action="MGT-05.place" onClick=${() => app.openSheet('SHT-30', { value: f.placeId, text: f.placeText, onSelect: (id, text) => upd({ placeId: id, placeText: text, errors: { ...f.errors, place: null } }) })} />
          <div class="col gap8"><div class="row between"><span class="field-label">${t('eventForm.capacity')}</span><span class="row gap8"><span class="t-body-s c-sec">${t('eventForm.unlimited')}</span><${Switch} checked=${f.unlimited} onChange=${(v) => upd({ unlimited: v })} action="MGT-05.unlimited" label=${t('eventForm.unlimited')} /></span></div>${!f.unlimited ? html`<div class="row gap12" style="justify-content:center"><${IconButton} icon="minus" label=${t('eventForm.decrease')} action="MGT-05.capacity.minus" onClick=${() => upd({ capacity: Math.max(1, f.capacity - 5) })} style=${{ background: 'var(--bg-surface-muted)' }} /><span class="kpi-value tnum" style="min-width:64px;text-align:center">${f.capacity}</span><${IconButton} icon="plus" label=${t('eventForm.increase')} action="MGT-05.capacity.plus" onClick=${() => upd({ capacity: Math.min(1000, f.capacity + 5) })} style=${{ background: 'var(--bg-surface-muted)' }} /></div>${f.errors.capacity ? html`<div class="field-help is-error" role="alert"><${Icon} name="triangle-alert" size=${14} /><span>${f.errors.capacity}</span></div>` : editing ? html`<span class="t-caption center">${t('eventForm.registeredNow', { count: registered })}</span>` : null}` : null}</div>
          <div class="col gap8"><span class="field-label">${t('eventForm.visibility')}</span><${Segmented} options=${[{ id: 'public', label: t('event.visibility.public'), icon: 'globe' }, { id: 'members', label: t('event.visibility.members'), icon: 'lock' }]} value=${f.visibility} onChange=${(v) => upd({ visibility: v })} action="MGT-05.visibility" /><span class="t-caption">${t('eventForm.visibilityHelp.' + f.visibility)}</span></div>
          <div class="row between"><div class="col"><span class="t-body-m">${t('eventForm.autoReminder')}</span><span class="t-caption">${t('eventForm.autoReminderHelp')}</span></div><${Switch} checked=${f.autoReminder} onChange=${(v) => upd({ autoReminder: v })} action="MGT-05.autoReminder" label=${t('eventForm.autoReminder')} /></div>` : null}
        ${f.step === 3 ? html`<${Banner} kind="info" icon="eye" text=${t('eventForm.previewNote')} card /><${EventCard} ev=${preview} screen="MGT-05" showClub=${false} /><${Card}>${[[t('eventForm.name'), f.title], [t('eventForm.type'), t('eventType.' + f.type)], [t('eventForm.startDate'), app.fmt.dateTime(f.startsAt)], [t('eventForm.endDate'), app.fmt.dateTime(f.endsAt)], [t('eventForm.place'), f.placeId ? t('place.' + f.placeId) : f.placeText], [t('eventForm.capacity'), f.unlimited ? t('eventForm.unlimited') : String(f.capacity)], [t('eventForm.visibility'), f.visibility === 'public' ? t('event.visibility.public') : t('event.visibility.members')]].map(([k, v], i) => html`${i ? html`<div class="divider" />` : null}<div key=${k} class="row between" style="padding:10px 16px"><span class="t-body-s c-muted">${k}</span><span class="t-body-s c-heading right" style="max-width:60%">${v}</span></div>`)}</${Card}>` : null}
      </div></${Scroll}>
      <${StickyCTA}>${f.step > 1 ? html`<${Button} variant="outline" label=${t('common.back')} action="MGT-05.back" onClick=${() => set({ step: f.step - 1 })} />` : null}${f.step < 3 ? html`<${Button} label=${t('common.continue')} action="MGT-05.next" onClick=${() => validate() && set({ step: f.step + 1 })} />` : html`<${Button} variant="outline" label=${t('eventForm.saveDraft')} action="MGT-05.saveDraft" onClick=${saveDraft} /><${Button} label=${editing && editing.status === 'published' ? t('common.save') : t('eventForm.publish')} loading=${busy} action="MGT-05.publish" onClick=${publish} />`}</${StickyCTA}>`;
  } };

  /* MGT-06 attendance */
  S['MGT-06'] = { tab: 'clubs', title: 'attendance.title', comp: function Attendance({ params, route }) {
    const { u, club, readOnly, allowed } = useMgt(params); const ev = sel().event(params.eventId); const [filter, setFilter] = useState('all'); const [q, setQ] = useState(''); const [menu, setMenu] = useState(null);
    if (!allowed || !ev) return html`<${NoAccess} screen="MGT-06" />`;
    const rs = sel().eventRsvps(ev.id).map((r) => ({ ...r, user: sel().user(r.userId) })).filter((r) => r.user); const reg = rs.filter((r) => r.status === 'going' || r.status === 'attended'); const att = rs.filter((r) => r.status === 'attended'); const wl = sel().waitlist(ev.id).map((r) => ({ ...r, user: sel().user(r.userId) })).filter((r) => r.user); const rate = reg.length ? Math.round((att.length / reg.length) * 100) : 0;
    const list = reg.filter((r) => filter === 'all' || (filter === 'attended' && r.status === 'attended') || (filter === 'absent' && r.status === 'going')).filter((r) => !q || r.user.name.toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))).sort((a, b) => a.user.name.localeCompare(b.user.name, 'tr'));
    const mark = (r, v) => { if (!app.guard(club.id)) return; const snap = app.store.get(); app.dispatch('rsvp.setAttended', { eventId: ev.id, userId: r.userId, attended: v }); app.toast('TST-31', { name: r.user.name, undo: () => app.store.restore(snap) }); };
    const exportCsv = () => { downloadText('\ufeff' + [['ad', 'eposta', 'durum', 'okutma']].concat(rs.map((r) => [r.user.name, r.user.email, t('status.' + r.status), r.scannedAt ? new Date(r.scannedAt).toISOString() : ''])).map((r) => r.map((c) => `"${c}"`).join(';')).join('\n'), 'katilimcilar.csv', 'text/csv;charset=utf-8'); app.toast('TST-29'); };
    const clubEvents = sel().clubEvents(club.id).filter((e) => e.status !== 'draft').sort((a, b) => b.startsAt - a.startsAt);
    return html`<${AppBar} onBack=${() => app.nav.back()} backAction="MGT-06.back" titleNode=${html`<div class="col"><span class="t-caption">${t('attendance.title')} · ${club.name}</span><button type="button" class="row gap4 t-title-s" style="text-align:left" data-action="MGT-06.switchEvent" onClick=${() => setMenu('events')}><span class="ellipsis" style="max-width:180px">${ev.title}</span><${Icon} name="chevron-down" size=${16} /></button></div>`}>${readOnly ? null : html`<${IconButton} icon="scan-line" label=${t('event.cta.scan')} brand action="MGT-06.scan" onClick=${() => app.nav.push('MGT-07', { clubId: club.id, eventId: ev.id })} />`}<${IconButton} icon="more-vertical" label=${t('a11y.more')} action="MGT-06.menu" onClick=${() => setMenu('top')} /></${AppBar}><${ROBanner} readOnly=${readOnly} />
      ${ev.startsAt > Date.now() ? html`<${Banner} kind="info" text=${t('attendance.notStarted')} />` : null}
      <div class="hscroll py8">${[['all', t('attendance.registered'), reg.length], ['attended', t('status.attended'), att.length], ['absent', t('attendance.absent'), reg.length - att.length], ['waitlist', t('status.waitlist'), wl.length]].map(([id, l, n]) => html`<${Chip} key=${id} label=${`${l} ${n}`} selected=${filter === id} action=${'MGT-06.summary.' + id} onClick=${() => setFilter(id)} />`)}</div>
      <div class="px16 col gap8 pb16"><div class="row gap8"><${Progress} value=${rate} max=${100} kind="success" label=${t('attendance.rate')} /><span class="t-label-m tnum">${t('attendance.rate')} %${rate}</span></div><${Input} icon="search" placeholder=${t('members.search')} value=${q} onInput=${setQ} action="MGT-06.search" ariaLabel=${t('members.search')} /></div>
      <${Scroll} routeKey=${route.key}><${ListState} n=${5} emptyProps=${{ illustration: 'empty-applications', title: t('attendance.empty') }}>
        ${filter !== 'waitlist' ? (list.length ? list.map((r) => html`<div key=${r.userId} class="tile is-plain"><${Avatar} user=${r.user} size=${40} /><span class="tile-text"><span class="t-body-m c-heading" style="display:block">${r.user.name}</span><span class="t-caption">${deptYear(r.user)}</span></span><${StatusBadge} status=${r.status === 'attended' ? 'attended' : 'going'} label=${r.status === 'attended' ? t('status.attended') : t('attendance.registeredOne')} /><${Switch} checked=${r.status === 'attended'} onChange=${(v) => mark(r, v)} action=${'MGT-06.attended.' + r.userId} label=${t('status.attended')} disabled=${readOnly} onDisabledClick=${() => app.toast('TST-26')} /></div>`) : html`<${EmptyState} illustration="empty-applications" title=${q ? t('members.noResults') : t('attendance.empty')} compact />`) : null}
        ${filter === 'all' || filter === 'waitlist' ? html`<div class="group-head"><span class="t-overline">${t('status.waitlist')}</span><span class="t-caption tnum">${wl.length}</span></div>${wl.length ? wl.map((r, i) => html`<div key=${r.userId} class="tile is-plain"><span class="badge-count" style="background:var(--text-muted)">${i + 1}</span><${Avatar} user=${r.user} size=${36} /><span class="tile-text"><span class="t-body-m c-heading" style="display:block">${r.user.name}</span><span class="t-caption">${deptYear(r.user)}</span></span><${Button} size="sm" variant="tonal" label=${t('attendance.promote')} disabled=${(ev.capacity != null && reg.length >= ev.capacity) || readOnly} action=${'MGT-06.promote.' + r.userId} onClick=${() => { if (!app.guard(club.id)) return; app.dispatch('rsvp.promote', { eventId: ev.id, userId: r.userId }); app.toast('TST-X13', { name: r.user.name }); }} onDisabledClick=${() => app.toast(readOnly ? 'TST-26' : 'TST-X14')} /></div>`) : html`<p class="t-body-s c-muted px16 pb16">${t('attendance.noWaitlist')}</p>`}` : null}
      </${ListState}></${Scroll}>
      ${menu === 'top' ? html`<${PopMenu} id="MGT-06" onClose=${() => setMenu(null)}><${Tile} title=${t('mgtMembers.export')} leading=${html`<${Icon} name="download" size=${20} />`} action="MGT-06.export" onClick=${() => { setMenu(null); exportCsv(); }} /><${Tile} title=${t('attendance.markAll')} leading=${html`<${Icon} name="check-check" size=${20} />`} disabled=${readOnly} action="MGT-06.markAll" onClick=${() => { setMenu(null); if (!app.guard(club.id)) return; app.openDialog('DLG-17', { kind: 'attendance', count: reg.length, onConfirm: () => { const snap = app.store.get(); app.dispatch('rsvp.markAllAttended', { eventId: ev.id }); app.closeDialog(); app.toast('TST-31', { name: t('attendance.allRegistered'), undo: () => app.store.restore(snap) }); } }); }} /><${Tile} title=${ev.registrationOpen ? t('attendance.closeReg') : t('attendance.openReg')} leading=${html`<${Icon} name=${ev.registrationOpen ? 'lock' : 'lock-open'} size=${20} />`} disabled=${readOnly} action="MGT-06.toggleRegistration" onClick=${() => { setMenu(null); if (!app.guard(club.id)) return; app.dispatch('event.toggleRegistration', { eventId: ev.id }); app.toast('TST-X15', { open: !ev.registrationOpen }); }} /></${PopMenu}>` : null}
      ${menu === 'events' ? html`<${PopMenu} id="MGT-06" onClose=${() => setMenu(null)}>${clubEvents.map((e) => html`<${Tile} key=${e.id} title=${e.title} subtitle=${app.fmt.dateShort(e.startsAt)} trailing=${e.id === ev.id ? html`<${Icon} name="check" size=${18} class="c-brand" />` : null} action=${'MGT-06.switchEvent.' + e.id} onClick=${() => { setMenu(null); app.nav.replace('MGT-06', { clubId: club.id, eventId: e.id }); }} />`)}</${PopMenu}>` : null}`;
  } };

  /* MGT-07 scanner */
  S['MGT-07'] = { tab: 'clubs', title: 'scan.title', comp: function Scanner({ params }) {
    const { u, club, readOnly, allowed } = useMgt(params); const ev = sel().event(params.eventId); const [torch, setTorch] = useState(false); const [front, setFront] = useState(false); const [manual, setManual] = useState(false); const [code, setCode] = useState(''); const perm = app.state.session.cameraPermission;
    useEffect(() => { if (GU.SCANNING) return; if (perm === 'default') setTimeout(() => app.openDialog('DLG-04'), 300); }, []);
    if (!allowed || !ev || readOnly) return html`<${NoAccess} screen="MGT-07" />`;
    const att = sel().attended(ev.id).length; const reg = sel().registered(ev.id).length;
    const demo = (kind) => { const going = sel().eventRsvps(ev.id).filter((r) => r.status === 'going'); const used = sel().attended(ev.id); if (kind === 'valid' && going.length) { const r = going[0]; const snap = app.store.get(); app.dispatch('rsvp.scan', { eventId: ev.id, userId: r.userId }); app.openSheet('SHT-24', { kind: 'valid', userId: r.userId, eventId: ev.id, undo: () => app.store.restore(snap) }); } else if (kind === 'valid') app.openSheet('SHT-24', { kind: 'invalid', reason: 'none' }); else if (kind === 'used') app.openSheet('SHT-24', { kind: 'used', userId: used.length ? used[0].userId : null, scannedAt: used.length ? used[0].scannedAt : Date.now(), eventId: ev.id }); else app.openSheet('SHT-24', { kind: 'invalid', reason: 'other' }); };
    const verify = () => { const r = sel().eventRsvps(ev.id).find((x) => x.ticketCode === code.trim().toUpperCase()); if (!r) { app.openSheet('SHT-24', { kind: 'invalid', reason: 'other' }); return; } const res = app.dispatch('rsvp.scan', { eventId: ev.id, userId: r.userId }); app.openSheet('SHT-24', { kind: res, userId: r.userId, eventId: ev.id, scannedAt: r.scannedAt }); setCode(''); setManual(false); };
    if (perm === 'denied') return html`<div class="scan-view" style="padding-top:var(--safe-top)"><div class="row" style="padding:4px 8px"><${IconButton} onCover icon="x" label=${t('a11y.close')} action="MGT-07.close" onClick=${() => app.nav.back()} /></div><div class="empty flex1" style="justify-content:center;color:#fff"><${Icon} name="camera" size=${64} /><h2 class="t-title-m" style="color:#fff">${t('scan.permissionTitle')}</h2><p class="t-body-s" style="color:rgba(255,255,255,.7)">${t('scan.permissionDesc')}</p><${Button} variant="outline" label=${t('scan.manualCode')} action="MGT-07.manualCode" onClick=${() => { app.dispatch('session.set', { cameraPermission: 'manual' }); setManual(true); }} style=${{ color: '#fff', borderColor: 'rgba(255,255,255,.4)', background: 'transparent' }} /><${Button} label=${t('scan.goSettings')} action="MGT-07.permission.retry" onClick=${() => app.toast('TST-32')} /></div></div>`;
    return html`<div class="scan-view" style="padding-top:var(--safe-top)">
      <div class="row gap4" style="padding:4px 8px"><${IconButton} onCover icon="x" label=${t('a11y.close')} action="MGT-07.close" onClick=${() => app.nav.back()} /><div class="flex1 col" style="padding:0 8px"><span class="t-title-s ellipsis" style="color:#fff">${ev.title}</span><span class="t-caption" style="color:rgba(255,255,255,.7)">${t('scan.counter', { a: att, b: reg })}</span></div><${IconButton} onCover icon="flashlight" label=${t('scan.torch')} action="MGT-07.torch" onClick=${() => setTorch(!torch)} style=${torch ? { background: '#fff', color: '#000' } : undefined} /><${IconButton} onCover icon="switch-camera" label=${t('scan.flip')} action="MGT-07.flip" onClick=${() => setFront(!front)} /></div>
      <div class="flex1 col" style="justify-content:center;align-items:center;gap:16px"><div class="scan-box" style=${{ transform: front ? 'scaleX(-1)' : 'none', filter: torch ? 'brightness(1.4)' : 'none' }}><i /><i /><i /><i /><span class="scanline" /></div><p class="t-body-s center" style="color:rgba(255,255,255,.7);max-width:260px">${t('scan.hint')}</p></div>
      <div class="col gap12" style="padding:16px 16px calc(var(--safe-bottom) + 16px);background:rgba(0,0,0,.35)">
        ${manual ? html`<div class="row gap8" style="align-items:flex-end"><div class="flex1" style="color:var(--text-primary)"><${Input} label=${t('scan.enterCode')} value=${code} onInput=${(v) => setCode(v.toUpperCase())} placeholder="GU-XXXX-XXXX" action="MGT-07.codeInput" autofocus onEnter=${verify} /></div><${Button} label=${t('scan.verify')} action="MGT-07.verify" onClick=${verify} disabled=${code.length < 12} onDisabledClick=${() => {}} /></div>` : html`<${Button} variant="outline" icon="pencil" label=${t('scan.manualCode')} action="MGT-07.manualCode" onClick=${() => setManual(true)} style=${{ color: '#fff', borderColor: 'rgba(255,255,255,.4)', background: 'transparent' }} />`}
        <span class="t-overline" style="color:rgba(255,255,255,.6)">${t('common.demo')}: ${t('scan.demoScan')}</span>
        <div class="row gap8"><${Button} size="sm" variant="tonal" label=${t('scan.demo.valid')} action="MGT-07.demoScan.valid" onClick=${() => demo('valid')} style=${{ flex: 1 }} /><${Button} size="sm" variant="tonal" label=${t('scan.demo.used')} action="MGT-07.demoScan.used" onClick=${() => demo('used')} style=${{ flex: 1 }} /><${Button} size="sm" variant="tonal" label=${t('scan.demo.invalid')} action="MGT-07.demoScan.invalid" onClick=${() => demo('invalid')} style=${{ flex: 1 }} /></div></div></div>`;
  } };

  /* MGT-08 content */
  S['MGT-08'] = { tab: 'clubs', title: 'content.title', comp: function Content({ params, route }) {
    const { u, club, readOnly, allowed } = useMgt(params); const [tab, setTab] = useState(params.tab || 'posts'); const [q, setQ] = useState(''); const [menu, setMenu] = useState(null); if (!allowed) return html`<${NoAccess} screen="MGT-08" />`;
    const posts = sel().allPostsOf(club.id).filter((p) => (tab === 'posts' ? p.type === 'post' : tab === 'announcements' ? p.type === 'announcement' : p.type === 'poll')).filter((p) => !q || (p.title || '' + ' ' + p.text).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr')));
    const pin = (p) => { if (!app.guard(club.id)) return; app.dispatch('post.pin', { postId: p.id, pinned: !p.pinned }); app.toast('TST-53', { pinned: !p.pinned }); };
    return html`<${MgtHeader} club=${club} title=${t('content.title')} screen="MGT-08" /><${ROBanner} readOnly=${readOnly} /><div class="px16 pb16 col gap8"><${Segmented} options=${[{ id: 'posts', label: t('content.tab.posts') }, { id: 'announcements', label: t('content.tab.announcements') }, { id: 'polls', label: t('content.tab.polls') }]} value=${tab} onChange=${setTab} action="MGT-08.tab" /><${Input} icon="search" placeholder=${t('common.search')} value=${q} onInput=${setQ} action="MGT-08.search" ariaLabel=${t('common.search')} /></div>
      <${Scroll} routeKey=${route.key}><${ListState} n=${4} emptyProps=${{ illustration: 'empty-posts', title: t('content.empty') }}>${posts.length ? posts.map((p) => { const reports = sel().reportsOnTarget('post', p.id); const nRep = reports.reduce((a, r) => a + r.reasons.length, 0); return html`<${Tile} key=${p.id} leading=${html`<span class=${cx('notif-icon', p.type === 'announcement' ? 'ni-brand' : p.type === 'poll' ? 'ni-info' : 'ni-neutral')}><${Icon} name=${p.type === 'announcement' ? 'megaphone' : p.type === 'poll' ? 'chart-column' : 'file-text'} size=${18} /></span>`} title=${html`<span class="row gap6">${p.pinned ? html`<${Icon} name="pin" size=${14} class="c-brand" />` : null}<span class="clamp1">${p.title || p.text}</span></span>`} subtitle=${`${app.fmt.rel(p.createdAt)} · ${t('content.stats', { likes: p.likes.length, comments: p.commentIds.length })}${p.hidden ? ' · ' + t('content.hidden') : ''}`} sub2=${nRep ? html`<${Badge} kind="pending" icon="flag" label=${t('content.reports', { count: nRep })} />` : null} action=${'MGT-08.row.' + p.id} onClick=${() => app.nav.push('FED-02', { clubId: club.id, postId: p.id })} trailing=${html`<${IconButton} icon="more-vertical" label=${t('a11y.more')} action=${'MGT-08.menu.' + p.id} onClick=${(e) => { e.stopPropagation(); setMenu(p); }} />`} />`; }) : html`<${EmptyState} illustration="empty-posts" title=${t('content.empty')} />`}</${ListState}></${Scroll}>
      ${readOnly ? null : html`<button type="button" class="fab" aria-label=${t('compose.title')} data-action="MGT-08.create" onClick=${() => app.nav.push('FED-03', { clubId: club.id })}><${Icon} name="plus" size=${22} />${t('feed.type.post')}</button>`}
      ${menu ? html`<${PopMenu} id="MGT-08" onClose=${() => setMenu(null)}><${Tile} title=${menu.pinned ? t('post.unpin') : t('post.pin')} leading=${html`<${Icon} name=${menu.pinned ? 'pin-off' : 'pin'} size=${20} />`} disabled=${readOnly} action=${'MGT-08.pin.' + menu.id} onClick=${() => { setMenu(null); pin(menu); }} /><${Tile} title=${t('common.edit')} leading=${html`<${Icon} name="pencil" size=${20} />`} disabled=${readOnly} action=${'MGT-08.edit.' + menu.id} onClick=${() => { setMenu(null); if (!app.guard(club.id)) return; app.nav.push('FED-03', { clubId: club.id, edit: menu.id }); }} /><${Tile} title=${t('common.delete')} danger leading=${html`<${Icon} name="trash-2" size=${20} />`} disabled=${readOnly} action=${'MGT-08.delete.' + menu.id} onClick=${() => { setMenu(null); if (!app.guard(club.id)) return; app.openDialog('DLG-10', { postId: menu.id }); }} /></${PopMenu}>` : null}`;
  } };

  /* MGT-09 club settings */
  S['MGT-09'] = { tab: 'clubs', title: 'clubSettings.title', comp: function ClubSettings({ params }) {
    const { u, club, readOnly, allowed } = useMgt(params); if (!allowed) return html`<${NoAccess} screen="MGT-09" />`;
    const [f, set, reset] = useForm('clubSettings-' + club.id, { categoryId: club.categoryId, summary: club.summary, about: club.about, email: club.social.email || '', instagram: club.social.instagram || '', web: club.social.web || '', applicationsOpen: club.applicationsOpen, approvalRequired: club.approvalRequired, requireNote: !!club.requireNote, cover: { palette: club.palette, pattern: club.pattern, seed: club.coverSeed }, errors: {}, dirty: false }); const [busy, run] = useBusy();
    const upd = (p) => { if (readOnly) { app.toast('TST-26'); return; } set({ ...p, dirty: true }); }; const ro = () => app.toast('TST-26');
    const back = () => { if (f.dirty) app.openDialog('DLG-25', { onSave: () => { app.closeDialog(); save(); }, onDiscard: () => { app.closeDialog(); reset(); app.nav.back(); }, onKeep: () => app.closeDialog() }); else { reset(); app.nav.back(); } };
    const save = () => run(async () => { const e = {}; if (f.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.email)) e.email = t('auth.err.email'); if (f.instagram && !/^@?[\w.]{2,30}$/.test(f.instagram)) e.instagram = t('clubSettings.err.instagram'); if (f.web && !/^https?:\/\/.+\..+/.test(f.web)) e.web = t('clubSettings.err.web'); set({ errors: e }); if (Object.keys(e).length) return; if (!app.guard(club.id)) return; await app.api(); const wasOpen = club.applicationsOpen; app.dispatch('club.update', { clubId: club.id, patch: { categoryId: f.categoryId, summary: f.summary, about: f.about, social: { email: f.email, instagram: f.instagram.startsWith('@') || !f.instagram ? f.instagram : '@' + f.instagram, web: f.web }, applicationsOpen: f.applicationsOpen, approvalRequired: f.approvalRequired, requireNote: f.requireNote, palette: f.cover.palette, pattern: f.cover.pattern, coverSeed: f.cover.seed }, actorId: u }); set({ dirty: false }); app.toast('TST-21'); if (wasOpen !== f.applicationsOpen) setTimeout(() => app.toast('TST-54', { open: f.applicationsOpen }), 1200); });
    const advisor = sel().user(club.advisorId);
    return html`<${MgtHeader} club=${club} title=${t('clubSettings.title')} screen="MGT-09" back=${back} /><${ROBanner} readOnly=${readOnly} /><${Scroll} routeKey=${'clubsettings-' + club.id}><div class="col gap20 px16 pt8 pb24">
      <div class="col gap8"><span class="t-overline">${t('clubSettings.group.look')}</span><div class="row gap12"><button type="button" class="emblem" data-action="MGT-09.logo" onClick=${() => (readOnly ? ro() : app.openSheet('SHT-16', { onPick: () => app.toast('TST-57') }))} aria-label=${t('clubSettings.logo')}><${Icon} name=${club.iconName} size=${30} /></button><button type="button" class="cover r16-9 flex1" style="border-radius:16px;position:relative;height:72px;aspect-ratio:auto" data-action="MGT-09.cover" onClick=${() => (readOnly ? ro() : app.openSheet('SHT-31', { value: f.cover, icon: club.iconName, onSelect: (c) => upd({ cover: c }) }))} aria-label=${t('clubSettings.cover')}><div style="position:absolute;inset:0" dangerouslySetInnerHTML=${{ __html: GU.coverArtSVG(f.cover.seed, club.iconName, f.cover.palette, f.cover.pattern) }} /><span class="badge badge-neutral" style="position:absolute;right:8px;bottom:8px;background:var(--bg-surface)">${t('clubSettings.cover')}</span></button></div></div>
      <div class="col gap12"><span class="t-overline">${t('clubSettings.group.info')}</span><div role="button" tabindex="0" data-action="MGT-09.lockedName" onClick=${() => app.toast('TST-20')} onKeyDown=${(e) => e.key === 'Enter' && app.toast('TST-20')}><${Input} label=${t('clubSettings.name')} value=${club.name} locked help=${t('clubSettings.nameLocked')} action="MGT-09.name" /></div>
        <${Picker} label=${t('clubSettings.category')} icon="layout-grid" value=${t('cat.' + f.categoryId)} action="MGT-09.category" onClick=${() => (readOnly ? ro() : app.openSheet('SHT-33', { value: f.categoryId, onSelect: (id) => upd({ categoryId: id }) }))} />
        <${Input} label=${t('clubSettings.summary')} value=${f.summary} onInput=${(v) => upd({ summary: v.slice(0, 160) })} maxLength=${160} counter action="MGT-09.summary" disabled=${readOnly} />
        <${Input} label=${t('clubSettings.about')} multiline rows=${5} value=${f.about} onInput=${(v) => upd({ about: v.slice(0, 1000) })} maxLength=${1000} counter action="MGT-09.about" disabled=${readOnly} /></div>
      <div class="col gap12"><span class="t-overline">${t('clubSettings.group.contact')}</span><${Input} label=${t('auth.email')} icon="mail" value=${f.email} onInput=${(v) => upd({ email: v })} error=${f.errors.email} action="MGT-09.email" disabled=${readOnly} /><${Input} label="Instagram" icon="camera" value=${f.instagram} onInput=${(v) => upd({ instagram: v })} error=${f.errors.instagram} action="MGT-09.instagram" disabled=${readOnly} /><${Input} label=${t('club.contact.web')} icon="globe" value=${f.web} onInput=${(v) => upd({ web: v })} error=${f.errors.web} action="MGT-09.web" disabled=${readOnly} /></div>
      <div class="col gap8"><span class="t-overline">${t('clubSettings.group.join')}</span><${Card}>${[['applicationsOpen', 'lock-open'], ['approvalRequired', 'shield-check'], ['requireNote', 'file-text']].map(([k, icon], i) => html`${i ? html`<div class="divider" />` : null}<div key=${k} class="tile is-plain in-card"><${Icon} name=${icon} size=${20} class="c-muted" /><span class="tile-text"><span class="t-body-m c-heading" style="display:block">${t('clubSettings.' + k)}</span><span class="t-caption">${t('clubSettings.' + k + 'Help')}</span></span><${Switch} checked=${f[k]} onChange=${(v) => upd({ [k]: v })} action=${'MGT-09.toggle.' + k} label=${t('clubSettings.' + k)} disabled=${readOnly} onDisabledClick=${ro} /></div>`)}</${Card}>${!f.approvalRequired ? html`<${Banner} kind="warning" text=${t('clubSettings.instantWarning')} card />` : null}</div>
      <div class="col gap8"><span class="t-overline">${t('club.advisor')}</span><${Card}><${UserRow} user=${advisor} sub=${t('clubSettings.advisorLocked')} inCard /></${Card}></div>
    </div></${Scroll}><${StickyCTA}><${Button} full label=${t('common.save')} loading=${busy} disabled=${!f.dirty || readOnly} action="MGT-09.save" onClick=${save} onDisabledClick=${() => app.toast(readOnly ? 'TST-26' : 'TST-X9')} /></${StickyCTA}>`;
  } };

  /* MGT-10 activity */
  S['MGT-10'] = { tab: 'clubs', title: 'activity.title', comp: function Activity({ params, route }) {
    const { club, readOnly, allowed } = useMgt(params); const [filter, setFilter] = useState('all'); if (!allowed) return html`<${NoAccess} screen="MGT-10" />`;
    const acts = sel().activityOf(club.id).filter((a) => filter === 'all' || ACT_CAT[a.kind] === filter); const groups = []; acts.forEach((a) => { const k = dayKey(a.createdAt); const g = groups.find((x) => x.k === k); if (g) g.items.push(a); else groups.push({ k, ts: a.createdAt, items: [a] }); });
    return html`<${MgtHeader} club=${club} title=${t('activity.title')} screen="MGT-10" /><${ROBanner} readOnly=${readOnly} /><div class="hscroll py8">${['all', 'membership', 'event', 'content', 'settings'].map((f) => html`<${Chip} key=${f} label=${f === 'all' ? t('common.all') : t('activity.cat.' + f)} selected=${filter === f} action=${'MGT-10.filter.' + f} onClick=${() => setFilter(f)} />`)}</div>
      <${Scroll} routeKey=${route.key}><${ListState} n=${6} emptyProps=${{ illustration: 'empty-notifications', title: t('activity.empty') }}>${groups.length ? html`${groups.map((g) => html`<div key=${g.k}><div class="group-head"><span class="t-overline" style="text-transform:none">${app.fmt.dayLabel(g.ts)}</span></div>${g.items.map((a) => html`<${ActivityRow} key=${a.id} a=${a} screen="MGT-10" club=${club} />`)}</div>`)}<${ListEnd} />` : html`<${EmptyState} illustration="empty-notifications" title=${t('activity.empty')} />`}</${ListState}></${Scroll}>`;
  } };
})();
