/* ===== SHELL ===== site layout (menu · device frame · control panel), app frame, overlays, action tracking, <gu-shell> element */
(function () {
  const { h, render, html, cx, Icon, app, store, nav, ui, registry, useState, useEffect, useRef, useLayoutEffect, Button, IconButton, Switch, Segmented, Avatar, Banner, RoleBadge, Logo, DEMO_ACCOUNTS, injectCSS, initIcons, seed } = GU;
  const t = (k, p) => app.t(k, p); const sel = () => app.sel;
  const PAGES_META = [['proto', 'site.proto', 'smartphone'], ['assets', 'site.assets', 'download'], ['ds', 'site.ds', 'palette'], ['map', 'site.map', 'layout-grid'], ['qa', 'site.qa', 'list-checks']];
  const site = { page: 'proto', listeners: new Set(), setPage(p) { this.page = p; this.listeners.forEach((f) => f()); }, openProto(screen, params, userId) { if (userId && app.uid() !== userId) { app.dispatch('session.login', { userId }); } if (screen) { ui.closeAllSheets(); ui.dialogs = []; nav.resetTo(screen, params || {}); } this.setPage('proto'); } };
  GU.site = site;

  /* ---------- status bar / nav / overlays ---------- */
  function StatusBar({ dark }) { GU.useTicker(30000); const d = new Date(); return html`<div class=${cx('statusbar', dark && 'on-dark')} aria-hidden="true"><span class="tnum">${GU.pad2(d.getHours())}:${GU.pad2(d.getMinutes())}</span><span class="row gap6" style="font-size:12px"><${Icon} name=${app.online() ? 'wifi-off' : 'wifi-off'} size=${14} style=${{ visibility: app.online() ? 'hidden' : 'visible' }} /><span style="display:inline-flex;gap:2px;align-items:flex-end;height:11px">${[4, 6, 8, 11].map((hh, i) => html`<i key=${i} style=${{ width: '3px', height: hh + 'px', background: 'currentColor', borderRadius: '1px', opacity: i < 3 ? 1 : 0.3 }} />`)}</span><span style="display:inline-block;width:24px;height:11px;border:1.5px solid currentColor;border-radius:3px;position:relative"><i style="position:absolute;left:1px;top:1px;bottom:1px;width:70%;background:currentColor;border-radius:1px" /></span></span></div>`; }
  function BottomNav() { const u = app.uid(); const tabs = GU.TABS.filter((tb) => tb !== 'admin' || sel().isSuper(u)); const unread = sel().unread(u); const icons = { clubs: 'users-round', events: 'calendar', notifications: 'bell', admin: 'shield-check', profile: 'user' };
    return html`<nav class="bottomnav" aria-label=${t('a11y.mainNav')}>${tabs.map((tb) => html`<button type="button" key=${tb} aria-current=${nav.activeTab === tb ? 'page' : undefined} data-action=${'NAV.tab.' + tb} onClick=${() => nav.switchTab(tb)}><${Icon} name=${icons[tb]} size=${24} /><span>${t('nav.' + tb)}</span>${tb === 'notifications' && unread ? html`<span class="nav-badge">${unread > 9 ? '9+' : unread}</span>` : null}</button>`)}</nav>`; }
  function ScreenHost() { const route = nav.current(); const def = GU.SCREENS[route.screen]; const hasNav = nav.mode === 'app' && nav.depth() === 1; const Comp = def ? def.comp : () => html`<div class="empty">${route.screen}</div>`;
    return html`<div class=${cx('screen', 'anim-' + nav.anim, hasNav && 'has-nav')} key=${route.key} data-screen=${route.screen} data-screen-label=${route.screen}>${!app.online() && nav.mode === 'app' ? html`<${Banner} kind="offline" text=${t('sys.offline.banner')} />` : null}<${Comp} params=${route.params || {}} route=${route} /></div>`; }
  function Overlays() { const hasNav = nav.mode === 'app' && nav.depth() === 1;
    return html`${ui.sheets.map((s) => { const def = GU.SHEETS[s.id]; if (!def) return null; return html`<${def.comp} key=${s.key} props=${s.props} close=${() => { const i = ui.sheets.indexOf(s); if (i >= 0) { ui.sheets.splice(i, 1); ui.notify(); } }} />`; })}
      ${ui.menu ? (() => { const M = GU.MENUS[ui.menu.id]; return M ? html`<${M} key=${ui.menu.key} props=${ui.menu.props} close=${() => ui.closeMenu()} />` : null; })() : null}
      ${ui.dialogs.map((d) => { const def = GU.DIALOGS[d.id]; if (!def) return null; return html`<${def.comp} key=${d.key} props=${d.props} close=${() => { const i = ui.dialogs.indexOf(d); if (i >= 0) { ui.dialogs.splice(i, 1); ui.notify(); } }} />`; })}
      ${ui.toast ? html`<${Toast} key=${ui.toast.key} toast=${ui.toast} aboveNav=${hasNav} />` : null}`; }
  function Toast({ toast, aboveNav }) { const def = GU.TOASTS[toast.id]; if (!def) return null; const p = toast.props || {}; const color = { success: 'var(--state-success)', error: 'var(--state-danger)', info: 'var(--state-info)' }[def.kind]; const icon = { success: 'circle-check', error: 'triangle-alert', info: 'info' }[def.kind]; const label = p.undo ? t('common.undo') : def.actionLabel ? def.actionLabel(p) : null;
    return html`<div class=${cx('toast-wrap', aboveNav && 'above-nav')}><div class="toast" style=${{ '--toast-color': color }} role=${def.kind === 'error' ? 'alert' : 'status'} aria-live="polite" data-toast=${toast.id}><${Icon} name=${icon} size=${18} class="toast-icon" /><span class="toast-text">${def.text(p)}</span>${label ? html`<button type="button" class="toast-action" data-action=${toast.id + (p.undo ? '.undo' : '.action')} onClick=${() => { ui.hideToast(); (p.undo || p.action) && (p.undo || p.action)(); }}>${label}</button>` : null}<button type="button" class="iconbtn is-sm" style="color:inherit;width:32px;height:32px" aria-label=${t('a11y.close')} data-action=${toast.id + '.close'} onClick=${() => ui.hideToast()}><${Icon} name="x" size=${16} /></button></div></div>`; }

  /* ---------- device ---------- */
  function Device({ fluid, splash }) { const theme = app.theme(); const route = nav.current(); const darkChrome = theme === 'dark' || ['CLB-03', 'EVT-02', 'MGT-07'].includes(route.screen); const ref = useRef();
    useEffect(() => { const el = ref.current; if (!el) return; const onClick = (e) => { const target = e.target.closest('[data-action]'); const inter = e.target.closest('button,a,[role=button],[role=switch],[role=tab],[role=checkbox],[role=radio],[role=option],[role=menuitem],input,textarea,select'); if (inter && !target && !inter.closest('[data-action]')) { registry.dead.push({ at: Date.now(), screen: route.screen, html: inter.outerHTML.slice(0, 120) }); return; } if (!target) return; const action = target.getAttribute('data-action'); if (!action || action === 'UNSET') { registry.dead.push({ at: Date.now(), screen: route.screen, html: target.outerHTML.slice(0, 120) }); return; }
        const before = { state: store.state, route: nav.current().key, sheets: ui.sheets.length, dialogs: ui.dialogs.length, menu: !!ui.menu, toast: ui.toast && ui.toast.key, busy: target.getAttribute('aria-busy') };
        registry.record(action, null);
        const classify = () => { const r = []; if (nav.current().key !== before.route) r.push('navigation'); if (ui.sheets.length !== before.sheets) r.push('sheet'); if (ui.dialogs.length !== before.dialogs) r.push('dialog'); if (!!ui.menu !== before.menu) r.push('menu'); if ((ui.toast && ui.toast.key) !== before.toast) r.push('toast'); if (store.state !== before.state) r.push('state'); if (target.isConnected && target.getAttribute('aria-busy') === 'true') r.push('loading'); if (target.isConnected && (target.getAttribute('aria-expanded') != null || target.getAttribute('aria-selected') != null || target.getAttribute('aria-checked') != null || target.getAttribute('aria-pressed') != null)) r.push('state'); return r; };
        setTimeout(() => classify().forEach((x) => registry.addResult(action, x)), 80); setTimeout(() => classify().forEach((x) => registry.addResult(action, x)), 1400); };
      el.addEventListener('click', onClick, true); return () => el.removeEventListener('click', onClick, true); }, [route.screen]);
    useEffect(() => { const onKey = (e) => { if (e.key === 'Escape') { if (ui.closeTop()) e.stopPropagation(); } }; const el = ref.current; el && el.addEventListener('keydown', onKey); return () => el && el.removeEventListener('keydown', onKey); }, []);
    return html`<div ref=${ref} class=${cx('gu-root device', fluid && 'is-fluid')} data-theme=${theme} lang=${app.locale()} style=${{ '--ts': app.textScale() }}>
      <${StatusBar} dark=${darkChrome} />${!fluid ? html`<div class="island" />` : null}
      <${ScreenHost} />${nav.mode === 'app' && nav.depth() === 1 ? html`<${BottomNav} />` : null}
      <${Overlays} />${splash ? html`<div class="splash splash-overlay" style="z-index:300" aria-hidden="true"><${Logo} size=${96} /><span class="t-title-l" style="letter-spacing:.04em">${app.APP_NAME}</span><span class="t-caption" style="position:absolute;bottom:40px">v${app.APP_VERSION}</span></div>` : null}<div class=${cx('homebar', darkChrome && 'on-dark')} /></div>`; }

  /* ---------- control panel ---------- */
  function Panel({ compact }) { const s = app.state.session; const u = app.uid(); const me = app.me(); const pend = u ? sel().pendingOf(u) : [];
    const G = ({ title, children }) => html`<div class="panel-group"><span class="t-overline">${title}</span>${children}</div>`;
    const decide = (approve) => { const m = pend[0]; if (!m) { app.toast('TST-X21'); return; } const club = sel().club(m.clubId); app.dispatch(approve ? 'membership.approve' : 'membership.reject', { clubId: m.clubId, userId: u, actorId: club.presidentId, reason: approve ? undefined : 'quota' }); app.toast(approve ? 'TST-27' : 'TST-28', { name: me.name }); };
    return html`<div class="panel gu-root" data-theme=${app.theme()} style=${compact ? { padding: '12px 16px' } : undefined}>
      <${G} title=${t('panel.account')}><div class="col gap6">${DEMO_ACCOUNTS.map((a) => { const usr = sel().user(a.id); return html`<button type="button" key=${a.id} class=${cx('account-row', u === a.id && 'is-active')} data-action=${'PANEL.login.' + a.id} onClick=${() => GU.auth.afterLogin(a.id)} title=${t('panel.loginAs')}><${Avatar} user=${usr} size=${30} /><span class="flex1 col"><span class="t-label-m c-heading ellipsis">${usr.name}</span><span class="t-caption" style="font-size:11px">${t(a.roleKey)} · ${t(a.descKey)}</span></span>${u === a.id ? html`<${Icon} name="circle-check" size=${16} class="c-brand" />` : html`<${Icon} name="log-in" size=${16} class="c-muted" />`}</button>`; })}</div><${Button} variant="outline" icon="log-out" label=${t('auth.logout')} action="PANEL.logout" onClick=${() => GU.auth.logout()} /></${G}>
      <${G} title=${t('panel.appearance')}><div class="panel-row"><span>${t('settings.theme')}</span></div><${Segmented} options=${[{ id: 'system', label: t('theme.system') }, { id: 'light', label: t('theme.light') }, { id: 'dark', label: t('theme.dark') }]} value=${s.theme || 'system'} onChange=${(v) => app.dispatch('session.set', { theme: v })} action="PANEL.theme" /><div class="panel-row"><span>${t('settings.language')}</span></div><${Segmented} options=${[{ id: 'tr', label: 'TR' }, { id: 'en', label: 'EN' }]} value=${app.locale()} onChange=${(v) => { app.dispatch('session.set', { locale: v }); try { document.documentElement.lang = v; } catch (e) { } }} action="PANEL.lang" /><div class="panel-row"><span>${t('settings.textSize')}</span></div><${Segmented} options=${[{ id: '1', label: '%100' }, { id: '1.3', label: '%130' }, { id: '1.6', label: '%160' }]} value=${String(s.textScale || 1)} onChange=${(v) => app.dispatch('session.set', { textScale: Number(v) })} action="PANEL.textScale" /><div class="panel-row"><span>${t('panel.frame')}</span><${Switch} checked=${app.state.ui.frame !== false} onChange=${(v) => app.dispatch('ui.set', { frame: v })} action="PANEL.frame" label=${t('panel.frame')} /></div></${G}>
      <${G} title=${t('panel.network')}><${Segmented} options=${[{ id: 'online', label: t('panel.online') }, { id: 'offline', label: t('panel.offline') }, { id: 'slow', label: t('panel.slow') }]} value=${app.state.ui.network} onChange=${(v) => app.dispatch('ui.set', { network: v })} action="PANEL.network" /></${G}>
      <${G} title=${t('panel.data')}><${Segmented} options=${[{ id: 'normal', label: t('panel.normal') }, { id: 'empty', label: t('panel.empty') }, { id: 'error', label: t('panel.error') }]} value=${app.state.ui.dataMode} onChange=${(v) => app.dispatch('ui.set', { dataMode: v })} action="PANEL.dataMode" /><${Button} variant="outline" icon="loader-circle" label=${t('panel.showLoading')} action="PANEL.loading" onClick=${() => { app.dispatch('ui.set', { loadingUntil: Date.now() + 3000 }); setTimeout(() => app.refresh(), 3100); }} /></${G}>
      <${G} title=${t('panel.system')}><${Button} variant="outline" icon="download" label=${t('panel.forceUpdate')} action="PANEL.forceUpdate" onClick=${() => app.openDialog('DLG-26')} /><${Button} variant="outline" icon="lock" label=${t('panel.sessionExpired')} action="PANEL.sessionExpired" onClick=${() => app.openDialog('DLG-27')} /><${Button} variant="outline" icon="bell-ring" label=${t('panel.simulateNotif')} action="PANEL.simulateNotif" onClick=${() => (u ? app.flows.simulateNotification() : app.toast('TST-X22'))} /><${Button} variant="outline" icon="refresh-cw" label=${t('panel.resetNotifPerm')} action="PANEL.resetNotifPerm" onClick=${() => { app.dispatch('session.set', { notifPermission: 'default', notifAskedAt: null }); if (u) app.openDialog('DLG-03'); }} /></${G}>
      <${G} title=${t('panel.applicationSim')}><p class="t-caption">${pend.length ? t('panel.pendingAt', { club: (sel().club(pend[0].clubId) || {}).name }) : t('panel.noPending')}</p><div class="row gap8"><${Button} variant="tonal" size="sm" icon="check" label=${t('panel.approveMine')} action="PANEL.approveMine" onClick=${() => decide(true)} style=${{ flex: 1 }} /><${Button} variant="outline" size="sm" icon="x" label=${t('panel.rejectMine')} action="PANEL.rejectMine" onClick=${() => decide(false)} style=${{ flex: 1 }} /></div></${G}>
      <${G} title=${t('panel.dataGroup')}><${Button} variant="outline" icon="refresh-cw" label=${t('panel.resetData')} action="PANEL.resetData" onClick=${() => { app.dispatch('seed.reset'); app.toast('TST-X23'); }} /><${Button} variant="outline" icon="download" label=${t('panel.downloadJson')} action="PANEL.downloadJson" onClick=${() => GU.downloadText(GU.exportDemoData ? GU.exportDemoData() : JSON.stringify(app.state, null, 2), 'demo-data.json', 'application/json')} /></${G}>
    </div>`; }

  /* ---------- site ---------- */
  function SideMenu({ onPick }) { return html`<nav class="sidemenu" aria-label=${t('site.menu')}><div class="row gap10" style="padding:4px 8px 16px"><${Logo} size=${32} /><span class="t-title-s" style="letter-spacing:.03em">${app.APP_NAME}</span></div>${PAGES_META.map(([id, k, icon]) => html`<button type="button" key=${id} class="menu-item" aria-current=${site.page === id ? 'page' : undefined} data-action=${'SITE.page.' + id} onClick=${() => { site.setPage(id); onPick && onPick(); }}><${Icon} name=${icon} size=${18} />${t(k)}</button>`)}<div class="spacer" /><p class="t-caption" style="padding:8px">${t('site.footer')}</p></nav>`; }
  function Frame({ splash }) { const stageRef = useRef(); const frame = app.state.ui.frame !== false;
    const calc = (hh, ww) => Math.min(1, (hh - 32) / (frame ? 870 : 844), (ww - 32) / (frame ? 416 : 390));
    const guess = () => { const ww = window.innerWidth; const stageW = ww >= 1024 ? ww - 232 - 340 : ww; return calc(window.innerHeight, stageW); };
    const [scale, setScale] = useState(guess);
    useLayoutEffect(() => { const el = stageRef.current; if (!el) return; const measure = () => setScale(el.clientHeight > 100 ? calc(el.clientHeight, el.clientWidth) : guess()); measure(); const ro = new ResizeObserver(measure); ro.observe(el); window.addEventListener('resize', measure); return () => { ro.disconnect(); window.removeEventListener('resize', measure); }; }, [frame]);
    return html`<div class="stage" ref=${stageRef}><div class=${cx(frame && 'frame')} style=${{ transform: `scale(${scale})`, transformOrigin: 'center' }}>${frame ? html`<i class="side-btn" style="left:-5px;top:120px;height:32px" /><i class="side-btn" style="left:-5px;top:170px;height:60px" /><i class="side-btn" style="left:-5px;top:240px;height:60px" /><i class="side-btn" style="right:-5px;top:190px;height:90px" />` : null}<${Device} splash=${splash} /></div></div>`; }
  function Site() { const [, tick] = useState(0); const [w, setW] = useState(window.innerWidth); const [drawer, setDrawer] = useState(false); const [splash, setSplash] = useState(() => Date.now() < (GU.splashUntil || 0));
    // subscribe synchronously (not in an effect) so store changes re-render even when the host suspends timers/rAF
    const subs = GU.useMemo(() => { const re = () => tick((x) => x + 1); return [store.subscribe(re), nav.subscribe(re), ui.subscribe(re), (site.listeners.add(re), () => site.listeners.delete(re))]; }, []);
    useEffect(() => { const onR = () => setW(window.innerWidth); window.addEventListener('resize', onR); const id = splash ? setTimeout(() => setSplash(false), Math.max(0, (GU.splashUntil || 0) - Date.now())) : null; return () => { subs.forEach((f) => f()); window.removeEventListener('resize', onR); clearTimeout(id); }; }, []);
    const prevNet = useRef(app.state.ui.network); useEffect(() => { const n = app.state.ui.network; if (prevNet.current === 'offline' && n !== 'offline') app.toast('TST-25'); prevNet.current = n; });
    useEffect(() => { try { document.documentElement.lang = app.locale(); } catch (e) { } }, [app.locale()]);
    const theme = app.theme(); const mobile = w < 768; const tablet = w >= 768 && w < 1024; const page = site.page; const Page = GU.PAGES && GU.PAGES[page];
    const center = page === 'proto' ? (mobile ? html`<${Device} fluid splash=${splash} />` : html`<${Frame} splash=${splash} />`) : (Page ? html`<div class="page"><${Page} /></div>` : null);
    return html`<div class=${cx('gu-root site', page !== 'proto' && 'is-page', tablet && 'is-tablet', mobile && 'is-mobile')} data-theme=${theme} lang=${app.locale()}>
      ${!mobile && !tablet ? html`<${SideMenu} />` : null}${center}${!mobile && !tablet && page === 'proto' ? html`<${Panel} />` : null}
      ${mobile || tablet ? html`<button type="button" class="demo-fab" data-action="SITE.demo" onClick=${() => setDrawer(true)} aria-haspopup="dialog"><${Icon} name="sliders-horizontal" size=${18} />${t('site.demo')}</button>` : null}
      ${drawer ? html`<div class="drawer-scrim" onClick=${() => setDrawer(false)} data-action="SITE.drawer.scrim" /><div class="drawer gu-root" data-theme=${theme} role="dialog" aria-modal="true" aria-label=${t('site.demo')}><div class="sheet-handle" /><div class="row between" style="padding:8px 8px 0 16px"><span class="t-title-s">${t('site.demo')}</span><${IconButton} icon="x" label=${t('a11y.close')} action="SITE.drawer.close" onClick=${() => setDrawer(false)} /></div><div class="hscroll py8">${PAGES_META.map(([id, k, icon]) => html`<${GU.Chip} key=${id} icon=${icon} label=${t(k)} selected=${site.page === id} action=${'SITE.page.' + id} onClick=${() => { site.setPage(id); setDrawer(false); }} />`)}</div><${Panel} compact /></div>` : null}</div>`; }

  /* ---------- boot ---------- */
  let booted = false;
  function boot() { if (booted) return; booted = true; injectCSS(); const saved = store.load(); store.set(saved || seed(), { persist: false }); if (nav.mode === 'splash') { GU.splashUntil = document.visibilityState === 'hidden' ? 0 : Date.now() + 1200; try { GU.auth.routeInitial(); } catch (e) { console.error(e); nav.resetTo('AUT-01'); } } initIcons(); try { document.documentElement.lang = app.locale(); } catch (e) { } try { matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => app.refresh()); } catch (e) { } }
  class GuShell extends HTMLElement { connectedCallback() { boot(); render(h(Site), this); } disconnectedCallback() { render(null, this); } }
  if (!customElements.get('gu-shell')) customElements.define('gu-shell', GuShell);
  GU.boot = boot; GU.Site = Site; GU.Device = Device; GU.Panel = Panel; GU.PAGES = GU.PAGES || {};
})();
